### ISSUE TITLE
How to create a DWrite.Factory2?

### ISSUE THREAD

**Issue by dontpanic92** [sharpdx/SharpDX#1027]
Hi there,

I noticed that for `DWrite.Factory` and `DWrite.Factory1`, there are constructors for creating the factories:

```
public Factory1();
public Factory1(FactoryType factoryType);
public Factory1(IntPtr nativePtr);
```

But for `DWrite.Factory2`, there is only one constructor:

```
public Factory2(IntPtr nativePtr);
```

Are the constructors not mapped? Or did I not get the correct way to create it?

Thanks

**Comment by xoofx** [comment]
> Are the constructors not mapped? Or did I not get the correct way to create it?

Likely not mapped

**Comment by xoofx** [comment]
Though you may be able to get a `IDWriteFactory2` from a `Factory1` with a QueryInterface<IDWriteFactory2> (haven't tried)

**Comment by dontpanic92** [comment]
`QueryInterface` seems working. Thanks!

Closing the issue, but it would be appreciate if the constructors mapping could be added
