### ISSUE TITLE
SharpDX.Direct2D1.ResultCode values disappeared

### ISSUE THREAD

**Issue by andrew-boyarshin** [sharpdx/SharpDX#1028]
[List of disappeared APIs from 4.1.0-ci217](https://fuget.org/packages/SharpDX.Direct2D1/4.1.0/lib/netstandard1.1/diff/4.1.0-ci217/)

All values in ResultCode disappeared, the class itself stays empty. Is that intentional?

**Comment by xoofx** [comment]
> All values in ResultCode disappeared, the class itself stays empty. Is that intentional?

No, that's weird, don't recall a change related to this. Maybe a side effect to move to a newer include SDK where these codes are defined somewhere else? If someone can have look at this, PR welcome.

**Comment by jkoritzinsky** [comment]
This is fixed on master as of #1057
