### ISSUE TITLE
XAudio2 can't initalize under win10

### ISSUE THREAD

**Issue by mcdis** [sharpdx/SharpDX#1030]
```
new XAudio2();
```
The instance has created but DeviceCount throw exception. Version is 2.8
2.7 and 2.9 can't create (Dll not found exception).
App - 64 bit
Win10 10.0.14393

**Comment by mikestek** [comment]
I have a similar issue. If I use the default version then I get the 'Nullable object must have a value' when creating the MasteringVoice. It happens for x86 and x64, desktop and uwp. If I force 2,7 then it works on desktop.

**Comment by SergeyBaryshev** [comment]
Same here like **mikestek** said.

Some info:
With 4.0.1 (previous version of SharpDX) on Win10 with Default or null parameter constructor creates AudioDX as 2.8 and on Win7 as 2.7 automatically. Now (4.1.0) it only works with 2.7 by manually.

**Comment by waltdestler** [comment]
Not sure if this is actually the same issue as OP's, but I too am getting the 'Nullable object must have a value' exception when creating the MasteringVoice. If anyone has a workaround without forcing 2.7, that'd be awesome. Otherwise I guess I'll have to downgrade back to 4.0.1.

**Comment by SouldomainTM** [comment]
@waltdestler
I think it's the same. I'm also having the same problem. I had to revert to 4.0.1.

**Comment by h1cks** [comment]
I have also reverted back, but to 4.1.0 I believe.

**Comment by munawarb** [comment]
Downgrading to 4.0.1 of XAudio2 fixed the issue for me. Thanks guys for all the pointers! For the longest time I thought it was something on my end.

**Comment by SouldomainTM** [comment]
Personally, `4.2.0-ci284` works for me.

**Comment by h1cks** [comment]
Tested my code fully on 4.0.1 and was fine.  So promoted to 4.2.0-ci284 and MasteringVoice is missing the volume property.  I also have installed 4.2.0 and has same issue.  Volume property has disappeared since 4.0.1

**Comment by h1cks** [comment]
Just to add, I didnt test 4.2.0-ci284 due to the compile issues.

**Comment by SouldomainTM** [comment]
Yeah, keep in mind with my test, that my engine is still in pre-alpha so isn't using almost any of the audio features. So that's why I could compile it seems. My code isn't using any volume property just yet. Only the initialization works.

**Comment by xoofx** [comment]
> Tested my code fully on 4.0.1 and was fine. So promoted to 4.2.0-ci284 and MasteringVoice is missing the volume property. I also have installed 4.2.0 and has same issue. Volume property has disappeared since 4.0.1

@jkoritzinsky maybe a regression there too?

**Comment by SouldomainTM** [comment]
@h1cks , are you sure that the `Volume `property belongs into the `MasteringVoice `class? The VS's object viewer doesn't show me for `4.0.1` a `Volume `property either. It's the `Voice `class that has one property named `Volume`, though.

**Comment by h1cks** [comment]
@SouldomainTM Can confirm that 4.0.1 has a mastering voice Volume attribute, in mastering voice there is a SetVolume but there is no volume attribute, this is actually off the inherited class "Voice" which both sourcevoice and mastering voice share.  The mastering voice was the only time I was using the attribute of Volume.  Confirmed its `voice `class.

**Comment by SouldomainTM** [comment]
@h1cks , I think you may want to make a new thread for this issue. The `Volume `property isn't in` 4.2.0` preview either. There is only some `SetVolume`, and `GetVolume `method in `Voice `class.

**Comment by jkoritzinsky** [comment]
@xoofx The signature for `SetVolume` isn't compatible with the property generator. I'd suggest manually writing the property or just using the `GetVolume` and `SetVolume` methods until I add a feature to the property generation to account for defaulted parameters.

**Comment by h1cks** [comment]
I will attempt to retry the release candidate tonight.  I have also discovered a side issue which I will raise as  a seperate ticket.

**Comment by xoofx** [comment]
> @xoofx The signature for SetVolume isn't compatible with the property generator. I'd suggest manually writing the property or just using the GetVolume and SetVolume methods until I add a feature to the property generation to account for defaulted parameters.

Ok, that's unfortunate that I didn't catch this during the SharpGen switch, because I would have prefer that we don't introduce API regression.

Anyway, ok, so @h1cks please use GetVolume/SetVolume instead on the new API

**Comment by feliwir** [comment]
I am still getting this issue with SharpDX.XAudio2 4.2.0 stable.
