### ISSUE TITLE
Register to render loop

### ISSUE THREAD

**Issue by Ixiodor** [sharpdx/SharpDX#1032]
Hello,
there is a way to register to a renderloop without actually using RenderLoop.Run?
What i want is a controllated render loop(V-Sync working) and a callback to "Draw" in my form to notify me when to draw.

**Comment by xoofx** [comment]
Use `RenderLoop.NextFrame` and you can handle your loop on your own, that's what `RenderLoop.Run` is doing:

https://github.com/sharpdx/SharpDX/blob/bdb12ec420d2b6ff32da184453c722380596ceb8/Source/SharpDX.Desktop/RenderLoop.cs#L206-L219
