### ISSUE TITLE
ISwapChainPanelNative, ISwapChainBackgroundPanelNative disappear

### ISSUE THREAD

**Issue by amerkoleci** [sharpdx/SharpDX#1035]
Seams that due to recent binding generator tool change thoose 2 interfaces disappeared.

@jkoritzinsky Any thoughts?

**Comment by xoofx** [comment]
Are you sure? Just downloaded manually the nupkg for SharpDX.DXGI and I'm seeing them in all .NET targets

**Comment by xoofx** [comment]
Why? They are, I can see them on latest. 4.1.0 was uploaded like last week.

**Comment by jkoritzinsky** [comment]
I was thinking the CI builds aren't being uploaded any more for some reason.

**Comment by mellinoe** [comment]
The classes haven't disappeared, but the `Swapchain` property on both has been removed.

**Comment by amerkoleci** [comment]
I see, lets keep this opened, I will submit PR

**Comment by jkoritzinsky** [comment]
I just fixed the bug that caused the property to not be generated. It will be out in the next SharpGenTools release.

**Comment by amerkoleci** [comment]
Thanks @jkoritzinsky, maybe you can release PR for SharpDX that updates the SharpGenTools package please?

**Comment by jkoritzinsky** [comment]
There's a bug that I've been unable to pin down in some of the code in `SharpGen.Runtime` package that I'd really like to get fixed before I release 1.1. I'll release right after I get that bug fixed.
