### ISSUE TITLE
[XAudio2] CreateMasteringVoice throws InvalidOperationException

### ISSUE THREAD

**Issue by SomeAnon42** [sharpdx/SharpDX#1036]
...when accessing the ``Value`` property of a nullable object without checking if it ``HasValue``.
Seems like a codegen issue.
![image](https://user-images.githubusercontent.com/6377116/41247768-c007d6ca-6db7-11e8-9368-866a1bef826a.png)

Version used: 4.1.0

**Comment by amerkoleci** [comment]
@jkoritzinsky any thoughts here as well?

**Comment by jkoritzinsky** [comment]
I'll take a look.

**Comment by jkoritzinsky** [comment]
@SomeAnon42 what version of SharpDX are you using?

That looks like it's using the old code-generator. (The current generated code doesn't look the same or seem to have the bug).

**Comment by SomeAnon42** [comment]
I'm using the latest version - 4.1.0. Previous versions *do not* have this problem.

**Comment by jkoritzinsky** [comment]
Found the bug. It's a bug in SharpGenTools.Sdk 1.0.0. I think it's fixed in SharpGenTools master but I'm not positive. I'll update this issue when I've verified that it's fixed.

**Comment by jkoritzinsky** [comment]
Yep. I ended up fixing this bug when I refactored all of the marshalling code for some of the upcoming features in SharpGenTools 1.1.0.

**Comment by amerkoleci** [comment]
#1037 seams affected as well
