### ISSUE TITLE
MediaFoundation attributes/dxgimanager throws StackOverflowException

### ISSUE THREAD

**Issue by amwx** [sharpdx/SharpDX#1039]
The latest version of the MediaFoundation dll (4.1.0.0) throws a StackOverflowException when attempting to set the DXGIManager in the MediaEngineAttributes

`MediaEngineAttributes attr = new MediaEngineAttributes();

attr.DxgiManager = dxgiManager; // Stackoverflow thrown when this line is executed`

And this is all following the Desktop Video Player Sample App.

I have another app that I wrote about a year ago that targets version 3.1 of the SharpDX dlls, and it runs fine, so I am assuming the cause is something that changed between v3.1 and v4.1?

**Comment by amerkoleci** [comment]
@jkoritzinsky Same here?

**Comment by jkoritzinsky** [comment]
This one's a bug in SharpDX after switching the definition of ComObject/IUnknown to not be special. I'm working on a PR for it now.

**Comment by Ixiodor** [comment]
Problem is still here...why closed?

**Comment by DTXMania** [comment]
from MSDN:

> The IsSubclassOf method cannot be used to determine whether an interface derives from another interface, or whether a class implements an interface.

Dont change line 278 of MediaAttributes.cs.
