### ISSUE TITLE
SharpDX.DirectWrite.FontFace.GetFiles() System.NullReferenceException

### ISSUE THREAD

**Issue by EssenRoc** [sharpdx/SharpDX#1040]
I just update SharpDX.Direct2D1 4.0.1 => 4.1.0.

look here [SharpDX-Samples/Desktop/DirectWrite/FontEnumeration/Program.cs](https://github.com/sharpdx/SharpDX-Samples/blob/ed7e80cdcac145cf1864c6b9358a558e5fe8deb6/Desktop/DirectWrite/FontEnumeration/Program.cs)

**Comment by amerkoleci** [comment]
@jkoritzinsky

**Comment by jkoritzinsky** [comment]
Yep that's a bug in the code generator. I'll file an issue on SharpGenTools and take a look at fixing it.

**Comment by jkoritzinsky** [comment]
Fixed on the code-gen end. Will be fixed after SharpGenTools is updated.

**Comment by xoofx** [comment]
yes
