### ISSUE TITLE
SharpDX.Direct3D11.ShaderResourceViewDescription.BufferResource ElementCount and ElementWidth members alias

### ISSUE THREAD

**Issue by helmutbressler** [sharpdx/SharpDX#1041]
Setting one member changes also the other. At least in the NuGet packet version 4.1

Sorry, I'm quite new to SharpDX, I couldn't manage to build it from source on my own. Ohterwise I would have checked where this behaviour is coming from.

**Comment by amerkoleci** [comment]
Thats correct as the are basically union, even in C/C++:

`
typedef struct D3D11_BUFFER_SRV {
  union {
    UINT FirstElement;
    UINT ElementOffset;
  };
  union {
    UINT NumElements;
    UINT ElementWidth;
  };
} D3D11_BUFFER_SRV;
`
`
[StructLayout(LayoutKind.Explicit)]
public struct BufferResource
{
	/// <summary>
	/// <dd> <p> Number of bytes between the beginning of the buffer and the first element to access. </p> </dd>
	/// </summary>
	/// <msdn-id>ff476094</msdn-id>
	/// <unmanaged>FirstElement</unmanaged>
	/// <unmanaged-short>FirstElement</unmanaged-short>
	[FieldOffset(0)]
	public int FirstElement;

	/// <summary>
	/// <dd> <p> The offset of the first element in the view to access, relative to element 0. </p> </dd>
	/// </summary>
	/// <msdn-id>ff476094</msdn-id>
	/// <unmanaged>ElementOffset</unmanaged>
	/// <unmanaged-short>ElementOffset</unmanaged-short>
	[FieldOffset(0)]
	public int ElementOffset;

	/// <summary>
	/// <dd> <p> The total number of elements in the view. </p> </dd>
	/// </summary>
	/// <msdn-id>ff476094</msdn-id>
	/// <unmanaged>NumElements</unmanaged>
	/// <unmanaged-short>NumElements</unmanaged-short>
	[FieldOffset(4)]
	public int ElementCount;

	/// <summary>
	/// <dd> <p> The width of each element (in bytes). This can be determined from the format stored in the shader-resource-view description. </p> </dd>
	/// </summary>
	/// <msdn-id>ff476094</msdn-id>
	/// <unmanaged>ElementWidth</unmanaged>
	/// <unmanaged-short>ElementWidth</unmanaged-short>
	[FieldOffset(4)]
	public int ElementWidth;
}

`

**Comment by helmutbressler** [comment]
That makes totally sense to me now. I should have checked the d3d11 documentation before posting. Apologies for bothering you with that (, but at least I know now that I did the SRV setup in my code incorrect). Thank you very much!

**Comment by amerkoleci** [comment]
No problem :) Glad to help out.
