### ISSUE TITLE
TextFormat.[TextAlignment,TextLayout] -> SetTextAlignment,SetTextLayout

### ISSUE THREAD

**Issue by Axiverse** [sharpdx/SharpDX#1044]
TextFormat used to have TextAlignment and TextLayout as get, set properties, but now has been separated into SetTextAlignment and SetTextLayout methods. Is this intentional or an unintended side effect of automation?

**Comment by SergeyBaryshev** [comment]
Same thing with Media Foundation - some of the properties turns to separate get and set methods. I think this is some bug of code generator.
