### ISSUE TITLE
A few regresions with SharpGenTools

### ISSUE THREAD

**Issue by xoofx** [sharpdx/SharpDX#1048]
Tracking here a few regressions with SharpGenTool before pushing for 4.2.0 (compared to 4.0.1):

- [ ] All abbreviations (max, min...etc.) are no longer expanded to their longer form (see https://www.fuget.org/packages/SharpDX.Direct3D11/4.2.0-ci259/lib/netstandard1.1/diff/4.0.1/)
- [ ] Strange naming in D3DCompiler of enum ParameterFlags (e.g pfIn) (see https://www.fuget.org/packages/SharpDX.D3DCompiler/4.2.0-ci259/lib/netstandard1.1/diff/4.0.1/)
- [ ] A few ResultCode have been removed and/or renamed (direct2d1 https://www.fuget.org/packages/SharpDX.Direct2D1/4.2.0-ci259/lib/netstandard1.1/diff/4.0.1/ dxgi https://www.fuget.org/packages/SharpDX.DXGI/4.2.0-ci259/lib/netstandard1.1/diff/4.0.1/ ....etc.)

**Comment by xoofx** [comment]
> Yeah I'm working on trying to nail down the cause of the naming issue.

Amazing, thanks!

**Comment by jkoritzinsky** [comment]
The next CI build of SharpGenTools should have fixes for the 1st and 3rd regression. I think I still need to investigate the 2nd one in the list.
