### ISSUE TITLE
ShaderBytecode.CompileFromFile()  System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by bryaan** [sharpdx/SharpDX#1051]
No matter what I try I can't get D3DCompiler to compile.
I tried it on the online compilers and works fine.

Using directx11 and SharpDx 4.1.0

```
var vertexShaderByteCode = SharpDX.D3DCompiler.ShaderBytecode.CompileFromFile(vsFile, "VSMain", "vs_5_0");
```

System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'

**Comment by bryaan** [comment]
My hlsl file

```

struct PSInput
{
	float4 position : SV_POSITION;
	/* float4 color : COLOR; */
};


PSInput VSMain(float4 position : POSITION, float4 color : COLOR)
{
	PSInput output;

	output.position = position;
	//output.position = mul(input.pos, worldViewProj);
	//output.color = input.color;

	return output;
}

float4 PSMain(PSInput input) : SV_TARGET
{
	//return vec4(1.0, 0.0, 0.0, 1.0);
	//return float4(1.0f, 0.0f, 0.0f, 1.0f);
	//return input.color;
	return input.position;
}
```

**Comment by bryaan** [comment]
Seems to work fine with the dxc compiler

dxc /T vs_5_0 /E VSMain "Minicube.hlsl" /Fo "Minicube.cso"

Is there some deprecation of D3DCompiler?

**Comment by xoofx** [comment]
@jkoritzinsky I had a look at the codegen and it seems completely off.

The 3.1.1 version of `Blob.GetBufferSize`

```C#
		internal unsafe PointerSize GetBufferSize()
		{
			return calli(System.Void*(System.Void*), this._nativePointer, *(*(IntPtr*)this._nativePointer + (IntPtr)4 * (IntPtr)sizeof(void*)));
		}
```

while the latest version:

```C#
		internal unsafe PointerSize GetBufferSize()
		{
			PointerSize result;
			object arg_20_0 = calli(System.Void*(System.Void*,System.Void*), this._nativePointer, &result, *(*(IntPtr*)this._nativePointer + (IntPtr)4 * (IntPtr)sizeof(void*)));
			return result;
		}
```

It is transforming the result into a pointer passed by argument, which is not valid.

This is quite a serious regression. Could you fix this issue in SharpGenTools and then go through all the samples and check that they are working correctly? (that's always what I did when I was doing a new version, I haven't done this for quite a while, but now checking and having even the most basic D3D11 sample not working is not great)

**Comment by bryaan** [comment]
After some changes I got it working, so not a bug. closing.

**Comment by jkoritzinsky** [comment]
@xoofx I just checked in a fix for this bug with a unit test into SharpGenTools master.

**Comment by xoofx** [comment]
> @xoofx I just checked in a fix for this bug with a unit test into SharpGenTools master.

Amazing. Do you need to proceed on publishing a new nuget for it? Btw, What do you think of making SharpGenTools a sub repo so that we can iterate more quickly without pushing an official SharpGenTools package?

**Comment by jkoritzinsky** [comment]
There should be a new package on the MyGet feed that you could use.

If you want to make SharpGenTools a submodule, go for it! I'm not a super big fan of submodules and it might be a little annoying to get the MSBuild scripts working the way you want, but that is an option.

**Comment by jkoritzinsky** [comment]
I think I forgot to bump the version after the release. Give me a sec to commit that. There should be a package up in about 5 minutes or so.

**Comment by Commisar-Deth** [comment]
Having the same problem as bryaan, trying to find where you posted but the myget feed url for sharpgentools just routes me back to their homepage, is it private? how can I get hold of it, the last release is 15 days ago and this post is 6 at the time of writing
