### ISSUE TITLE
After updating Sharpdx inputlayout gives error

### ISSUE THREAD

**Issue by pekira** [sharpdx/SharpDX#1056]
I have updated sharpdx to the most recent version(4.2) before updating everting was working fine but after updating i started getting a error on inputlayout i have tried to reinstall all dlls but the error continues.

I have checked and nothing is null and the file exists

`SharpDX.SharpDXException: 'HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: O parâmetro está incorreto.
'
`
Message: O parâmetro está incorreto. translates to Message the parameter is invalid.

`            ShaderBytecode bytecode = ShaderBytecode.CompileFromFile("HSLS/MiniCube.fx", "VS", "vs_4_0");
            vertexShader = new VertexShader(Device, bytecode);

            // Layout from VertexShader input signature 
            layout = new InputLayout(Device, ShaderSignature.GetInputSignature(bytecode), new[]
            {
                new InputElement("POSITION", 0, Format.R32G32B32A32_Float, 0, 0),
                new InputElement("COLOR", 0, Format.R32G32B32A32_Float, 16, 0)
            });`

Edit:
I have tried samples and they give the same error with the newest version (4.2)

**Comment by amerkoleci** [comment]
@jkoritzinsky Any thoughts?

**Comment by jkoritzinsky** [comment]
@amerkoleci I'm not sure with this one. I'll try to investigate but if you could take a look too that'd be good.

**Comment by jkoritzinsky** [comment]
I believe this is fixed in the next CI drop of SharpGenTools. #1058 is definitely fixed by it (samples correctly run).
