### ISSUE TITLE
[4.2.0 NuGet] Strange behavior with "SharpDX.xml".

### ISSUE THREAD

**Issue by SergeyBaryshev** [sharpdx/SharpDX#1071]
Created a new project, added references to SharpDX packages via Nuget. After downloading I have checked them in "packages" folder. So is there bug with main SharpDX assembly?

.xml <-this!
SharpDX.dll
SharpDX.pdb

While others are fine:

SharpDX.MediaFoundation.dll
SharpDX.MediaFoundation.pdb
SharpDX.MediaFoundation.xml

Also "SharpDX.xml" is not copied to destination folder with application.

**Comment by amerkoleci** [comment]
Will submit PR ASAP
