### ISSUE TITLE
Setup myget

### ISSUE THREAD

**Issue by amerkoleci** [sharpdx/SharpDX#1098]
Hi @xoofx,

Can you setup myget server then I can push PR with nightly myget packages build?

You can take look at my engine repo (https://github.com/amerkoleci/vortice/blob/master/.appveyor.yml)
I have my own sharpdx myget but probably need yours one.

Thanks

**Comment by xoofx** [comment]
Not sure I would like to use myget, appveyor is supposed to provide this no? I saw in appveyor documentation something like this:

```
nuget:
  project_feed: true
```

that might be just enough?

**Comment by amerkoleci** [comment]
I see, can you do setup for that? Not sure I can do that from external

**Comment by xoofx** [comment]
Not sure my changes did something, but I think packages are available at: https://ci.appveyor.com/nuget/sharpdx 
Let me know if you are not able to use this

**Comment by amerkoleci** [comment]
Nice one, it works, let me submit PR with README.md update to show how to use nightly pckages.
Thanks

**Comment by amerkoleci** [comment]
PR #1099 added
