### ISSUE TITLE
Bug in Mapping.xml file?

### ISSUE THREAD

**Issue by RachamimYaakobov** [sharpdx/SharpDX#1133]
Why `unsigned int` [maped ](https://github.com/sharpdx/SharpDX/blob/master/Source/Mapping.xml#L514) to `System.Int32` instead of `System.UInt32`, and the same question about `unsigned short` and `unsigned longlong` that maped to `System.Int16` and `System.Int64` ?

**Comment by xoofx** [comment]
Because it is a very old decision that had to be made because SharpDX was meant to be compatible with SlimDX and all .NET APIs are mainly working with int. Literals in .NET are int, so that any usage of a SharpDX API would have had required to cast from int to uint.
