### ISSUE TITLE
D3D11 Effects linked with wrong d3dcompiler version

### ISSUE THREAD

**Issue by Telanor** [sharpdx/SharpDX#327]
It seems the linked version of d3dcompiler has changed again (to 47) and the same issues I had in this thread are back: http://sharpdx.org/forum/5-api-usage/1359-direct2d-effects-class-for-win7.

The dlls provided in the download in that thread still seem to work, but it requires having the 46 and 47 versions alongside each other.  The ones from the 2.5.1 download still reference version 44 though.  They should be updated.

Also, the d3dcompiler dlls in the Redist folder are version 46 but version 47 is the one needed.

**Comment by QuantumDeveloper** [comment]
@xoofx Hello. When will you integrate this fix to you framework? This is very actual bug.

**Comment by xoofx** [comment]
Sorry, I just merged it to the latest branch b311ce426740e26d5510a8f5cd3c07bb8f22bb20
There is still some work to do on this branch before we can release it (fix issue with all the RawXXX types and Direct2D effects... + compilation of the whole Toolkit)

**Comment by QuantumDeveloper** [comment]
@xoofx Could you please tell how much time will you need to finish those tasks? Just want to know how long will need to wait

**Comment by xoofx** [comment]
Several hours of work, but I have currently no spare time to work on this. Maybe after GDC.

**Comment by QuantumDeveloper** [comment]
Ok, I see. hope you will find some time to finish with next sharpdx release.

**Comment by QuantumDeveloper** [comment]
@xoofx hello.
Sorry for my impudence, but do you already have some spare time?
I just want to use effects with 11_2 libs on desktop, but without this fix included I couldnot do that.
Coulde you please say when you will fix this issue?
Thanks in advance.

**Comment by xoofx** [comment]
@QuantumDeveloper couldn't you just cherry pick the commit, branch from 2.6.3 and apply this commit to it? It will be easier if you just compile it yourself. The 3.0 branch is breaking other things that It will take more time to bring back to a working version (unrelated to this specific issue)

**Comment by QuantumDeveloper** [comment]
@xoofx I`d do that with pleasure, but I just caanot build your sources, because compiler found nearly 100 errors lelated to not found files:
```
Show Details	Severity	Code	Description	Project	File	Line
	Error		Source file 'M:\GameEditor\SharpDX-master_integration\Source\SharpDX.Direct3D11.Effects\Generated\LocalInterop.cs' could not be found.	SharpDX.Direct3D11.Effects	CSC	
	Error		Source file 'M:\GameEditor\SharpDX-master_integration\Source\SharpDX.DirectComposition\Generated\Enumerations.cs' could not be found.	SharpDX.DirectComposition	CSC	
	Error		Source file 'M:\GameEditor\SharpDX-master_integration\Source\SharpDX.DXGI\Generated\Interfaces.cs' could not be found.	SharpDX.DXGI	CSC	
	Error		Source file 'M:\GameEditor\SharpDX-master_integration\Source\SharpDX.DXGI\Generated\Structures.cs' could not be found.	SharpDX.DXGI	CSC	
	Error		"sgen.exe" exited with code 1.	SharpGen		
```
So, I just cannot build it by myself now.
I am using VS 2015 preview. I dont know, maybe this is VS bug and on VS 2013 everything OK, but I faced with this issue only trying to compile your sources.
Thats why I ask you to release a knew version via nuget.
In any case I think I will update my project to use v3.0 even with breaking changes.

**Comment by xoofx** [comment]
You should not have any errors, unless some per-requisities are not installed (at least, Microsoft .NET 3.5, Microsoft DirectX June 2010 SDK, Microsoft Windows SDK 7.1)

VS2015 preview is not supported.

**Comment by QuantumDeveloper** [comment]
```
VS2015 preview is not supported.
```
Seems, thats the reason. Will you enable VS 2015 support?

**Comment by QuantumDeveloper** [comment]
@xoofx 
Will you enable VS 2015 support?

**Comment by QuantumDeveloper** [comment]
@xoofx 
I build your changes at last and now I have an issue - fps is dropping from 1500 to 300 while I am not rendering and in debug mode of DirectX I see the following messages:

```
Warning: Live ComObject [0x62A522D830], potential memory leak: Active COM Object: [0x62A522D830] Class: [SharpDX.Direct3D11.EffectVectorVariable] Time [03/11/2015 00:53:07] Stack:
    d:\Docs\SharpDX-master_integration\Source\SharpDX\CppObject.cs(46,13) : Void .ctor(IntPtr)
    d:\Docs\SharpDX-master_integration\Source\SharpDX\ComObject.cs(35,9) : Void .ctor(IntPtr)
    d:\Docs\SharpDX-master_integration\Source\SharpDX.Direct3D11.Effects\Generated\Interfaces.cs(3974,9) : Void .ctor(IntPtr)
    d:\Docs\SharpDX-master_integration\Source\SharpDX.Direct3D11.Effects\Generated\Interfaces.cs(4648,9) : Void .ctor(IntPtr)
    d:\Docs\SharpDX-master_integration\Source\SharpDX.Direct3D11.Effects\Generated\Interfaces.cs(4300,17) : SharpDX.Direct3D11.EffectVectorVariable AsVector_()
    d:\Docs\SharpDX-master_integration\Source\SharpDX.Direct3D11.Effects\EffectVariable.cs(86,13) : SharpDX.Direct3D11.EffectVectorVariable AsVector()
```

They appeared each time when I am accessing shader variable.
This warning slow down app a lot.
Did you faced with that issues or know what could cause them?

**Comment by xoofx** [comment]
Maybe because you don't dispose them. I don't know if they changed the native behavior so now they are proper COM objects (don't remember if they were previously). So if they are COM objects, you need to carefully cache them and dispose them on purpose like any COM objects.

**Comment by QuantumDeveloper** [comment]
@xoofx earlier behavior was different -  you dont need to dispose them. Maybe they were not COM objects. With that changes is not very comfortable to create variables and dispose them each time you want to update it in shader. Is there a way to change current behavior to prevous? Previous was more developer friendly and easy to use.

**Comment by xoofx** [comment]
I haven't checked there code base, but don't think they have made such a big changes. Just set `Configuration.EnableTrackingReleaseOnFinalizer = false` and you should get rid-off these warnings. You can also try to use `EnableReleaseOnFinalizer = true` in your specific case, but I can't guarantee that there won't be any side effects.

**Comment by QuantumDeveloper** [comment]
@xoofx You was right. Disabbling object tracking and EnableTrackingReleaseOnFinalizer returned previous performance. Seems all working fine. Thanks for help. 
Still waiting for official version 3.0 :)
