### ISSUE TITLE
Support D2D, DWrite and WIC on WP 8.1

### ISSUE THREAD

**Issue by IndieViking** [sharpdx/SharpDX#334]
Support new APIs on Windows Phone 8.1
- Direct2D
- DirectWrite
- WIC
- HLSL shader compiler

Source:
http://blogs.msdn.com/b/shawnhar/archive/2014/04/03/windows-phone-8-1.aspx

**Comment by alexsorokoletov** [comment]
Guys, I wonder if you can help me with WIC and WP8.1
WicRenderTarget ctor crashes on devices, but not on emulators.
https://github.com/mono/CocosSharp/issues/260

Appreciate any help or advise.
