### ISSUE TITLE
sizeof being called on struct in unsafe context

### ISSUE THREAD

**Issue by augiem** [sharpdx/SharpDX#406]
The generated IL code for SharpDX.Interop.SizeOf calls sizeof() directly on managed structs outside an unsafe block which is not allowed. Instead it should use System.Runtime.Interop.SizeOf(). (Adding an unsafe block around sizeof instead will just cause another error "Cannot get the address of, get the size of, or declare a pointer to a managed type.")

I discovered this as I was trying to get SharpDX's DirectInput wrapper to work with the Unity3D game engine. I was always getting an exception from _ _ result _ _.CheckError() in SharpDX.DirectInput.CustomDevice.SetDataFormat. I found the cause of this was in SharpDX.DirectInput.CustomDevice.GetDataFormat, line:

_dataFormat = new DataFormat(((DataFormatAttribute) dataFormatAttributes[0]).Flags) {DataSize = Utilities.SizeOf<TRaw>()};

Utilities.SizeOf<TRaw>() was returning an incorrect value of 4 instead of 272 for the struct. When testing with a form application, it actually worked, but when tested within Unity it failed with an exception. By changing Utilities.SizeOf<T>() to call System.Runtime.InteropServices.Marshal.SizeOf(typeof(T)), the problem was solved. I also changed the SizeOf<T>(T[] array) overload to use Marshal.SizeOf.

Documentation:
http://msdn.microsoft.com/en-us/library/eahchzkf.aspx

"For all other types, including structs, the sizeof operator can be used only in unsafe code blocks. Although you can use the Marshal.SizeOf method, the value returned by this method is not always the same as the value returned by sizeof. Marshal.SizeOf returns the size after the type has been marshaled, whereas sizeof returns the size as it has been allocated by the common language runtime, including any padding."

**Comment by pottierg** [comment]
Hello, (and sorry for the bump)

we are working our way to integrate a non-standard joystick controller in Unity using SharpDX, without success so far when it comes to put the dll into Unity (everything works well in Visual Studio).

We tried to recompile SharpDX without success. Could any of you @augiem or @pbatard upload your SharpDX library (base and DirectInput) for anyone wanting to use it with Unity?

Thank you very much,
With best regards
