### ISSUE TITLE
Matrix3x3 with weird indexer

### ISSUE THREAD

**Issue by Debug-Err** [sharpdx/SharpDX#516]
In Matrix3x3, public float this[int index], either the indices are weird or the exception message is wrong. Here the getter of the operator:

    switch (index)
    {
        case 0:  return M11;
        case 1:  return M12;
        case 2:  return M13;
        // What's with index 3?
        case 4:  return M21;
        case 5:  return M22;
        case 6:  return M23;
        // What's with index 7?
        case 8:  return M31;
        case 9:  return M32;
        case 10: return M33;
        // "Indices run from 0 to 8", really?
        default: throw new ArgumentOutOfRangeException("index", "Indices for Matrix3x3 run from 0 to 8, inclusive.");
    }

I'm not sure if this has a logic together with Matrix4x4's, but it looks wrong to me.

**Comment by xoofx** [comment]
Thanks for the report, this is fixed.
