### ISSUE TITLE
Direct3D11 does not render in WPF when using Maximized Window mode

### ISSUE THREAD

**Issue by devdept2** [sharpdx/SharpDX#519]
Hi,

like the question on the link below, i'm experiencing the same problem.

http://stackoverflow.com/questions/18484295/why-does-direct-x-content-for-sharpdx-not-render-when-using-maximized-window-mod/27272585#27272585

I have e WPF control that creates a Direct3D11 device, 
I followed the Direct3D10 WPFHost sample of the SharpDX installation to implement my control.

If the WindowState is "Maximized" and the WindowStyle is different from "None", when my application starts up I don't see any rendered graphics. 
My control is alive, though, and as soon as I resize the Window the direct3D graphics becomes visible.

I'm using SharpDX 2.6.3.

The Direct3D10 WPFHost sample doesn't seem to have this issue.

Is this a known bug or am I doing something wrong?

Thanks

**Comment by tgjones** [comment]
In case it's of any help, I wrote [ClippingHwndHost](https://github.com/tgjones/gemini/blob/master/src/Gemini/Framework/Controls/ClippingHwndHost.cs) to solve the specific problem of using `HwndHost`ed content inside a WPF `ScrollViewer`.

Combined with [HwndWrapper](https://github.com/tgjones/gemini/blob/master/src/Gemini/Framework/Controls/HwndWrapper.cs), which converts mouse input into .NET-friendly events, it's not too terrible a solution. But as @xoofx said, there are still a number of other issues to be considered (airspace, etc.).
