### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by xanather** [sharpdx/SharpDX#520]
A large part of .NET has been opened source (called CoreCLR/.NET Core) and I was wondering if SharpDX is willing to support such a scenario?

Problems:
1. .NET Core 5 doesn't seem like it will be able to reference .NET Framework targeted libraries.
2. Libraries like System.Windows.Forms will not be supported with .NET Core. Meaning on Windows, forms will need to be interacted with natively - something I think SharpDX shouldn't really need to worry about (RenderForm/RenderLoop wont be usable though).

Pro's and cons of using .NET Core is here: http://blogs.msdn.com/b/dotnet/archive/2014/12/04/introducing-net-core.aspx

A good reason to support it would be to allow custom game engines to create a single cross platform library which optionally uses SharpDX (DirectX) or OpenGL on windows, and just OpenGL on other platforms all while targeting .NET Core.

Obviously .NET Core is still some time from release, but any ideas surrounding this?

**Comment by xoofx** [comment]
> OpenTK manages to provide cross platform .dll's by using runtime determinations.

OpenTK doesn't have the requirement (and can't) to run on WindowsRT/WP81, where Runtime determination is not possible due to AppCertification. This is a reason why it is so laborious to provide PCL libraries for SharpDX, because we need to completely remove all platform dependent code from assemblies, even if they are not used.

**Comment by xoofx** [comment]
Latest version 3.0.0-alpha01 is supporting .NET45 and PCL for Windows 8. The PCL version should be compatible with the .NET core version.

**Comment by Alan-FGR** [comment]
Hey guys, sorry for resurrecting this. I'm trying to run the examples in Net Core and they require WinForms, so I'm wondering what would the the recommended alternative for windowing, can I create a window in SDL and pass the context pointer to SharpDX?

**Comment by RayKoopa** [comment]
Especially now with upcoming Windows Forms support in .NET Core 3, it would be interesting to get the Desktop package to provide support for .NET Core 3.
But one thing at a time. Let things go final first :)

**Comment by ryancheung** [comment]
SharpDX shall get the Desktop pacage to target .NET Core 3.0
