### ISSUE TITLE
Compiled tkfxo file with tkfxc.exe is not loaded.

### ISSUE THREAD

**Issue by jucysoft** [sharpdx/SharpDX#524]
After downloading SharpDX-SDK-2.6.3, I compiled Inverted.fx with DIrectX11-net40\tkfxc.exe.
Inverted.fx file is used at following sample project.
http://developer.nokia.com/community/wiki/Creating_a_Lens_application_that_uses_HLSL_effects_for_filters

I changed LIB/ARM/*.* with DirectX11_1-WP8-ARM/*.*.
and changed Content/Inverted.tkfxo with new built Inverted.tkfxo.

It cause run time error. "could not find asset." at following code:
     inversionEffect = Content.Load<Effect>("Inverted.tkfxo");

**Comment by xoofx** [comment]
The way to use it is to compile with the msbuild action ToolkitFxc as it is done for all toolkit samples. tkfxc is generating a filename with an extension while the Content manager is not using it
