### ISSUE TITLE
Sharpdx bc6h cubemap loading issue

### ISSUE THREAD

**Issue by shinkamui** [sharpdx/SharpDX#530]
Hi, I'm using SharpDX.Direct3D11.Resource.FromFile<Texture2D> to load a dds cubemap. The code works well with bc1 cube but always go no response with bc6h format.
 
The bc6h file is generated from a r16g16b16a16_float cube by texconv, which is a dds compress tool from DirectXTex toolset. The generated file is proven correct by ddsview (another directxtex tool) and visual studio, so I wonder is this a bug? 

Source cubemap and generated bc6 cube files are attached in this thread:
http://www.gamedev.net/topic/664666-sharpdx-bc6h-cubemap-loading-issue/

ps: version 2.6.3

**Comment by xoofx** [comment]
No known bug, as it is almost a direct call to the underlying C++ API, please follow [this](http://sharpdx.org/forum/4-general/1774-how-to-debug-a-sharpdxexception)
