### ISSUE TITLE
ShaderBytecode.Compile AccessViolationException

### ISSUE THREAD

**Issue by teddemunnik** [sharpdx/SharpDX#531]
I have downloaded SharpDX.D3DCompile using NuGet and made sure I have statisfied all prerequisites, however when I call ShaderBytecode.Compile, or ShaderBytecode.CompileFromFile it is giving me an AccessViolationException. 

My computer is running Windows 8.1 Pro, but I also tried installing DirectX Redistributable 2010.

````
CompilationResult result = ShaderBytecode.CompileFromFile(fileName, "ps_4_0_level_9_1");
````
Changing the shader profile does not fix the issue.

**Comment by xoofx** [comment]
There is no known issue with this method. Maybe check the file (an UTF8 encoding messing the compiler?) or check to run in process x86...

**Comment by ArtiomCiumac** [comment]
This issue does reproduce when using DX11 assemblies, however when I use the DX11.2 assemblies - I get the following error: `D3DCompile: pEntrypoint pointer is invalid`. Therefore, the `AccessViolationException` is specific to older d3d compiler implementation from `d3dcompiler_43.dll`.

It works fine, however, if I provide the entry point name:
```
CompilationResult result = ShaderBytecode.CompileFromFile(fileName, "main", "ps_4_0_level_9_1");
```

AFAIK, the entry point can be null only for 'effect' profiles - that begin with `fx_...` - for anything else the entry point name is mandatory.

We could add a check in SharpDX to provide a more meaningful error message if entry point is not provided, however I am not sure how future-proof it is. Something like this can do the trick if inserted after `ShaderBytecode.cs, line 654`:

```
if (string.IsNullOrWhiteSpace(profile))
    throw new ArgumentNullException("profile");

if (!profile.ToUpperInvariant().StartsWith("FX_") && string.IsNullOrWhiteSpace(entryPoint))
    throw new ArgumentNullException("entryPoint");
```

What do you think?

**Comment by teddemunnik** [comment]
Excuse me for responding so late, I've not been at work since reporting this. It problably has to do with not giving an entry point to the method, as @ArtiomCiumac suggested. If not running in process x86, as suggested by @xoofx, causes any issues that may be part of the problem as well. Reporting a better error message would have been really helpful indeed! 

I'll report back when I verify whether any of these suggestions fixes my application.

**Comment by xoofx** [comment]
This should be fixed by the commit above.
