### ISSUE TITLE
Custom XAPO keeps receiving buffers after disposing sourcevoices

### ISSUE THREAD

**Issue by AudioW** [sharpdx/SharpDX#536]
Hi

I have a situation where I assign a custom XAPO to a mastering voice using SharpDX 2.6.3.

When I assign and start a sourcevoice the XAPO works fine. When I stop and dispose the sourcevoice, there are still buffers going in to the XAPO (Process() is still being called) even though there are no active sourcevoices.

Thanks

Wouter

**Comment by xoofx** [comment]
I don't have time to look into the details of this API, so if you are not able to reproduce this with C++ code, I will reopen this issue, otherwise it is a usage issue.
