### ISSUE TITLE
Exception SharpDX.Xaudio2 on windows 8

### ISSUE THREAD

**Issue by arsenium** [sharpdx/SharpDX#538]
Hi! Current status:
Windows 8 + Visual Studio 2012 express for Windows 8.
SharpDX 2.6.3.
I`m install SharpDX.XAudio2 from nuget: Install-Package SharpDX.XAudio2
Create simple Windows 8 Metro app and simple class SoundEffect:

 public class SoundEffect
    {
        readonly XAudio2 _xaudio;
        readonly WaveFormat _waveFormat;
        readonly AudioBuffer _buffer;
        readonly SoundStream _soundstream;
        SourceVoice sourceVoice;

        public SoundEffect(string soundFxPath)
        {
            _xaudio = new XAudio2();
            var masteringsound = new MasteringVoice(_xaudio);

            var nativefilestream = new NativeFileStream(
            soundFxPath,
            NativeFileMode.Open,
            NativeFileAccess.Read,
            NativeFileShare.Read);

            _soundstream = new SoundStream(nativefilestream);
            _waveFormat = _soundstream.Format;
            _buffer = new AudioBuffer
            {
                Stream = _soundstream.ToDataStream(),
                AudioBytes = (int)_soundstream.Length,
                Flags = BufferFlags.EndOfStream
            };

            sourceVoice = new SourceVoice(_xaudio, _waveFormat, true);
            sourceVoice.SubmitSourceBuffer(_buffer, _soundstream.DecodedPacketsInfo);
        }

        public void Play()
        {
            
            sourceVoice.Start();
            
        }
        public void Stop()
        {
            sourceVoice.Stop();
        }
    }

My problem:
http://i.imgur.com/XPr0UrW.png
The primary reference "SharpDX" could not be resolved because it has an indirect dependency on the .NET Framework assembly "System.Runtime, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which has a higher version "4.0.10.0" than the version "4.0.0.0" in the current target framework.

My TargetPlatform .NETCore,Version=v4.5.
Why can occur such error?

**Comment by xanather** [comment]
Looks like the project is trying to reference .NET Framework assemblies, something that should not happen if you're targeting .NET Core assemblies. I have yet to see how Metro/Universal app workflow works yet but this is what I see on the surface. Maybe download the latest version from the official SharpDX website instead and reference the Metro assemblies manually?

**Comment by arsenium** [comment]
I installed manually SharpDX 2.6.3, and the error is still there. I was able to install only the version SharpDX 2.5.0.

**Comment by temkich** [comment]
I have the same problem!
What is the latest version sharpdx exists for Windows 8 only, not for Windows 8.1 and above.
I was able to install only 2.5. How to work with 2.6.3 on windows 8?

**Comment by xanather** [comment]
I use the nuget packages, they are 2.6.3

**Comment by temkich** [comment]
You can create an empty Windows Store app project with installed SharpDX 2.6.3? And send me? 
Just an empty project with SharpDX 2.6.3 and add this class in project for example and build:

public class SoundEffect
    {
        readonly XAudio2 _xaudio;
        readonly WaveFormat _waveFormat;
        readonly AudioBuffer _buffer;
        readonly SoundStream _soundstream;
        SourceVoice sourceVoice;
        VoiceState state;
        MasteringVoice masteringsound;
        public SoundEffect()
        {
            _xaudio = new XAudio2();
        }
    }

. I want to understand why I do not work = (

**Comment by pjmagee** [comment]
I had issues using the Non-signed libraries. Try replacing with the signed dll's

**Comment by xoofx** [comment]
Try to use 3.0.0-alpha01 as we are now only providing .NET45 support it should better work.

**Comment by temkich** [comment]
windows 8 not supported.
http://i.imgur.com/Ef1vgsf.png

**Comment by xoofx** [comment]
@temkich: hm, I think It is compatible with Windows 8.1 not Windows 8

**Comment by xanather** [comment]
AMD doesn't even support windows 8 with their GPU drivers anymore last I heard, should really upgrade to windows 8.1 its free.
