### ISSUE TITLE
Insert Audio-effects like equalizer in media engine ex?

### ISSUE THREAD

**Issue by codemaster7832** [sharpdx/SharpDX#539]
I studied media-player sample and others too. I can understand how video-effect can be added. However I tried to add reverb or equalizer effect like soundsource. But I dont understand how that can be done with mediaengineex.InsertAudioEffect.

**Comment by xoofx** [comment]
Unless there is a bug, I'm closing this issue as it looks like more a usage issue (Sorry, we don't have enough time to provide support for usage)
