### ISSUE TITLE
WIC.Bitmap.CopyPixels output length.

### ISSUE THREAD

**Issue by grokys** [sharpdx/SharpDX#545]
In the documentation for WIC.Bitmap.CopyPixels it says:

    The size of the array must be sizeof(pixel) * rectangle.Width * rectangle.Height

However the code uses:

    if ((rectangle.Width * rectangle.Height) != output.Length)
                throw new ArgumentException("output.Length must be equal to Width * Height");

This means it is impossible to pass an array of the correct length to the methods. If you pass the accepted length, you get a System.AccessViolationException.

https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX.Direct2D1/WIC/BitmapSource.cs#L115
https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX.Direct2D1/WIC/BitmapSource.cs#L137

**Comment by xoofx** [comment]
Indeed the documentation is incorrect. T must be of the type of the pixel. But It should work as long as T is of the correct type. If you pass a byte array and the pixel is 32bits, it won't work.

**Comment by grokys** [comment]
Ok, but if T must be of the type of the pixel then that makes it difficult to write a generic version that works on an image with an arbitrary number of bits per pixel. What is the recommended way to do such a thing?

**Comment by xoofx** [comment]
There are other overloads like taking a byte[] array or a native pointer. 

I'm closing the issue as it looks ok to me.
