### ISSUE TITLE
SharpDX Exception on samples | BindFlags.DepthStencil

### ISSUE THREAD

**Issue by ghost** [sharpdx/SharpDX#546]
I am just leaving this here, i am fairly new to SharpDX.

When creating a Texture2D object and setting BindFlags to BindFlags.DepthStencil it throws a exception.

I seem to get this error

An unhandled exception of type 'SharpDX.SharpDXException' occurred in SharpDX.dll

Additional information: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

This error was found from the sharpdx samples but most likely isnt the samples causing it but something internally

**Comment by xoofx** [comment]
Please follow http://sharpdx.org/forum/4-general/1774-how-to-debug-a-sharpdxexception in order to find what's wrong. Afaik, all samples are working.
