### ISSUE TITLE
SetIndexBuffer causes AccessViolationException on intel GPU (Surface Pro 3)

### ISSUE THREAD

**Issue by TheWhiteAmbit** [sharpdx/SharpDX#547]
Whenever I tried to call SharpDX.Direct3D11.InputAssemblerStage.SetIndexBuffer (since SharpDX 2.3.1 until latest NuGet 2.6.x stable [device.ImmediateContext.InputAssembler.SetIndexBuffer(...)]) I get an System.AccessViolationException. Thought it might only be case with 32Bit Indices, but 16bit Indices also crash. Drawing nonindexed works as well es drawing Indexed with the same code on nVidia GPUs. Enabling Debug of Native-Code and Debug-Device creation does not give any more informations since It seems to create Memory-Access-Violation (not an Direct3D-Exception).

Sample Exception Output:

System.AccessViolationException was unhandled by user code
  HResult=-2147467261
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=SharpDX.Direct3D11
  StackTrace:
       at SharpDX.Direct3D11.InputAssemblerStage.SetIndexBuffer(Buffer indexBufferRef, Format format, Int32 offset)
       at SharpDX.WPF.Direct3DContent..ctor() in c:\Users\thewh_000\Source\Repos\XL1\SharpDX.WPF\Direct3DContent.cs:line 129
  InnerException:

**Comment by TheWhiteAmbit** [comment]
Sounds a little bit like this Issue 531:
https://github.com/sharpdx/SharpDX/issues/531

**Comment by xoofx** [comment]
This is not related. I cannot reproduce it as I don't have an intel GPU. Intel GPU drivers are a bit less "robust" than others. For example, using a feature level under 10.0 is not working well on their driver.

**Comment by smack0007** [comment]
I know this issue is closed but I had the same problem and I managed to fix it. Using the trick described here:

http://sharpdx.org/forum/5-api-usage/241-d3d11-indexbuffer?start=10#1417

I found out that my IndexBuffer was actually being created with BindFlags.VertexBuffer. Correcting this mistake fixed the problem for me.
