### ISSUE TITLE
RegisterComponentMaskFlags has no enum value for mask

### ISSUE THREAD

**Issue by silvesthu** [sharpdx/SharpDX#553]
Enum RegisterComponentMaskFlags has no definition about mask part corresponding with __Mask__ field is not included.

None, ComponentX, ComponentY, ComponentZ, ComponentW, All, which indicates the declared type such as float, float2, etc.

I figured out Mask are on the 8~15bit of the RegisterComponentMaskFlags value.
But it will be nice that they are in the definition of enum originally.

Besides, the original type of Mask if BYTE, and also for ReadWriteMask.
So I doubt that UsageMask in RegisterComponentMaskFlags even eat up the space of 
ReadWriteMask which cause it always gives None.

ref: D3D11_SIGNATURE_PARAMETER_DESC https://msdn.microsoft.com/en-us/library/windows/desktop/ff476215.aspx

**Comment by kburgoyne** [comment]
The original Mask may be being duplicated in both 0..7 and 8..15.  Found this problem with ShaderParameterDescription.UsageMask.  Bandaid is to make sure to mask (&) against the enums, or make sure to mask for only 0..7 before comparing.  Any approach that strips off bits 8..N might work.  Seems like it should work for ShaderParameterDescription.UsageMask given what I'm seeing.

**Comment by xoofx** [comment]
Sorry, I don't understand this issue. Can you reformulate it? What is exactly the problem?

**Comment by silvesthu** [comment]
@xoofx My apologize.
My problem was that I can't get correct value for D3D11_SIGNATURE_PARAMETER_DESC::Mask.
But now since you fixed the type of RegisterComponentMaskFlags, I suppose the issue has already gone. Thank you by the way.
