### ISSUE TITLE
DrawGlyphRun uses wrong native color struct

### ISSUE THREAD

**Issue by gerhard-j** [sharpdx/SharpDX#558]
I'm not sure, but I think SharpDX.DirectWrite.BitmapRenderTarget.DrawGlyphRun uses wrong a wrong native color struct. In MSDN it's a COLORREF (32bit RGB). In SlimDX it's a Color4 (4 floats). My sample application crashes in 32 bit mode exactly in this API with an access violation. In 64 bit mode it succeedes, but produces some kind of random coloring. 
I think the color paramater should have the type System.Drawing.Color or a simmilar type.
Thanx, Gerhard

**Comment by xoofx** [comment]
Thanks, indeed the COLOREF is an int. This should be fixed by the commit above.
