### ISSUE TITLE
Newest nuget does not run Install.ps1 => packages don't add anything to project

### ISSUE THREAD

**Issue by davepermen** [sharpdx/SharpDX#566]
The newest nuget updates for visual studio 2015 removed Install.ps1 / Uninstall.ps1 support. The result is, adding SharpDX to a project leads to no references added.

I guess the packages should put the dll's properly into the libs (and into different .net targets for the different platforms).

**Comment by xoofx** [comment]
The way SharpDX binaries are generated with the different versions ((DX11, DX12) * OS (Desktop, Windows Store...etc.) doesn't work well with nuget. If the `install.ps1` is not working with VS2015 and as it has been causing some trouble in the past... I'm pondering to completely abandon support for nuget...  There will be soon a new release and I will check by then hot to improve the distribution.

**Comment by xoofx** [comment]
Starting with 3.0.0 (alpha01), we have abandoned some old DirectX versions, OS platforms and .NET framework, so we are now able to target nuget in a more standard way.
