### ISSUE TITLE
NullReferenceException at  SharpDX.Toolkit.GameWindowDesktopWpf.EndScreenDeviceChange

### ISSUE THREAD

**Issue by elangovanr** [sharpdx/SharpDX#568]
I'm getting NullReferenceException when I run application that is using DirectX. The application works fine if I run from visual studio, but if I run exe from debug folder, this exception occurs. Following is the stack trace.

> System.NullReferenceException: Object reference not set to an instance
> of an object.    at
> SharpDX.Toolkit.GameWindowDesktopWpf.EndScreenDeviceChange(Int32
> clientWidth, Int32 clientHeight) in
> g:\TFS\NextGen\OpenSource\SharpDX-master\Source\Toolkit\SharpDX.Toolkit.Game\Desktop\GameWindowDesktopWpf.cs:line
> 122    at
> SharpDX.Toolkit.GraphicsDeviceManager.ChangeOrCreateDevice(Boolean
> forceCreate) in
> g:\TFS\NextGen\OpenSource\SharpDX-master\Source\Toolkit\SharpDX.Toolkit.Game\GraphicsDeviceManager.cs:line
> 826    at SharpDX.Toolkit.Game.InitializeBeforeRun() in
> g:\TFS\NextGen\OpenSource\SharpDX-master\Source\Toolkit\SharpDX.Toolkit.Game\Game.cs:line
> 301    at SharpDX.Toolkit.GameWindowDesktopWepf.Run() in
> g:\TFS\NextGen\OpenSource\SharpDX-master\Source\Toolkit\SharpDX.Toolkit.Game\Desktop\GameWindowDesktopWpf.cs:line
> 206    at SharpDX.Toolkit.Game.Run(GameContext gameContext) in
> g:\TFS\NextGen\OpenSource\SharpDX-master\Source\Toolkit\SharpDX.Toolkit.Game\Game.cs:line
> 371    at ImageDxViewer.DxViewer3D..ctor(Object
> controllerSynchronizer) in
> d:\Source\Framework\ImageDxViewer\DxViewer3D.xaml.cs:line 52 __(This line calling Game.Run  method)__

This used to work couple of weeks back and it suddenly stopped working. I'm using windows 8.1 Enterprise edition. Following are the major changes I have done recently in my system. Did Windows Update and Installed Latest Visual Studio 2015 CTP. I have tried to uninstall visual studio and other windows updates, still I have the same problem

**Comment by xoofx** [comment]
Sorry, the Toolkit is no longer supported.
