### ISSUE TITLE
Matrix class uses deprecated Marshal.SizeOf

### ISSUE THREAD

**Issue by Gavin-Williams** [sharpdx/SharpDX#572]
The following needs to be updated
public static readonly int SizeInBytes = Marshal.SizeOf(typeof(Matrix));
to:
public static readonly int SizeInBytes = Marshal.SizeOf< Matrix >();

**Comment by xoofx** [comment]
This is fixed by commit 67d356e746198b69cb3f630ce9e2c270bf99ffb2
