### ISSUE TITLE
Wrong parameters in multiple Direct3D9.BaseMesh methods

### ISSUE THREAD

**Issue by CodeHazard** [sharpdx/SharpDX#573]
Parameter declarationRef in Direct3D9.BaseMesh.CloneMesh should be an array, but currently takes only a single VertexElement. Same goes for the UpdateSemantics and GetDeclaration methods in the same class.

**Comment by xoofx** [comment]
All the legacy X model Direct3D9 loader/animation/bones has never been supported in SharpDX and we are no longer making changes to the Direct3D9 layer.

**Comment by CodeHazard** [comment]
Ah okay, thanks for the reply. Marking known-to-be-broken methods like these as deprecated could be helpful to avoid future confusion about the matter.
