### ISSUE TITLE
XAudio2 and disposing

### ISSUE THREAD

**Issue by xanather** [sharpdx/SharpDX#574]
I am unsure of how I should handle disposing of objects in XAudio2.

I know many XAudio2 objects have methods like StopEngine() and DestroyVoice(), but are these functions automatically called when calling Dispose on such an object?

In native code I know you would, but what about in SharpDX's case and C# memory management?

The XAudio2 has samples that use StopEngine/DestroyVoice and other samples that don't.

**Comment by xoofx** [comment]
Afair, you need to handle them explicitly. Samples are not always accurate but often just to demonstrate a basic access to the API.
