### ISSUE TITLE
Internal exceptions being thrown

### ISSUE THREAD

**Issue by xanather** [sharpdx/SharpDX#575]
Internal general System.Exceptions are being thrown.

The spam of exceptions are only thrown when Configuration.EnableObjectTracking = true; (I had this enabled always for debug building). For now I have disabled the use of it in my application.

When resizing a Win32 window and causing the Back buffer to resize it lags the application (even XAudio2 has trouble playing back - like the debugger is locking up the process or something). Note that in my application though I do resize the back buffer on every WM_SIZE event. Usually its fine and smooth, but with Configuration.EnableObjectTracking as true it lags badly like its having trouble resizing the SwapChain and buffers.

Strange thing is that it does not lag if the debugger is not attached and Configuration.EnableObjectTracking is true.

I am using Direct3D11.

**Comment by xoofx** [comment]
could you precise which version of SharpDX?

**Comment by xanather** [comment]
Version 3.0.0.0 alpha01

**Comment by xoofx** [comment]
yes, it might be broken in this version.

**Comment by xoofx** [comment]
As SharpDX is now using PCL, there is no other ways than throwing an exception to get a stacktrace. I have added a custom exception `GetStackTraceException` that you can ignore in VS. Afaik, this is the only possible fix for now.
