### ISSUE TITLE
XAudio 2.7 support

### ISSUE THREAD

**Issue by xanather** [sharpdx/SharpDX#576]
I just noticed the alpha no long has XAudio2.7 support. I am unable to make much use of the new 3.0.0.0 alpha versions unless XAudio2.7 support is brought back. XAudio2.8 does not work on Win7 and that OS still has over 50% of the market share. I'm sure many others feel the same.

Thanks,
Xanather

**Comment by xoofx** [comment]
the latest version on git is now including support for both 2.7 and 2.8 from the same binaries (still an alpha). I will release an update alpha02 in the coming days.
