### ISSUE TITLE
[Direct3D12] ShaderResourceViewDescription padding 

### ISSUE THREAD

**Issue by mrvux** [sharpdx/SharpDX#578]
Hello, I noticed while creating a ShaderResourceView in Direct3D12 that structure padding is invalid.

Simply in generated code:
    [FieldOffset(12)]
    public SharpDX.Direct3D12.ShaderResourceViewDescription.Texture2DResource Texture2D;

Field offset should be 16 to work properly.
Since I'm not sure where this part built in the code generation, I'll issue it here (should be a pretty easy fix)

Many thanks
Julien

**Comment by xoofx** [comment]
Yes, as I mentioned a bit in the 3.0 post, there are many things not correctly marshaling in D3D12 that require custom marshaling.

**Comment by xoofx** [comment]
This is fixed by previous commit.
