### ISSUE TITLE
Direct3D11 performances

### ISSUE THREAD

**Issue by devdept2** [sharpdx/SharpDX#579]
Hi,

I see a degradation of performances in my application when the window becomes larger.
I'm using SharpDX 2.6.3 and I create a Direct3D11 device.
This happens with feature level 11 but not with feature level 9_3.
I thought it could have been due to too complicated shaders, but I tried returning a simple fixed color without computing any illumination and the same issue happens.
Is this something to be expected or could there be some problems in my code?

**Comment by xoofx** [comment]
Most likely in your code or setup (drivers....etc.). Afaik, no known issues.

**Comment by devdept2** [comment]
mmm... that's strange.
I tried these 2 cases:

Common code:
                 // Create Device and SwapChain
                factory = new Factory();
                Adapter ad = factory.GetAdapter(0);

Case 1)  Forces a Level_9_3 feature level
                Device = new Device(ad, DeviceCreationFlags.BgraSupport, FeatureLevel.Level_9_3);

Case 2)  Gets a Level_11 feaure level
                Device = new Device(ad, DeviceCreationFlags.BgraSupport);


Everything else is the same, so they are both using the same code except for the Device initialization and in the Case 2) i see a big drop in framerate between small and maximized window (of about 10 times) on a Intel HD 4000 machine.

**Comment by devdept2** [comment]
Hi,

how can you explain that simply creating the device with featureLevel 11_0  gives such a different framerate on cards like the Intel HD 4000 between a small and a maximized window, whilst the 9_3 featureLevel device goes pretty much at the same framerate?

**Comment by xoofx** [comment]
@devdept2 I can't explain driver differences and discrepencies between feature levels. On the opposite, I remember that I have had many issues with 9.1/9.3 feature levels on Intel. But that's unfortunately a total blackbox.

Try to determine the minimum sample that produce such behavior and tweak an existing C++ sample to check if it happens there too, or not.  I'm closing this issue, unless you are able to prove that it is coming from SharpDX itself.
