### ISSUE TITLE
Is .NET4.5 still supported in SharpDX for WinRT?

### ISSUE THREAD

**Issue by unarist** [sharpdx/SharpDX#580]
I installed "SharpDX Toolkit for VisualStudio" into VS2012 and create project "Toolkit Game" for "Windows Store" platform.

Project creation succeeds, but build failed.

> warning MSB3274: The primary reference "SharpDX" could not be resolved because it was built against the ".NETCore,Version=v4.5.1" framework. This is a higher version than the currently targeted framework ".NETCore,Version=v4.5".
> warning MSB3275: The primary reference "SharpDX.Toolkit.Game" could not be resolved because it has an indirect dependency on the assembly "SharpDX, Version=2.6.3.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1" which was built against the ".NETCore,Version=v4.5.1" framework. This is a higher version than the currently targeted framework ".NETCore,Version=v4.5".
> ...

.NET4.5 (and VS2012) is no longer supported?

**Comment by xoofx** [comment]
SharpDX2.6.3 WinStore is relying on Win8.1 which is requiring using .NET4.5.1
