### ISSUE TITLE
how to create VideoDisplayControl?

### ISSUE THREAD

**Issue by newdreamworlds** [sharpdx/SharpDX#581]
although there are few samples of playing video by sharpdx, I have managed to play video by MediaSession of sharpdx. however, there is srill a headache, which is how to creare VideoDisplayControl. I can not figure it out by myself and can not find any samples on the internet. I am not going to use MediaEngineEx, because it does not support  win7.
is there anyone who can help me? thanks.

**Comment by xoofx** [comment]
Sorry, I'm closing this issue as this is a usage question and there is nobody here to help on this specific one.
