### ISSUE TITLE
Namespace not found on Windows 10 UAP project

### ISSUE THREAD

**Issue by LoveMetal-StrangeGames** [sharpdx/SharpDX#583]
I have installed the following packages through NuGet:
SharpDX.2.6.3
SharpDX.Direct3D11.2.6.3
SharpDX.DXGI.2.6.3
SharpDX.Toolkit.2.6.3
SharpDX.Toolkit.Graphics.2.6.3
SharpDX.Toolkit.Game.2.6.3

None of these show up in the Project References panel, and the only available namespaces are SharpDX.Direct2D1, SharpDX.Direct2D1.Effects, SharpDX.DirectWrite and SharpDX.WIC.

I'm using Visual Studio 2015 CTP, everything works fine and references & namespaces are available on a Windows 8.1/Windows Phone 8.1 project.

Note that a Windows phone 8.1 project using SharpDX with the previous packages works fine on a Windows Phone 10 emulator.

**Comment by xoofx** [comment]
UAP is not supported by 2.6.3. Next 3.0 version should support it.

**Comment by Gavin-Williams** [comment]
I have sharpdx running in a UAP solution on Windows 10. But I don't use Nuget, so my references were added manually.
