### ISSUE TITLE
D2D LayerParameters.OpacityBrush and GeometricMask should be optional.

### ISSUE THREAD

**Issue by grokys** [sharpdx/SharpDX#584]
According to MSDN,  D2D1_LAYER_PARAMETERS.opacityBrush and geometricMask should be optional:

https://msdn.microsoft.com/en-us/library/windows/desktop/dd756654(v=vs.85).aspx
(under "Creating Layers)

However in LayerParameters at https://github.com/sharpdx/SharpDX/blob/d8fb59d1edcadb77c493522fdf98509513fe633d/Source/SharpDX.Direct2D1/LayerParameters.cs, SharpDX attempts to take the NativePointer of the value without a null check.

**Comment by xoofx** [comment]
Fixed by previous commit
