### ISSUE TITLE
[SharpDX 2.6.3, D2D1, Win10] Query of D2D registered effects fails

### ISSUE THREAD

**Issue by morpheusxx** [sharpdx/SharpDX#585]
While getting registered D2D effects works in Win 7 + 8(.1), it fails inside Win 10 Insider Preview (10074).

Exception already happens inside getter:

[2015-05-02 19:05:51,790] [1678   ] [DX Render] [WARN ] - GraphicsDevice: DirectX Exception
SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: Falscher Parameter.

   bei SharpDX.Result.CheckError()
   bei SharpDX.Direct2D1.Factory1.GetRegisteredEffects(Guid[] effects, Int32 effectsCount, Int32& effectsReturned, Int32& effectsRegistered)
   bei SharpDX.Direct2D1.Factory1.get_RegisteredEffects()
   bei MediaPortal.UI.SkinEngine.ContentManagement.AssetCore.EffectAssetCore`1.Allocate()
   bei MediaPortal.UI.SkinEngine.ContentManagement.EffectAsset`1.Allocate()

While this could be an issue of "unfinished" Windows 10, it would be good to be checked!

**Comment by xoofx** [comment]
Sorry for the inconvenience, I forgot to mention in the blog post about 3.0 version that D2D effects are not yet ported to the new model. This is a known issue.

**Comment by morpheusxx** [comment]
Sorry, I was not specific enough. The issue is with SharpDX 2.6.3. already. So I think this is a Win10 related bug.

**Comment by morpheusxx** [comment]
As followup:

Good news for Windows 10: I've updated to latest testbuilld 10158 and the Direct2D build is finally working again! 

So the issue has been fixed in Windows 10 in the meantime. SharpDX was working correctly.
