### ISSUE TITLE
Direct2D BorderTransform null pointer exception

### ISSUE THREAD

**Issue by gerhard-j** [sharpdx/SharpDX#586]
[SharpDX.Direct2D V3.0.0-alpha01]

The constructor of BorderTransform 
public BorderTransform(EffectContext context, ExtendMode extendModeX, ExtendMode extendModeY)

internally calls
   context.CreateBorderTransform(extendModeX, this.ExtendModeX, this);
and creates a null pointer exception.

I think this should be 
   context.CreateBorderTransform(extendModeX, extendModeY, this);

regards, Gerhard

**Comment by xoofx** [comment]
Thanks for finding this. This should be fixed by commit e6bb4e3b5a8cfe27985a4a7f5346959d8076754e
