### ISSUE TITLE
Is there a missing SwapChain1.Present1  method?

### ISSUE THREAD

**Issue by Gavin-Williams** [sharpdx/SharpDX#588]
The swapchain.present method says in intellisense ..

"Starting with Direct3D 11.1, we recommend not to use Present anymore to present a rendered image. Instead use SharpDX.DXGI.SwapChain1.Present1(System.Int32, SharpDX.DXGI.PresentFlags, System.IntPtr).."

But there is no Present1 method exposed.

**Comment by xoofx** [comment]
The method is available as `public unsafe void Present(int syncInterval, PresentFlags presentFlags, PresentParameters presentParameters)`
