### ISSUE TITLE
DXGI_ERROR_UNSUPPORTED on Windows 7

### ISSUE THREAD

**Issue by gagagu** [sharpdx/SharpDX#589]
Hi,
i'm using the new SharpDX alpha 3.0.0 Alpha 01 for my vr streaming Project (https://github.com/gagagu/VR-Streamer-Windows-Server). Since the 3.0.0 Alpha Version my Programm is not working on Windows 7 anymore. I get the error DXGI_ERROR_UNSUPPORTED by using the screen capture method.
I think the reason ist the version of DirectX (max. DirectX version on Windows 7 is 11.1). But what i have to do to make it working with the 3.0.0 alpha?

**Comment by xoofx** [comment]
It should work as interfaces should be backward compatible, unless they have messed-up something with header files between Windows 10041 SDK (which 3.0.0-alpha01 is currently based on) and Windows 8.1 SDK. I will have to make a diff of the assemblies to find out why.

**Comment by gagagu** [comment]
Hi, thanks for reply. 
I found out that the following method will throw the error:
               duplicatedOutput = output1.DuplicateOutput(device);

Thf forward

**Comment by gagagu** [comment]
Any news for me how to get ist working on Windows 7?
If you like to take a look into my code its also a github project https://github.com/gagagu/VR-Streamer-Windows-Server/blob/master/Gagagu%20VR%20Streamer%20Server/DirectX.cs

Thanks forward

**Comment by xoofx** [comment]
Sorry, my spare time is currently quite limited for SharpDX support, so you have to dig yourself into the problem. Try to compare the assemblies 2.6.3 and 3.0.0 on these specific methods (decompiled methods) and look why this is different. The screen capture is perfectly working on Windows 8 here, so if DXGI is returning a DXGI_ERROR_UNSUPPORTED on Win7, I'm quite dubitative that It worked before with 2.6.3...

**Comment by xoofx** [comment]
Also note as stated in the documentation [DuplicateOutput](https://msdn.microsoft.com/en-us/library/windows/desktop/hh404600%28v=vs.85%29.aspx) require to have installed the Platform Update for Windows 7. So it should work, unless this platform update is not installed ([download here](https://www.microsoft.com/en-us/download/details.aspx?id=36805))

**Comment by gagagu** [comment]
Hi,
the platform update is already installed.
