### ISSUE TITLE
How to get the proper SharpDX dlls

### ISSUE THREAD

**Issue by shiro900** [sharpdx/SharpDX#590]
I am trying to make this [ScreenCapture example](https://github.com/sharpdx/SharpDX-Samples/tree/master/Desktop/Direct3D11.1/ScreenCapture) to work from SharpDX's github. It gives me errors about `DuplicateOutput` method, `Output1` class and `OutputDuplicateFrameInformation` struct, because all 3 don't exist under SharpDX.DXGI namespace.

From your documentation [DuplicateOutput](http://sharpdx.org/documentation/api/m-sharpdx-dxgi-output1-duplicateoutput) method, [Output1](http://sharpdx.org/documentation/api/t-sharpdx-dxgi-output1) class and [OutputDuplicateFrameInformation](http://sharpdx.org/documentation/api/t-sharpdx-dxgi-outputduplicateframeinformation) struct, all exist in `SharpDX.DXGI.dll 2.4.2.0`.

I got the current .dlls I am using (SharpDX.dll, SharpDX.DXGI.dll and SharpDX.Direct3D11.dll) by installing [SharpDX-SDK-2.6.3.exe](http://sharpdx.org/upload/SharpDX-SDK-2.6.3.exe) and then opening it (it prompts you to extract its contents) and I got those 3 dlls from the `\Bin\DirectX11-net40` folder. The version of those dlls is the latest **2.6.3** instead of **2.4.2.0**

How am I supposed to get `SharpDX.DXGI.dll 2.4.2.0` ? It is nowhere to be found on your website. Or how am I supposed to make that [ScreenCapture example](https://github.com/sharpdx/SharpDX-Samples/tree/master/Desktop/Direct3D11.1/ScreenCapture) work ?

**Comment by xoofx** [comment]
- With 2.6.3, DuplicateOutput is part of DirectX11_2-net40 folder.
- With 3.0.0 it is included only the the bin\desktop directory.

**Comment by shiro900** [comment]
You are right, I completely did not see DirectX11_2-net40 folder. Sorry for my stupidity. The example compiled but it gives me a strange runtime exception.

![enter image description here][1]

Any idea what I could possibly be doing wrong ? Not even sure where to begin to solve this error. Someone in the [forum](http://sharpdx.org/forum/4-general/3417-type-initializer-exception-with-2-5-0-full-installer) said it is the graphics card driver issue. My operating system is windows 7 if it makes any difference. I forgot the source, but I heard that this would work only in windows 8 ? Is this true ? If so, is there any ScreenCapture example that works for windows 7 ?

  [1]: http://i.stack.imgur.com/G4STq.png
