### ISSUE TITLE
Question about SharpDX.Mathematics and Raw types

### ISSUE THREAD

**Issue by axefrog** [sharpdx/SharpDX#591]
Hey, I'm building a simple game engine for myself which is (so far) successfully abstracting away SharpDX to a separate library in anticipation of .NET 5.x and being able to target Mac/Linux (I guess I'd use OpenTK for those). One thing I'm lacking is a lot of the basic math types that are glued to SharpDX (Vector4, Color4, Matrix, etc.). I was going to use the SharpDX.Mathematics nuget package as it appeared to be somewhat independent but then I noticed all of the conversions to and from the "Raw" types, and thus the associated dependency on SharpDX. I started taking a copy of the bulk of SharpDX.Mathematics and stripping out the Raw* types into a separate portable library and it got me wondering; what are all those Raw types for? When are they used? I've never seen them come up in samples and my own code has never touched them, so I don't really understand their significance, or what the implication is for not having them.

**Comment by xoofx** [comment]
In the 3.0.0, raw types are used by all SharpDX/DirectX API to perform the interop with C++. They don't carry any methods and are lightweight structs. That way a higher level API like Paradox or MonoGame can perform directly conversion to these raw types without having to reference `SharpDX.Mathematics`. The `SharpDX.Mathematics` is just here to keep the samples working and is directly tied-up with SharpDX raw types to make conversion transparent to raw types.
Hope this makes sense.

**Comment by axefrog** [comment]
Ah yes, that makes sense. Thanks.
