### ISSUE TITLE
Building with Visual Studio 2015 RC

### ISSUE THREAD

**Issue by xanather** [sharpdx/SharpDX#595]
SharpGen says a "Fatal Error has occured" while trying to build. I tried a while to try figure out the reason why but gave up. I was trying to see if I can fix https://github.com/sharpdx/SharpDX/issues/594 as looking at the code it seems easy enough though I can't test my changes because it won't build.

I have Windows 10 Build 10130 x64 with WinSDK that comes with VS2015RC.

**Comment by xanather** [comment]
Trying to build on a Win8.1 machine with VS2013 won't work either since it can't find the DX12 headers which don't exist on Win8.1.

**Comment by xoofx** [comment]
Currently, SharpDX requires the Windows 10 SDK 10041 installed (thought not sure it is still downloadable). It means that if that SharpDX D3D12 on the latest Windows 10 is not working, but it should work for other APIs.

**Comment by xoofx** [comment]
Latest version is compiling with Windows SDK 10069
