### ISSUE TITLE
NuGet packages and newer .NET versions (4.5.1 - 4.6)

### ISSUE THREAD

**Issue by SuperJMN** [sharpdx/SharpDX#596]
I'm trying to upgrade my projects to .NET 4.6 using VS 2015 RC. 
They use the latest stable version of SharpDX (2.6.3). The current target is 4.5, but when I set it to 4.6, the package upgrade process fails. This is the exception I get:

Update-Package : Could not install package 'SharpDX.DXGI 2.6.3'. You are trying to install this package into a project that targets '.NETFramework, Version=v4.6', but the package 
does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Update-Package -Reinstall -ProjectName Perspex.Direct2D1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
 
This happens also when targeting to 4.5.1. It's a big problem, since I'm referencing PCL libraries that are compatible ONLY with 4.5.1+.

This is the current packages.config.
<package id="SharpDX" version="2.6.3" targetFramework="net45" userInstalled="true" />
<package id="SharpDX.Direct2D1" version="2.6.3" targetFramework="net45" userInstalled="true" />
<package id="SharpDX.DXGI" version="2.6.3" targetFramework="net45" userInstalled="true" />

**Comment by xanather** [comment]
Something must be wrong with your configuration, I was able to use SharpDX with .NET 4.5.2/4.5.1 just fine. Not sure about 4.6 though (moved to .NET Core since then).

**Comment by xoofx** [comment]
I know that nuget had an issue in a recent VS2015, but don't know if the fix was released publically.  Otherwise make sure that your NuGet Package Manager for Visual Studio 2015 is update to date.

SharpDX 3.0 should improve the process with nuget as we are no longer using custom `install.ps1` scripts
