### ISSUE TITLE
SurfaceQueue in SharpDX

### ISSUE THREAD

**Issue by devdept2** [sharpdx/SharpDX#599]
Hi,

I'm experiencing some synchronization issues in my WPF/SharpDX control, between the Directx11 Device and the D3DImage control (that uses a Direct3D9.DeviceEx device).

I already implemented the trick of copying a small subresource region to a staging texture (That I found in many places on the web), then querying the surface and doing a Map() / UnMap() which solved the issue in many occasions, but not all of them.

````
const int subResourceNumber = 0;
ResourceRegion resourceRegion = new ResourceRegion
{
    Back = 1,
    Bottom = 1,
    Front = 0,
    Left = 0,
    Right = 1,
    Top = 0
};
Context.CopySubresourceRegion(backBufferTexture, subResourceNumber, resourceRegion, _stagingTextureForSynchronization, subResourceNumber, 0, 0, 0);

using (Surface surface = _stagingTextureForSynchronization.QueryInterface<Surface>())
{
    DataStream dataStream;
    surface.Map(SharpDX.DXGI.MapFlags.Read, out dataStream);
    surface.Unmap();
    dataStream.Dispose();
}
````
Long ago I stumbled on this article by microsoft

https://msdn.microsoft.com/en-us/library/windows/desktop/ee913554(v=vs.85).aspx#interoperability_between_direct3d_9ex_and_dxgi_based_apis

where it says that 

*In order to share reading and writing to a Direct3D 9Ex shared surface, you must add manual synchronization to the application itself.
...
The producer-consumer building blocks are implemented in the helper by using a queue of surfaces. Surfaces are enqueued by the producer and dequeued by the consumer. The helper introduces three COM interfaces: ISurfaceQueue, ISurfaceProducer, and ISurfaceConsumer.*

and finally decided to give it a try.
But I can't find the SurfaceQueue class in SharpDX. Is this somethnig that is not supported?
If it's not supported, am I at a dead end to correctly synchronize the rendering in my WPF D3D control?

**Comment by xoofx** [comment]
> If it's not supported, am I at a dead end to correctly synchronize the rendering in my WPF D3D control?

Hi, as I have explained in issue #118 and #533  D3DImage sync is fundamentally broken and I don't know of any reliable workaround.

Concerning shared surface, there was a working solution in the old toolkit. Basically you need to create a Direct3D11 texture with support for Shared resource between D3D device (see [GameWindowDesktopWpf.cs](https://github.com/sharpdx/Toolkit/blob/9f95587d7b9ffaa9cf48993db79cc406f492ec71/Source/Toolkit/SharpDX.Toolkit.Game/Desktop/GameWindowDesktopWpf.cs#L241)) and correctly using with [D3DImage](https://github.com/sharpdx/Toolkit/blob/master/Source/Toolkit/SharpDX.Toolkit.Game/Desktop/D3D11Image.cs)

**Comment by devdept2** [comment]
Hi,

i think I solved it by doing the rendering on an extra texture and then doing a Context.ResolveSubresource on the texture shared with the D3DImage backbuffer.
It may not be the best performance-wise, since there's an extra texture-copy in between, but it seems to fix the issue.
