### ISSUE TITLE
Closed Issue #589

### ISSUE THREAD

**Issue by gagagu** [sharpdx/SharpDX#600]
Hi, you have closed my issue but it's not resolved.
DXGI_ERROR_UNSUPPORTED on Windows 7 #589 

I've installed two Systems completely new. One with Windows 7 -64 bit and one with 32 bit. I've installed all Drivers all Windows updates and the "Windows 7 DGXI Plattform update"!

One System is with AMD HD5770 and one with NVidia gtx 660 graphic Card.

I have installed visual Studio 2012, your 3.0.0-alpha1 Version and your samples from github.
On start of the Project "Direct3D11.1/ScreenCapture" i will get the following error on both Systems:
HRESULT: [0x887A0004], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_UNSUPPORTED/Unsupported], Message: Unknown

I've tested it on two extra Windows 7 Systems (no clean install) with the same error.

Thanks for your help

**Comment by xoofx** [comment]
So it means that it is not supported and I cannot do anything about this. This sample is working correctly on Windows 8 so I suspect that it does not work on Windows 7.
