### ISSUE TITLE
Access Violation while disposing BitmapFrameEncode or BitmapEncoder

### ISSUE THREAD

**Issue by Niharp21** [sharpdx/SharpDX#602]
We are rarely getting the below exception 
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

We feel that this is coming while disposing BitmapFrameEncode or BitmapEncoder object as shown in the below code :

 MemoryStream stream = null;
            BitmapEncoder encoder = null;
            BitmapFrameEncode bitmapFrameEncode = null;
            byte[] renderedBuffer = null;

            try
            {
                stream = new MemoryStream();

                switch (options.ImageType)
                {
                    case ImageType.PNG:
                        encoder = new PngBitmapEncoder(m_resource.WicFactory);
                        encoder.Initialize(stream);
                        bitmapFrameEncode = new BitmapFrameEncode(encoder);
                        bitmapFrameEncode.Initialize();
                        break;

                    case ImageType.GIF:
                        encoder = new GifBitmapEncoder(m_resource.WicFactory);
                        encoder.Initialize(stream);
                        bitmapFrameEncode = new BitmapFrameEncode(encoder);
                        bitmapFrameEncode.Initialize();
                        break;

                    default:
                        encoder = new JpegBitmapEncoder(m_resource.WicFactory);
                        encoder.Initialize(stream);
                        bitmapFrameEncode = new BitmapFrameEncode(encoder);
                        bitmapFrameEncode.Options.ImageQuality = (float)options.ImageQuality / 100;
                        bitmapFrameEncode.Initialize();
                        break;
                }

                bitmapFrameEncode.WriteSource(wicBitmap);
                bitmapFrameEncode.Commit();
                encoder.Commit();
                stream.Capacity = (int)stream.Length;
                renderedBuffer = stream.ToArray();

            }
            finally
            {
                if (encoder != null)
                {
                    encoder.Dispose();
                }
                if (stream != null)
                {
                    stream.Dispose();
                }
                if (bitmapFrameEncode != null)
                {
                    bitmapFrameEncode.Dispose();
                }
             
            }

We think that order of disposing might be the cause i.e. disposing bitmapFrameEncode at the last is the issue. It might be trying to dispose some resources which are already freed by BitmapEncoder or MemoryStream so disposing BitmapFrameEncode first might solve this issue.

Please let me know if you have any suggestions. We are using SharpDX DirectX11-net20 2.6.3 version

**Comment by xoofx** [comment]
Most likely you shoud dispose them in the reverse order of their creation ( bitmapFrameEncode, encoder, stream)
