### ISSUE TITLE
Debugging can stop unexpectedly when Direct2D factory created with debug flags (v2.6.3)

### ISSUE THREAD

**Issue by attackgoat** [sharpdx/SharpDX#608]
I had an issue where I was accidentally using two different SharpDX.Direct2D.Factory instances to draw a path; one factory created the render target and another the path.

Both factories were created with DebugLevel.Error | DebugLevel.Information | DebugLevel.Warning as the flags option. When my code hit the RenderTarget.FillGeometry(Geometry, Brush) method the debugger exits hard with code 0x4000001f (STATUS_WX86_BREAKPOINT) and no other details. Native code debugging and hosting process options didn't change the behavior. This certainly did not make debugging easy.

When both factories were created with DebugLevel.None then the FillGeometry method succeeds but the next call (RenderTarget.EndDraw) fails with a very helpful error:
HRESULT: [0x88990012], Module: [SharpDX.Direct2D1], ApiCode: [D2DERR_WRONG_FACTORY/WrongFactory]

**Comment by ArtiomCiumac** [comment]
The very helpful error means that you are trying to use two objects created
with a different factory.
Try to use the same factory instance for everything.

2015-07-08 17:56 GMT+01:00 attackgoat <notifications@github.com>:

**Comment by attackgoat** [comment]
Yes - that error was indeed as helpful as I mentioned - but that's not what I was trying to create any issue about.

I was trying to point out that the debugger stops in a way that makes it hard to find out why.

I don't see any code in the SharpDX source I would change to fix this but I know very little about how the build process for this code. If this is unrelated and identical to the unmanaged coding experience; well then I hope some future Googler find the keywords on this page and spends less time at this problem than I did. :)

**Comment by xoofx** [comment]
The behavior you get in C# is the same than in native C++ code. SharpDX cannot reduplicate all the checks that are already done by the native layer (except sometimes few cases with null check args) so you need to carefully check DirectX errors. Some APIs provide debug layers to better diagnostic these errors and this is the way to go.
