### ISSUE TITLE
ShaderResourceView.FromStream no longer available?

### ISSUE THREAD

**Issue by QuantumDeveloper** [sharpdx/SharpDX#610]
HI I updated to the latest alpha (002) and see that ShaderResourceView.FromStream() is no longer available. So, how to load textures with new library versions? Is there any alternatives?

**Comment by xoofx** [comment]
These APIs were part of old Direct3dx11 that are no longer provided or supported by Microsoft, so latest version is reflecting this. In order to load textures you need to use WIC or custom loader (or even System.Drawing if you are on desktop only). For WIC there was a working implem in the toolkit
