### ISSUE TITLE
Where to download latest dev version 3.0.0?

### ISSUE THREAD

**Issue by amerkoleci** [sharpdx/SharpDX#618]
Where can i download latest dev version, I have alpha02 from nuget, is there any more recent version?
I need recent XAudio changes.

**Comment by xoofx** [comment]
On sharpdx.org latest dev paxkage or teamcity results

**Comment by amerkoleci** [comment]
You mean this link:
http://sharpdx.org/upload/SharpDX-SDK-LatestDev.exe
