### ISSUE TITLE
Serializing Structs

### ISSUE THREAD

**Issue by dualdragoon** [sharpdx/SharpDX#621]
I have noticed that a large number of classes and structs in SharpDX are unable to be serialized conventionally as they are not marked as serializable and was wondering if there was any reason why they weren't, and if not, if you could do so as a project that I have been working to migrate from XNA to SharpDX requires some data to be serialized.

**Comment by xoofx** [comment]
Because `[Serializable]` attribute is not available on PCL (and basically on Windows Store Apps) so you should no longer rely on this attribute as it is not portable.
