### ISSUE TITLE
Access Violation while disposing WICStream

### ISSUE THREAD

**Issue by Niharp21** [sharpdx/SharpDX#626]
We are getting access violation while disposing BitmapEncoder which eventually crashes our process. Please find below the call stack from the crash dump ;

000000000c0b2080 000007fef1deeb52 System.AccessViolationException..ctor()
000000000c0fce78 000000000a517700 DomainBoundILStubClass.IL_STUB(Void*, UInt32)
000000000c0fd3a0 000007ff0188c8e8 SharpDX.ComObject.SharpDX.IUnknown.Release()
000000000c0fd3f0 000007ff018a0121 SharpDX.ComObject.Dispose(Boolean)
000000000c0fd440 000007ff0188c7e1 SharpDX.WIC.WICStream.Dispose(Boolean)
000000000c0fd480 000007ff018a00b2 SharpDX.DisposeBase.CheckAndDispose(Boolean)
000000000c0fd4c0 000007ff0188c7e1 SharpDX.WIC.BitmapEncoder.Dispose(Boolean)
000000000c0fd500 000007ff018a0012 SharpDX.DisposeBase.CheckAndDispose(Boolean)

We are disposing these resources in the below order : BitmapFrameEncode , WicBitmap , JpegBitmapEncoder and while disposing JpegBitmapEncoder we get access violation. This exception is very random in occurence

**Comment by xoofx** [comment]
The dispose order should match the reverse of the constructing order. If could you reproduce it with the simple [WIC sample code](https://github.com/sharpdx/SharpDX-Samples/blob/master/Desktop/WIC/EncodeDecode/Program.cs#L55), that would help.

**Comment by Niharp21** [comment]
I have kept the same order as in the sample code. Only difference  I am not using WICStream instead creating .NET MemoryStream. Will it make any difference?

**Comment by xoofx** [comment]
Well, the version taking a Stream is very convoluted under the hood, as the have to create a C++ ComStream wrapper around the .NET Stream, pass it to WIC that will callback the stream through this wrapper... Not something that I have been tested much.

If eveything is in memory, try using the methods that takes a pointer instead, just pin your managed array (or allocate a native memory directly if you don't need a managed array).
