### ISSUE TITLE
[UWP] Graphics diagnostics feature is not available ...

### ISSUE THREAD

**Issue by Gavin-Williams** [sharpdx/SharpDX#636]
I have a Universal Windows project in VS2015, targeting x64. I'm using SharpDX 3.0.0 alpha02 (via nuget). When i try to run graphics diagnostics I get the following message : 
  
  The Graphics Diagnostics feature is not available for this project type on the specified target platform.

https://social.msdn.microsoft.com/Forums/en-US/9b2c9519-0d80-4784-896f-a121230b717e/uwp-c-sharpdx-graphics-diagnostics-feature-is-not-available-?forum=csharpgeneral

**Comment by xoofx** [comment]
SharpDX can't do anything about this. It is Visual Studio that doesn't allow the usage of the Graphics Diagnostics with a C# project. If Graphics Diagnostics  was working, it would work with a plain C# UWP project without SharpDX, but it is not the case. It was the same case when they introduced it for Windows 8, it was not working with C# projects, they fixed it later.
