### ISSUE TITLE
Will there be support for UAP on W10?

### ISSUE THREAD

**Issue by ferzkopp** [sharpdx/SharpDX#638]
I was just trying to add the latest stable SharpDX package to a Universal App project in VS2015 and got this error:
SharpDX 2.6.3 is not compatible with UAP,Version=v10.0 (win10-x64-aot).

Would support be coming some time in the near future?

What would be needed to enable support for the platform? Any patches out there? Can one workaround by compiling SharpDX from sources? Can I help in any way (coding, testing)?

Thanks!

**Comment by xoofx** [comment]
Use the 3.0.0 version (latest beta is fine)
