### ISSUE TITLE
[UWP] Can't create swap chain for core window

### ISSUE THREAD

**Issue by Gavin-Williams** [sharpdx/SharpDX#639]
I'm trying to write a UWP application without xaml, so just using the IFrameworkView implementation method as described at https://msdn.microsoft.com/en-us/library/windows/apps/hh465033.aspx 

I've translated the window management part of that code from C++ to C#, so I have the window. But it looks like SharpDX is missing [Factory2.CreateSwapChainForCoreWindow](https://msdn.microsoft.com/en-us/library/windows/apps/hh404559.aspx) I don't see how a UWP (non-xaml) app can be built without that method (But still looking for a way).

**Comment by xoofx** [comment]
https://github.com/sharpdx/SharpDX/blob/e6bb4e3b5a8cfe27985a4a7f5346959d8076754e/Source/SharpDX.DXGI/SwapChain1.cs#L54

**Comment by NicolasPopy** [comment]
when i write this,  it tries convert corewindow to intPtr : 
`Factory2 f2 = adapter.GetParent<Factory2>();
            var W = Windows.UI.Core.CoreWindow.GetForCurrentThread();
            SharpDX.DXGI.SwapChain1 s1 = new SwapChain1(f2, mDevice, W, ref  swd1, null);`

There is 4 methods and visual studio tries to use 4th method.
