### ISSUE TITLE
[UWP] [DX12] Debug layer isn't working.

### ISSUE THREAD

**Issue by Gavin-Williams** [sharpdx/SharpDX#640]
I have the following code:

#if DEBUG
            {  DebugInterface.Get().EnableDebugLayer();  }
#endif   

and I have the debugger type set to Mixed (Managed & Native) but I don't get any debug output.

Edit : I can't even force debug layer on with DXControlPanel

**Comment by discosultan** [comment]
@Gavin-Williams How did you solve this issue? I also seem to miss something ...

**Comment by andrewst** [comment]
In windows 10 must be active "Graphics Tools" feature.
https://msdn.microsoft.com/en-us/library/windows/apps/mt210797.aspx

**Comment by discosultan** [comment]
@andrewst Thanks for pointing out the "Graphics Tools" feature!

In my case, I simply had to enable *native code debugging* from the project properties debug tab. I actually tested enabling this before, but I tested this in a scenario where the DX debug layer did not output any message - hence my confusion :)
