### ISSUE TITLE
SetRenderTargets Access violation

### ISSUE THREAD

**Issue by Gitii** [sharpdx/SharpDX#646]
Hi,

I've encountered an Accessviolation exception when setting the render targets.
I checked with the samples (latest one, dev3 beta1, although it also happens with 2.6.3).
I still think its somehow my fault (SetTargets and SetRenderTargets difference??), but maybe its really an error:

In my own code, I do:
```javascript
pd3dImmediateContext.OutputMerger.SetRenderTargets
(m_DepthStencilDSV, m_ColorSpecIntensityRTV, m_NormalRTV, m_SpecPowerRTV);
```
which results in:
```
0xC0000005: Zugriffsverletzung beim Lesen an Position 0xBFCB8EEC.
(Access violation at ...)
```
Setting the targets in sequence (nonsense) cause no errors:
```
pd3dImmediateContext.OutputMerger.SetRenderTargets
(m_DepthStencilDSV, m_SpecPowerRTV);
...
```
Altough
pd3dImmediateContext.OutputMerger.SetRenderTargets
(m_DepthStencilDSV, **new [] {** m_SpecPowerRTV **}** );

throws an exception like before. But this time the accessviolation is at position **0x01**.
But why? Its an params-parameter, in the end its an array anyway?! Setting it explicit should make no difference(?)

If I change it to SetTarget, no exceptions (I am still porting stuff, no (real) visual check possible).

I have checked this using the samples (Dx11, MiniTri, only changed the SetTarget-line) and its the same:
```
Ausnahme ausgelöst bei 0x7723A94D (kernel32.dll) in MiniTri.exe: 
0xC0000005: Zugriffsverletzung beim Lesen an Position 0x00000001.
```

Any ideas?

**Comment by weltkante** [comment]
SetRenderTargets does a [stackalloc inside an if-block](https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX.Direct3D11/DeviceContext.OutputMergerStage.cs#L481) but keeps using the resulting pointer outside of the if-block. Not sure if that is allowed, if it is not allowed that could cause an acces violation if the compiler reuses the stack space and overwrites it with other data.

Note that there are more methods like this which do the same thing, so if that's indeed the cause they all need to be fixed.

**Comment by Gitii** [comment]
Temporary I am using SetTargets as replacement. In my opinion stackalloc should not be used if the array is really kept by directx. On the other hand I see plenty of directx (c++) code which uses the stack for this. I think its best to consider this for the directx12 wrapper. Its a good opportunity to check it when.

**Comment by weltkante** [comment]
The array is not kept by directx, it's just temporary storage to unwrap the .NET objects and transfer the contained pointers over to C++.

From a quick test stackalloc seems to live until the function is left, so this might not be the source of the access violation after all. Either that or my test program was wrong and tested the wrong thing.

I'll try to reproduce your problem with your described changes to the sample programs.

**Comment by weltkante** [comment]
Found the problem, that function is broken, probably a copy/paste error. Has nothing to do with the stackalloc. I'll check if other overloads have the same issue and file a pull request.

**Comment by weltkante** [comment]
Explanation: `renderTargetViewsPtr` is already an array (allocated via stackalloc) so taking another address-of operator on it is one indirection too much. Probably has been copy pasted from [line 450](https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX.Direct3D11/DeviceContext.OutputMergerStage.cs#L450).
