### ISSUE TITLE
[Direct3D12] CreateGraphicsPipelineState throws NullReferenceException

### ISSUE THREAD

**Issue by weltkante** [sharpdx/SharpDX#647]
CreateGraphicsPipelineState throws a NullReferenceException for me. I can't guarantee that its not my mistake, but all the arguments seem set, except that I have left some shaders empty (I only need pixel and vertex shader for now). In C++ it worked leaving other shaders at null.

~~Could that be the cause for a NullReferenceException? [In the source](https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX.Direct3D12/Device.cs) I can see it is doing fixed-statements on all shaders without checking if the shaders are null. Would that throw an exception?~~

**[edit]** with some trial and error I figured out that it was the StreamOutputDescription not being set, even though I don't use it. Maybe make it a struct or add a null check? Feel free to close the issue if throwing a NullReferenceException instead of doing a null check is the intended behavior.

**Comment by xoofx** [comment]
Fixed in the commit 0ccabe1
