### ISSUE TITLE
[D3D12] SetRenderTargets mapping incomplete

### ISSUE THREAD

**Issue by weltkante** [sharpdx/SharpDX#649]
[ID3D12GraphicsCommandList::OMSetRenderTargets](https://msdn.microsoft.com/en-us/library/windows/desktop/dn986884.aspx) needs two overloads because the 2nd parameter can be either an array of handles or a single handle to a range of render targets. Which version it is is specified by the 3rd parameter, so you probably can leave that out and auto-set it depending on which overload was called.

Or if you don't like that you at least need to replace the current version to take an array of handles instead of a single handle, so the caller can decide which variant to use.

**Comment by xoofx** [comment]
Fixed in commit bfcd01245ba48433e7b722ca644e80b086475532
