### ISSUE TITLE
Compiled shaders as embedded resources

### ISSUE THREAD

**Issue by rickardp** [sharpdx/SharpDX#652]
I just discovered the `ToolkitFxc` build action in the toolkit to compile shaders to bytecode as part of the MSBuild build process, and it helps a lot.

However, it just creates a bytecode file in the output directory, which is usually not the end target for the shader. In my case, I want to add all shaders as embedded resources in the assembly so that it is self-contained.

It is fairly easy to accomplish what I want by appending the following to the .csproj file (with the caveat that it still creates the files in the output dir, and the following would also add other Toolkit* build action output):

    <Target Name="AfterCompileShaders" AfterTargets="TkListContentAndCompileTarget">
      <ItemGroup>
        
        <EmbeddedResource Include="@(TkContent)"/>
      </ItemGroup>
    </Target>

I think it would make a great addition to SharpDX if this was built into the toolkit, at it seems (at least to me) to be a quite common and good pattern (shaders is code, code goes into the assembly).

**Comment by xoofx** [comment]
Thanks. Unfortunately, as it was announced for the 3.0 milestone, the Toolkit is no longer supported or maintained.

**Comment by baSSiLL** [comment]
Thanks @rickardp for your snippet. I've modified it to prevent copying files to the output folder.
```xml
  <!-- Embed SharpDX.Toolkit resources into an assembly and remove them from the contents to prevent copying to output directory -->
  <Target Name="AfterCompileShaders" AfterTargets="TkListContentAndCompileTarget">
    <ItemGroup>
      <EmbeddedResource Include="@(TkContent)">
        <CopyToOutputDirectory>Do not copy</CopyToOutputDirectory>
      </EmbeddedResource>
      <Content Remove="@(TkContent)"/>
    </ItemGroup>
  </Target>
```
