### ISSUE TITLE
SharpDX.Direct3D12.FormatSupport1 & 2 should be marked with [Flags] attribute

### ISSUE THREAD

**Issue by Tape-Worm** [sharpdx/SharpDX#657]
I use this enumeration when using `CheckFeatureSupport` to determine available formats for display. I noticed (well, Visual Studio noticed) that the enum does not use the `[Flags]` attribute. 

I confirmed with the C++ equivalent of this code and the `FeatureDataFormatSupport.Support1` and `FeatureDataFormatSupport.Support2` do return OR'd enumeration values. 

This is not a huge deal as it all still works as it should. It's just VS being nit picky and driving me crazy in the process. :)

**Comment by xoofx** [comment]
Fixed. I have also changed the signature of the CheckFeatureSupport method to hopefully ease its usage.
