### ISSUE TITLE
SharpDX.Direct3D12.Device.CheckFeatureSupport uses an IntPtr for passing the feature values.

### ISSUE THREAD

**Issue by Tape-Worm** [sharpdx/SharpDX#658]
Another small item, but the `CheckFeatureSupport(Feature, IntPtr, int)` method requires an `IntPtr` to the necessary structure to pass to the method.

I'm pretty used to dealing with some semblance of "unsafe" code in C# (that said, it's not like we're forced to use an unsafe context here).  But for others this might pose a problem as they might not be comfortable dealing with an IntPtr.  More than anything, it just might be too C++ for some :)

Perhaps providing a generic method like `T CheckFeatureSupport<T>(Feature)` or something along those lines to return the appropriate values would be better?

**Comment by xoofx** [comment]
Fixed in commit 2d5f8b6bcea88be0682d9329ca946d9eff779ab9
