### ISSUE TITLE
Update sources to match latest Win 10 SDK

### ISSUE THREAD

**Issue by QuantumDeveloper** [sharpdx/SharpDX#663]
Today Win 10 received an updates (including new SDK version) and now Sharpdx is broken because it expects earlier SDK version.
Seems it need to be update in the code.

**Comment by RobyDX** [comment]
Me too, after update my D3D12 apps don't work anymore.

**Comment by RobyDX** [comment]
I've received an update for Windows. Now all sample works, except for texture ones. But I've discovered from debug messages that is changed memory managed. I've replaced HeapProperties for texture creation with this
new HeapProperties(CpuPageProperty.WriteBack, MemoryPool.L0)
and now all works :+1:

**Comment by GrafSeismo** [comment]
Ah good to know that i am not alone with missing functionality after VS Update 1. In my case Direct2D1 is sadly missed ;)

**Comment by xoofx** [comment]
It is updated. The automatic build for SharpDX binaries is not.
