### ISSUE TITLE
Ps3/ps4 controller DirectInput

### ISSUE THREAD

**Issue by sueds** [sharpdx/SharpDX#664]
I'm trung to add ps3 controller support to my game but even if sharpdxDirectInput recognise my gamepad , there is not update in the gamepad state. 

Is it possible to add ps3 gamepad support with directInput or should I just write a using rawinput.

**Comment by stilldesign** [comment]
It seems DirectInput is considered deprecated now (https://en.wikipedia.org/wiki/DirectInput)
RawInput works reasonably well, it certainly works for the PS4 controller as I just recently added it to my engine, plus all the hard work of mapping raw input values has already been done here: https://code.google.com/p/ds4-tool/source/browse/ScpControl/DS4Device.cs

**Comment by xoofx** [comment]
Unlikely supported by DirectInput out-of-the-box. So better try RawInput.
