### ISSUE TITLE
SharpGen Fatal error

### ISSUE THREAD

**Issue by h3h3** [sharpdx/SharpDX#669]
Hey, i can't get SharpGen to work while following any of these docs.
https://github.com/sharpdx/SharpDX#build
https://github.com/sharpdx/SharpDX/wiki/Building
https://github.com/sharpdx/SharpDX/issues/623

SharpGen fails with 'A fatal error occured' with the following output.
https://www.zerobin.net/?12c4cb3046a107ac#6DOtaycUg9BINlwfhBRn+FbCV4e1x+lrZ+uy8RYn0R8=

Environment: 
Win8.1 x64
VS13u2 & VS15
WinSDK 10.1.10586.15 & 8.100.26936
DXSDK Jun10 + checked if DXSDK_DIR exists
using latest master

**Comment by ehmehe** [comment]
Can confirm!

**Comment by h3h3** [comment]
fixed
