### ISSUE TITLE
SharpDX.Utilities.AllocateMemory OverflowException

### ISSUE THREAD

**Issue by Yourself** [sharpdx/SharpDX#670]
I've been encountering an intermittent issue with SharpDX 2.6.3 wherein a call to `SharpDX.Utilities.AllocateMemory` will throw a `System.OverflowException`.  Ultimately this is coming from within a call to `SharpDX.Toolkit.Graphics.Texture2D` when attempting to save a texture to disk as a PNG.  The texture is quite large (4096x4096) and has mip-maps enabled.

I've seen this issue occur when calling `Utilities.AllocateMemory` in isolation and asking for 128 MB (with the default alignment).  The test case also includes a call to `Utilities.FreeMemory`, so it doesn't seem to be a low memory problem.  The exception will get thrown randomly, sometimes on the first invocation and sometimes not at all.

**Comment by xoofx** [comment]
Maybe related to a fix that was applied recently 186479d05b83ac3bf5e18985b8b56c03d38f2c4f It is available on latest 3.0.0 release (note that the Toolkit is no longer supported in this version)

**Comment by xoofx** [comment]
Should be fixed.
