### ISSUE TITLE
Direct2D Transformation issue

### ISSUE THREAD

**Issue by vxd-dev** [sharpdx/SharpDX#672]
I am using the SharpDX.Direct2D to draw 2D geometries. Each coordinate should be transformed from Word coord. system to image by the following formula:
dx = (point.X - translationX)/PixelWidth; 
dy = (translationY - pointY)/PixelHeight;

If I apply this formula manually everything is fine. However I decided to use the Matrix3x2 transformation instead of calling the convert method for each point manually.
I have tried to multiply two matrices: Matrix3x2.Translation(-translationX, -translationY) * Matrix3x2.Scale(1/PixelWidth, -1/PixelHeight), but got a quite strange result as you can see on the screen attached. Looks like a 3D sphere. Also if I make a transformation of points in debug I receive the same result for Matrix3x2.TransformPoint and for my transform method, so the rendering result should be also the same.
![screen1](https://cloud.githubusercontent.com/assets/16404864/11962865/a8c0689e-a8eb-11e5-9632-2a63383d3f06.PNG)
The correct result (rendered without transformation) is the following:
![screen2](https://cloud.githubusercontent.com/assets/16404864/11963041/d074b1c8-a8ec-11e5-96ec-97a82b7d3591.PNG)

**Comment by xoofx** [comment]
I can't see why you get invalid results, the following code gives expected result:

```C#
var translation = Matrix3x2.Translation(-1, -2);
var scaling = Matrix3x2.Scaling(0.25f, 0.5f);
var transform = translation * scaling;
var result = Matrix3x2.TransformPoint(transform, new Vector2(2, 3));
Assert.AreEqual(new Vector2(0.25f, 0.5f), result);
```
so I assume that there is something wrong in your code somewhere... Also you are talking about rendering results that can imply many other problems (upload data to GPU...etc.), so can you post some actual code using only Maths API that reproduce this bug?

**Comment by xoofx** [comment]
Closing this issue for now. If you have any reproducible test case, I will reopen it, thanks
