### ISSUE TITLE
[MediaFoundation]Wrong DLL import

### ISSUE THREAD

**Issue by laheller** [sharpdx/SharpDX#673]
Import for [MFPCreateMediaPlayer](https://msdn.microsoft.com/en-us/library/windows/desktop/dd375520(v=vs.85).aspx) function is wrong, because it references **mfplat.dll** but it should reference **mfplay.dll**.

**Comment by laheller** [comment]
Fun fact: Microsoft says for the function above: _Deprecated. This API may be removed from future releases of Windows. Applications should use the Media Session for playback._
But this functions works well on Windows 10 Professional x64 :+1:

**Comment by amerkoleci** [comment]
This should be closed as I submitted PR.
