### ISSUE TITLE
Change target framework to .NET 4.0 Client Profile

### ISSUE THREAD

**Issue by mkalex777** [sharpdx/SharpDX#680]
Could you please change target framework to .NET 4.0 Client Profile?
It's the maximum version which is supported on Windows XP, so I'm using it in my project.
I cannot add reference on SharpDX, because it was built for different framework.
If I switch to .NET 4.5 it works ok, but it's not suitable for me, because I need .NET 4.0 client profile.
Thanks

Here is VS error:
Warning	19	The primary reference "SharpDX, Version=2.5.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the framework assembly "System.Collections, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0,Profile=Client". To resolve this problem, either remove the reference "SharpDX, Version=2.5.0.0, Culture=neutral, processorArchitecture=MSIL" or retarget your application to a framework version which contains "System.Collections, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".	TestSharpDX

**Comment by xoofx** [comment]
I can't as I want the PCL Profile used for desktop to be compatible with CoreCLR.

You can still use assemblies from 2.6.3 which supports 4.0 or compile 3.0.0 and change profile [settings in the source](https://github.com/sharpdx/SharpDX/blob/8acef9e0bb7271187859c9720e99c17314fa2a89/Build/SharpDX.PreSettings.targets#L39).
