### ISSUE TITLE
Can we have full initialization constructors for all Raw* types, like RawRectangleF has?

### ISSUE THREAD

**Issue by jnm2** [sharpdx/SharpDX#681]
It's just a bit of a pain to type `new Vector2 { X = x, Y = y }` instead of `new RawVector2(x, y)`, especially right next to `new RawRectangleF(left, top, right, bottom)`.

**Comment by OndrejPetrzilka** [comment]
Isn't the point of Raw* not to use it directly? E.g. you create new Vector2 with any constructor it has, implicit cast will convert it to RawVector2.

`new Vector2(x,y)` seems fine to me, no need to write `new Vector2() { X = x, Y = y }` or `new RawVector2() { X = x, Y = y }`

**Comment by Gavin-Williams** [comment]
I agree. The whole notion of having *another* vector class, like we don't have enough out there already is ridiculous. C# can't handle this stuff, now I need an engine class that internally converts to a SharpDX class, and what, now I need to consider raw versions as well. This whole business of rewriting and cooperating these math classes was already out of hand, even before SharpDX introduced the raw's.

**Comment by amerkoleci** [comment]
This should be closed as I submitted PR.

**Comment by jnm2** [comment]
@amerkoleci @xoofx Awesome! Thank you!
