### ISSUE TITLE
DllNotFoundException calling ShaderBytecode.Compile on Windows 7

### ISSUE THREAD

**Issue by InfiniteMort** [sharpdx/SharpDX#683]
With the 3.0 release of SharpDX, I get the following DllNotFoundException when calling ShaderBytecode.Compile or ShaderBytecode.CompileFromFile:

Unable to load DLL 'd3dcompiler_47.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

The problem occurs calling the compile methods on Windows 7, but not on Windows 10. The problem did not occur when calling the compile methods using SharpDX 2.6.3 (On .NET Framework 4.0).

**Comment by xoofx** [comment]
This is expected. SharpDX 3.0 is built on D3DCompiler 47 which is included in Windows 8.1+ OS

You need to redistribute the DLL yourself in order to run on prior OS (check in folder like `%ProgramFiles(x86)%\Windows Kits\10\Redist\D3D\x86`

**Comment by InfiniteMort** [comment]
This is unfortunate, as it means that it won't be possible to create AnyCPU applications that can run on Windows 7, Windows 8 and Windows 10, without requiring an installer which first installs the d3dcompiler_47.dll on the target operating system.

**Comment by xoofx** [comment]
Not entirely correct, at least on desktop you can make it easily: 
- ship the `d3dcompiler_47.dll` into two sub folders (`x86`, `x64`) along your app. No installer are required.
- at startup, preload the correct d3dcompiler_47 with a `LoadLibrary` Win32 function

Subsequent DllImport will work transparently once the DLL has been already loaded.

**Comment by InfiniteMort** [comment]
Thank you, I will try that.
