### ISSUE TITLE
Depth Issue after upgrading to 3.0.0

### ISSUE THREAD

**Issue by Shuun** [sharpdx/SharpDX#688]
After updating to 3.0.0 Depth buffer does not seem to be working properly. Worked fine on 2.6.3. Windows 10, 64bit, also tested on reference and warp device types and got the same results. After inspecting in visual studio's graphics debugger it seems that depth is always written out as 0, instead of its actual value - that means that whatever mesh gets drawn last gets on top of everything else. What could be the problem?

**Comment by QuantumDeveloper** [comment]
maybe you just clear your depth buffer before drawing?

**Comment by Shuun** [comment]
Yes, i clear the depth buffer before drawing, giving it a clear value of 1.0 across the board, then after each mesh is drawn, depth buffer is given value 0.0 everywhere the mesh occupies the screen, regardless of actual depth.

**Comment by Shuun** [comment]
So the issue is this - the old ViewportF assigns MinDepth = 0.0f and MaxDepth = 1.0f as default by using constructor, but the new RawViewportF needs explicit assignment of those or it just leaves them as 0...

**Comment by xoofx** [comment]
Why not using `SharpDX.Mathematics.ViewportF`? The Raw value are not intended to be used directly.
