### ISSUE TITLE
Error creating XInput Controller in Windows 7

### ISSUE THREAD

**Issue by jeremyharris99** [sharpdx/SharpDX#689]
I am trying to create a `SharpDX.XInput.Controller` for `UserIndex.One`.  When my code calls the `Controller` constructor, a dialog pops up as follows
![image](https://cloud.githubusercontent.com/assets/15331856/12153829/6493dfae-b479-11e5-8cfb-58a7b7798c40.png)

Once I click OK, my program proceeds as expected. The `Controller` object is created properly and seems to work fine. Also, subsequent attempts to create a `Controller` object for any `UserIndex` (even One again) work correctly without showing the dialog.

**Comment by BrannonKing** [comment]
Do we need to check the OS version number before attempting to load XInput14? It seems that is a Windows v8+ thing.

**Comment by jeremyharris99** [comment]
Oops... Totally user error... Further testing has revealed this was due to me putting the Xinput1_4.dll into my system folder. It doesn't properly run on Windows7, and it was the LoadLibrary call that was causing this dialog to be displayed. Issue can be closed...
