### ISSUE TITLE
Release RawInput and DirectInput for PCL (v3.0)

### ISSUE THREAD

**Issue by mklemarczyk** [sharpdx/SharpDX#693]
Can you release RawInput 3.0 and DirectInput 3.0 for PCL?

**Comment by xoofx** [comment]
Should be fixed, sorry for the trouble.

**Comment by mklemarczyk** [comment]
Errors still occurs in release 3.0.1.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'SharpDX.DirectInput 3.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'SharpDX.RawInput 3.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

```

**Comment by xoofx** [comment]
It is working perfectly here on a desktop .NET project.

On what kind of projects (.NET version, .NET platform) are you trying to use DirectInput?

**Comment by mklemarczyk** [comment]
I want use it on Windows Store app library.

**Comment by xoofx** [comment]
`DirectInput` and `RawInput` has never been released for Windows Store App, as they are not supported by Microsoft on this platform. You need to use the proper [Windows Input API](https://msdn.microsoft.com/en-us/library/windows/apps/windows.devices.input.aspx) or XInput if you are looking for gamepads.

**Comment by mklemarczyk** [comment]
You released it in 2.6.3 version, why there is a problem right now?

**Comment by xoofx** [comment]
You said:
> I want use it on Windows Store app library (I use PCL).

And then now:
> Windows Input API is not available in Windows Forms and WPF applications.

Can you explain clearly which platform exactly are you actually targeting?

> You released it in 2.6.3 version, why there is a problem right now?

`DirectInput` and `RawInput` have **never** been released in SharpDX for Windows Store apps for the reason that they are not allowed by Microsoft on the Store. Double check 2.6.3, they are not there, so please, can you take the time to dig into your problem before coming back here? (sorry to be rude, but I don't like feeling being trolled)

**Comment by mklemarczyk** [comment]
I'm targeting all .NET platforms.

Try by yourself to add references:
packages\SharpDX.2.6.3\Bin\DirectX11-Signed-net40\SharpDX.DirectInput.dll
packages\SharpDX.2.6.3\Bin\DirectX11_2-Signed-net40\SharpDX.RawInput.dll

into PCL with Profile111.
It works on my machine, with published by you NuGet packages.

**Comment by xoofx** [comment]
> I'm targeting all .NET platforms.

Good, then you need to know that you cannot target Store Apps using `DirectInput` or `RawInput`, so you basically cannot target this platform.

> Try by yourself to add references:

Of course you can add these references to a PCL assembly (btw, they are not PCL but standard .NET 4.0 assemblies, the compiler is not hard-checking that they must be PCL, you should be able to do the same with 3.0 assemblies by referencing them directly), but if you run your app through the Windows App Certification Kit, you will see that they are not allowed, and any apps trying to use your assemblies for a Store App will be refused.

So again, you cannot target all platforms with DirectInput and RawInput.
