### ISSUE TITLE
Possible issue with v3.0.0 on Windows 10?

### ISSUE THREAD

**Issue by BEEden** [sharpdx/SharpDX#697]
I have been using SharpDX for some time now and it has been very reliable and easy to work with.  Recently I upgraded to v3.0.0 and aside from having to make a few changes from Vector2 to RawVector2, it was a no-brainer.  

However, it soon became apparent that I had a few unresolved memory leaks, so I installed the Windows 10 SDK so that I could access the D3D Debug Layer.  This is where my problems started -- although I was able to quickly locate and resolve all of the memory leaks, installing the Windows 10 SDK killed the performance of my project -- whether or not the debug layer is turned on.  I went from being able to have 1200 or so integration-driven Direct2D1 geometries running on-screen at a stable 60fps, down to less than 300 before the application becomes slow and sometimes completely unresponsive.

After spending hours trying to locate the source of the problem, including extensive profiling, I loaded an old SharpDX project from a few months ago and found that it exhibited the same behaviour, even when run from a pre-compiled binary that was built months ago.  I also tried another workstation running Windows 10 and even updated the nVidia driver to the latest version just in case, albeit with no luck.

It appears that installing the Windows 10 SDK was the cause of the problem, but uninstalling it does not resolve the issue.  i am running Visual Studio 2013 with all updates installed.  Any suggestions would be gratefully received!  Many thanks.

**Comment by xoofx** [comment]
So there is no "possible issue with v3.0.0 on Windows 10" then? :p
Sorry, I can't really help on this, you should try to contact DirectX/Microsoft about this.

**Comment by BEEden** [comment]
Well, I used the term "possible", because I didn't want to assume straight away that SharpDX was the problem -- it has been fast, very reliable, very easy to use and I cannot recommend it enough.  I was hoping that someone else might have experienced something similar.  Thanks anyway, xoofx.
