### ISSUE TITLE
Why does ObjectReference.StackTrace not contain the stack trace?

### ISSUE THREAD

**Issue by jnm2** [sharpdx/SharpDX#698]
Every object has this string for the stack trace: 
```
   at SharpDX.Diagnostics.ObjectTracker.GetStackTrace()
```

`Configuration.EnableObjectTracking = true;` is being set. Is there another stack trace setting I missed, or documentation for anything that can affect the stack trace? Or is it a bug?

**Comment by xoofx** [comment]
This is a f**k**g bug of PCL :(

If you are on desktop, you should be able get get a reliable stack trace by overriding it on the ObjectTracker:

```c#
ObjectTracker.StackTraceProvider  =  () => Environment.StackTrace;
```

On other platforms, afaik, there are no workarounds.
