### ISSUE TITLE
Add netstandard1.5 to list of targets.

### ISSUE THREAD

**Issue by xanather** [sharpdx/SharpDX#699]
As shown here https://github.com/dotnet/cli/issues/907 dnxcore50 needs to be an available target to compile with .NET Core.

**Comment by xanather** [comment]
Actually its still possible to use SharpDX without adding a dnxcore50 target (by forcefully adding/overriding additional imports). Will leave issue open, other third-party libs will probably add direct support for it in the future so might be in SharpDX interest to add it too.

This is what I am talking about:
    "dnxcore50": {
      "imports": "portable-net45",
    }

**Comment by xanather** [comment]
Update: https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-standard-applications.md

**Comment by xanather** [comment]
Looks like NET Standard 1.5 is settled

**Comment by JimSEOW** [comment]
IT is time to [support .NET Standard 2.0](https://github.com/sharpdx/SharpDX/issues/864#issuecomment-324872484) ( including UWP6.0)

**Comment by xoofx** [comment]
SharpDX supports .NET Standard1.1 which is compatible with .NET Standard 2.0

**Comment by JimSEOW** [comment]
@xoofx thanks for reminder. should have checked the dependencies.
