### ISSUE TITLE
Can I use XAudio2 for save the output ?

### ISSUE THREAD

**Issue by arsenium** [sharpdx/SharpDX#704]
I am working on a Windows 8.1 App that does some audio mixing and recording. Can I use XAudio2 for save the output stream? Save a mix of multiple voices to a wav file.

**Comment by xoofx** [comment]
Unfortunately XAudio2 doesn't provide such a feature out of the box. You could may be develop an effect (see [PlaySoundCustomXAPO](https://github.com/sharpdx/SharpDX-Samples/tree/master/Desktop/XAudio2/PlaySoundCustomXAPO) sample) that you plug before the final mix and would capture the mix. Note that there is no way to capture a mix without playing it to an output.
