### ISSUE TITLE
XAudio2 SourceVoice.State.SamplesPlayed always returns 0 in 64-bit configurations

### ISSUE THREAD

**Issue by waltdestler** [sharpdx/SharpDX#709]
Hello!

I have attached a simple Visual Studio project that reproduces this issue. Specifically, the issue is that  SourceVoice.State.SamplesPlayed always returns 0 when the project is set to x64 (or Any CPU with "Prefer 32-bit" off), whereas it works properly when the project is set to x86 (or Any CPU with "Prefer 32-bit" on).

This is occurring with SharpDX 3.0.1 (from Nuget) on Visual Studio 2015 Update 1 targeting .Net 4.6.1. (I haven't yet tested any other setups.)

Steps to reproduce:
1. Load and run the attached Visual Studio project.
2. A "cannon" sound will play and output will be logged to the console window.
3. Note that as the sound plays, the "Samples played" counts up.
4. Go into the project properties, and on the Build tab change the "Platform target" from x86 to x64.
5. Run the project again. Note that the sound plays but the "Samples played" stays at 0.

Please let me know if there's any more information I can provide in order to help debug this issue. Thanks so much!

[Test.zip](https://github.com/sharpdx/SharpDX/files/135489/Test.zip)

**Comment by xoofx** [comment]
Hi, thanks for the report! Currently I have no spare time left for digging into SharpDX issues. PR are welcome.

**Comment by waltdestler** [comment]
Okay, so I believe I know exactly what the problem is, but I'm not sure how to fix it since the issue is in a generated file, and I'm not familiar with how SharpDX generates files from the C++ headers.

Specifically, I believe the problem is with how the JIT aligns the VoiceState struct on 64-bit architectures. Here's what the VoiceState structure looks like (without the comments):

    [StructLayout(LayoutKind.Sequential)]
    public  partial struct VoiceState {	
        public System.IntPtr Context;
        public int BuffersQueued;
        public long SamplesPlayed;
    }

My hypothesis is that the JIT by default will align the SamplesPlayed on an 8-byte boundary. On x86 the Context IntPtr will be 4 bytes (and BuffersQueued is of course 4 bytes), meaning that the JIT won't insert any padding between BuffersQueued and Samples Played. But on x64 the Context IntPtr will be 8 bytes, which I believe will cause the JIT to insert 4 bytes of padding between BuffersQueued and SamplesPlayed; padding which the C++ API apparently doesn't have.

I verified my hypothesis by manually adding a Pack=4 to the StructLayout attribute...

    [StructLayout(LayoutKind.Sequential, Pack=4)]
    public  partial struct VoiceState {	
        public System.IntPtr Context;
        public int BuffersQueued;
        public long SamplesPlayed;
    }

... which fixes the issue on x64 (and still works fine on x86).

However, since VoiceState is in a generated file, I'm not sure how to tell the generator to add the Pack=4 to the VoiceState structure. If you can give me some direction on how to make that change, then I'd be happy to fix the bug and submit a pull request.

Thanks!

**Comment by xoofx** [comment]
Thanks for digging. In the past, I think that the Pack = 4 was generated explicitly, but I removed it at some point because it was not working for some other stuffs. I haven't checked XAudio2, but I suspect that they are introducing some pragma packs in their code.

You can try to add the following line to [Mapping-xaudio2.xml:220](https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX.XAudio2/Mapping-xaudio2.xml#L220)

        <map struct="XAUDIO2_.*" pack="4" />

**Comment by waltdestler** [comment]
That seems to work great!

Incidentally, as I was scanning through the XAudio2 structs to make sure that setting Pack=4 on all of them wouldn't break anything, I noticed that AudioBuffer's Context field had a similar packing issue on x64, which your suggestion also fixes.

I'll go ahead and submit a pull request to fix this.

Thanks for your help!

**Comment by waltdestler** [comment]
This got fixed by pull request #710
