### ISSUE TITLE
Cannot find type System.MarshalByRefObject in module CommonLanguageRuntimeLibrary.

### ISSUE THREAD

**Issue by ThePademelon** [sharpdx/SharpDX#720]
when I try and compile after referencing SharpDX.Desktop in my Universal Windows Platform application I get this error:

> Xaml Internal Error error WMC9999: Cannot find type System.MarshalByRefObject in module CommonLanguageRuntimeLibrary.

**Comment by xoofx** [comment]
You cannot use `SharpDX.Desktop`. It is only valid for win32 desktop app, not UWP.
