### ISSUE TITLE
[UWP] DirectInput not compatible package

### ISSUE THREAD

**Issue by odens** [sharpdx/SharpDX#721]
Can not install SharpDX.DirectInput 3.0.1 on UWP project.
Here are output:
Restoring packages for 'App8'.
Restoring packages for d:\dev\App8\App8\project.json...
SharpDX.DirectInput 3.0.1 is not compatible with UAP,Version=v10.0.
Some packages are not compatible with UAP,Version=v10.0.
SharpDX.DirectInput 3.0.1 is not compatible with UAP,Version=v10.0 (win10-arm).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
SharpDX.DirectInput 3.0.1 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
SharpDX.DirectInput 3.0.1 is not compatible with UAP,Version=v10.0 (win10-x86).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
SharpDX.DirectInput 3.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
SharpDX.DirectInput 3.0.1 is not compatible with UAP,Version=v10.0 (win10-x64).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
SharpDX.DirectInput 3.0.1 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
Package restore failed for 'App8'.
Package restore failed. Rolling back package changes for 'App8'.

**Comment by xoofx** [comment]
`DircetInput` is deprecated and not a certified API for UWP, so they are not allowed, so SharpDX cannot provide it. See #693 for other details
