### ISSUE TITLE
[DirectInput] Please add GetObjectInfoByOffset to CustomDevice

### ISSUE THREAD

**Issue by iayucar** [sharpdx/SharpDX#726]
Hi guys, 

When a JoystickUpdate comes, the offset included there points to a field in the RawJoystickState struct. Sometimes, it's necessary to find what actual DeviceObjectInstance is related to that update. 

For that, it would be necessary to clall GetObjectInfo(offset, PropertyHowType.Byoffset), but GetObjectByInfo is internal in your implementation. You already give access to some overloads of it with GetObjectInfoByName, GetObjectInfoById, and GetObjectInfoByUsage, but it lacks the last one: GetObjectInfoByOffset, which is crucial to do that mapping.

Could you please add this method to CustomDevice.cs, so we can access that feature? It would be the following lines:

public DeviceObjectInstance GetObjectInfoByOffset(int offset)
{
       return GetObjectInfo(offset, PropertyHowType.Byoffset);
}

Or else, is there any other way I have missed to map offsets in the RawJoystickState struct to DeviceObjectInstances?

Many thanks in advance, and congrats for your great great work. 

Cheers, 

Iñaki Ayucar

**Comment by xoofx** [comment]
Fixed by #727

**Comment by markusbuschhoff** [comment]
The request (found by googling) misled me to believe that the offsets in JoystickUpdate and DeviceObjectInstance are comparable. They are not. 

As an example: My Saitek Rudder Pedals have three DeviceObjectInstances with offsets 0, 4, 8 (these are left toe brake, right toe brake and rudder). But, the JoystickUpdate structure for the Rudder has a RawOffset of 0x14. 

Actually, there seems to be only a very crude way of matching JoystickUpdates to DeviceObjectInstances: The JoystickUpdate.Offset can be mapped to HID Page and Code which can be used to find an ObjectInstance. There should be a better way of doing this.
