### ISSUE TITLE
Unable to create Debug device wit Windows SDK 10.0.26624

### ISSUE THREAD

**Issue by devdept2** [sharpdx/SharpDX#732]
Hi,

After installing the Windows SDK 10.0.26624 I'm no longer able to create a device with debug creation flags.

```
var factory = new Factory2();
Device = new Device(factory.Adapters[0], DeviceCreationFlags.Debug | DeviceCreationFlags.BgraSupport);

```
With SharpDX 2.6.3 I get:

_Exception thrown: 'SharpDX.SharpDXException' in SharpDX.dll_

_Additional information: HRESULT: [0x887A002D], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: The application requested an operation that depends on an SDK component that is missing or mismatched._

With SharpDX 3.0.2 I get:

_Exception thrown: 'SharpDX.SharpDXException' in SharpDX.dll_

_Additional information: HRESULT: [0x887A002D], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_SDK_COMPONENT_MISSING/SdkComponentMissing], Message: The application requested an operation that depends on an SDK component that is missing or mismatched._

**Comment by xoofx** [comment]
It is quite awkward, but the Windows SDK doesn't include the debug layer (!)

You need to install the [optional feature Graphics Tools](https://msdn.microsoft.com/en-us/library/windows/apps/mt210797.aspx)

**Comment by devdept2** [comment]
Thank you very much!

**Comment by devdept2** [comment]
Hi,

I managed to install the Graphics Tools and with 2.6.3 I can now create a Device with Debug flags, but in 3.0.2 I get:

Exception thrown: 'SharpDX.Diagnostics.ObjectTracker.GetStackTraceException' in SharpDX.dll
