### ISSUE TITLE
Please return back D3D10.

### ISSUE THREAD

**Issue by donggas90** [sharpdx/SharpDX#733]
Hi,
I'm working on a game and game tools with SharpDX. 
My target platform is Win7 and I'm using D2D interoperation.
But DX11 in Win7 dose not fully support D2D interop as I know.
http://stackoverflow.com/questions/11771257/using-direct2d-to-draw-on-direct3d11-surface
Definitely, the MS had been guaranteed the interoperation only with the D3D10.1 by their document.
https://msdn.microsoft.com/en-us/library/windows/desktop/dd370966(v=vs.85).aspx
(DX12+ has been guaranteed as well. but my target platform is Win7 that is using DX11.)
I'm sure about that SharpDX had supported D3D10 but not now.
Maybe you thought D3D10 is needless because of D3D11 and 12 but it's not.
Please return back D3D10.

**Comment by czenzel** [comment]
I second this. I need the ability to do some 2D for an app I am working on for HoloLens: basic text and basic overlays. I have been researching all day and can't find anything linking these two other than what is mentioned above (shared device between Direct3D 10 and Direct2D).

**Comment by xoofx** [comment]
Have you try to install https://support.microsoft.com/en-us/kb/2670838 ?
For reference http://stackoverflow.com/a/31868992/1356325

I removed D3D10 based on this, but it may not be ideal if the KB above doesn't work or it is not installed automatically by a Windows updarte (I thought it was), so I will have to restore D3D10.

**Comment by donggas90** [comment]
Yes, it has not installed automatically. Checked my Windows 7.
And I don't think, it's a master solution. 
Some end user should suffer about this. And should drop reliability of my SWs.

As you know and the article said, only support partially in Win7. It's not change when the update installed.
Maybe in other nations' people use new Windows such as 8 and 10 popularly.
But in our nation, most popular Windows is 7 yet and I'm using it as well. So I need full interface in Win7.

**Comment by chedburgh** [comment]
I'd like to third this. I have coded up a custom Direct2D WPF control for a games tool, and I'd like to support Win 7 - Win 10. I've stayed on 2.6.X so far, but I suspect I'm going to need to move to the latest at some point.

**Comment by chedburgh** [comment]
I'd like to third this. I have coded up a custom Direct2D WPF control for a games tool, and I'd like to support Win 7 - Win 10. I've stayed on 2.6.X so far, but I suspect I'm going to need to move to the latest at some point.

**Comment by RobyDX** [comment]
I've coded some sample using Direct3D11 and Direct2D using SharpDx. Here the archive
https://github.com/RobyDX/SharpDX_Demo
Check if they work on Windows 7 (I'm using Windows 10)

**Comment by donggas90** [comment]
@RobyDX I already known about that it is working **ALMOST** of Win7s. But my objective is covering ALL of Win7s. NOT ALMOST. So I need guaranteed method.

**Comment by xoofx** [comment]
Thanks to the work of @andrewst this should be fixed by latest commit. See #760 
A new release will be done in the coming days with a new nuget package.
