### ISSUE TITLE
Exception when creating Debug device on Windows 10 and SharpDx 3.0.2

### ISSUE THREAD

**Issue by devdept2** [sharpdx/SharpDX#735]
I'm getting a ton of 

> _Exception thrown: 'SharpDX.Diagnostics.ObjectTracker.GetStackTraceException' in SharpDX.dll_

when creating a Direct3D11 device with Debug flags in Windows 10 with SharpDX 3.0.2.

Is it normal?

**Comment by xoofx** [comment]
Yes, it should if you have enabled `Configuration.EnableObjectTracking`, this is the only way to get a stacktrace in a PCL assembly. Note that `Configuration.EnableObjectTracking` should be used only in debug scenarios.
Let me know if this is not the case.

**Comment by devdept2** [comment]
Yes I'm using that (in debug scenario)... but in previous version (2.6.3) it was not throwing all those exceptions

**Comment by xoofx** [comment]
Yes, because 2.6.3 was not PCL

**Comment by devdept2** [comment]
Thanks
