### ISSUE TITLE
DeviceContext1.ClearView()'s 'color' parameter is of type 'float' when it should be a 'RawColor4'.

### ISSUE THREAD

**Issue by waltdestler** [sharpdx/SharpDX#744]
The signature for `SharpDX.Direct3D11.DeviceContext1.ClearView` currently looks like this:

    public void ClearView(SharpDX.Direct3D11.ResourceView viewRef, float color, SharpDX.Mathematics.Interop.RawRectangle[] rectRef, int numRects)

However, that `color` parameter is supposed to be 4 floats, according to the [docs](https://msdn.microsoft.com/en-us/library/windows/desktop/hh404601(v=vs.85).aspx).

I tried fixing this myself by adding this line to `Mapping.xml`:

    <map param="ID3D11DeviceContext1::ClearView::Color" type="SharpDX.Mathematics.Interop.RawColor4" />

But this produces the following error:

    fatal: in CppInterface [ID3D11DeviceContext1]/Method void ID3D11DeviceContext1::ClearView([In] ID3D11View* pView,[In] const SharpDX.Mathematics.Interop.RawColor4* Color,[In, Buffer, Optional] const RECT* pRect,[In] unsigned int NumRects) Unknown type found [SharpDX.Mathematics.Interop.RawColor4]

So I'm stumped on how to fix this. I'm happy to fix it myself and submit a pull request, but I need a tip on how to get the code generator to work.

**Comment by xoofx** [comment]
Use the type `SHARPDX_VECTOR4` as [here](https://github.com/sharpdx/SharpDX/blob/e4e820ea5d1fcd98fe4199be299b5de4831d6758/Source/Mapping.Direct3D1x.xml#L399). The type is expected to be a C++ type, not a C# type. 

They are rebinded to C# type via the [default mappings](https://github.com/sharpdx/SharpDX/blob/e4e820ea5d1fcd98fe4199be299b5de4831d6758/Source/SharpDX/Mapping-core.xml#L525).

**Comment by andrewst** [comment]
<map param="ID3D(\d+)DeviceContext1::ClearView::Color" type="SHARPDX_COLOR4" pointer="*" array="0"/>
