### ISSUE TITLE
No way to get status code from SwapChain(X).Present?

### ISSUE THREAD

**Issue by waltdestler** [sharpdx/SharpDX#746]
[`IDXGISwapChain::Present`](https://msdn.microsoft.com/en-us/library/windows/desktop/bb174576(v=vs.85).aspx) can return the non-error status code [`DXGI_STATUS_OCCLUDED`](https://msdn.microsoft.com/en-us/library/windows/desktop/cc308061(v=vs.85).aspx) when the game window is not visible. (This is especially useful when paired with [`DXGI_PRESENT_TEST`](https://msdn.microsoft.com/en-us/library/windows/desktop/bb509554(v=vs.85).aspx).)

But unless I'm missing something, I see no way of getting this status code in SharpDX (It's not an error, so SharpDX won't throw an exception for it), even though there's already an existing `DXGIStatus` enum.

What's the best API design for getting this status code? Just return it from `Present`? I can look into making the desired API change myself, once I know what that desired change is and that there's no existing way to get the status code.

**Comment by xoofx** [comment]
Try by adding the property `hresult='true'` to the xml mapping on the DXGI.SwapChain.Present method. This will require a PR after. Thanks!
