### ISSUE TITLE
SharpDX.MediaFoundation.DirectX is not part of build.

### ISSUE THREAD

**Issue by camkego** [sharpdx/SharpDX#748]
Please forgive me if the reasons for why this is not part of the build is obvious, but it is not clear to me.

I am porting some code related to video acceleration, and I would like to support those
that are on older platforms (Dx9), because it seems much of the working world is stuck on older operating systems, such as Win7.

I need the following to port my code:
IDirectXVideoAccelerationService / SharpDX.MediaFoundation.DirectX.VideoAccelerationService

But it is clearly not included in the current 3.0.2 build, and doesn't compile when included.

Could someone in the know estimate if I dig into this whether it will be simple or complex to bring this into the build in a working form?

Thank you

**Comment by xoofx** [comment]
Hm, I think this was removed as part of the 3.0.0 refactoring/cleanup. You would have to use the older 2.6.x release to use this...

**Comment by camkego** [comment]
Alexandre,
Would you be able to provide some guidance on how I would add these back into the 3.0.x codebase?
\SharpDX.MediaFoundation\DirectX\*.cs

**Comment by xoofx** [comment]
- Clone 2.6.3 branch
- Build it
- Extract the files from `Generated\DirectX\*.cs` and copy them back to the the 3.0.x branch
- Look at the commit c6d8e457a3c4b9c4af6b0bfc41817e45601e2787 to backport any stuffs that was removed related to Direct3D9 interop. There could be other commits related to Multimedia branch

**Comment by camkego** [comment]
Alexandre,
Thank you.
If I do that and getting it working well, and implement any clean-ups as requested by you,
would you possibly consider a Pull Request for 3.0.4 [or other] to add the MediaFoundation.DirectX for 9 support back in?

**Comment by xoofx** [comment]
For Desktop there should be hopefully no problem, so sure, a PR will be welcome

**Comment by xoofx** [comment]
This is fixed by PR #762
