### ISSUE TITLE
SharpDXException while creating Device

### ISSUE THREAD

**Issue by Reaw** [sharpdx/SharpDX#756]
Hello! I have a big problem with starting with pure SharpDX. Any example for SharpDX is not working for me, the program stops running and it throws SharpDXException HRESULT: [0x887A0001], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_INVALID_CALL/InvalidCall], Message: Unknown.

Someone told me that it is happening because my hardware could not support DirectX11 - but It does, my NVidia GeForce GTX750Ti and my Windows 7 64 bit also supports it and even turning  down the FeatureLevel written below to '9' doesn't change anything

I really don't know what can I do with that exception it is always at this code snippet (Device11.CreateWithSwapChain):

```
public SharpDevice(RenderForm form, bool debug = false)
        {
            View = form;
            // SwapChain description
            var desc = new SwapChainDescription()
            {
                BufferCount = 1,//buffer count
                ModeDescription = new ModeDescription(View.ClientSize.Width, View.ClientSize.Height, new Rational(60, 1), Format.R8G8B8A8_UNorm),//sview
                IsWindowed = true,
                OutputHandle = View.Handle,
                SampleDescription = new SampleDescription(1, 0),
                SwapEffect = SwapEffect.Discard,
                Usage = Usage.RenderTargetOutput
            };
            FeatureLevel[] levels = new FeatureLevel[] { FeatureLevel.Level_11_0 };

            //create device and swapchain
            DeviceCreationFlags flag = DeviceCreationFlags.None | DeviceCreationFlags.BgraSupport;
            if (debug)
                flag = DeviceCreationFlags.Debug;

                Device11.CreateWithSwapChain(SharpDX.Direct3D.DriverType.Hardware, flag, levels, desc, out _device, out _swapchain);
//...
```
I'm also getting this Exception on the same line in your sample of using this Device https://github.com/sharpdx/SharpDX-Samples/blob/master/Desktop/Direct3D11/MiniTri/Program.cs

I would be very grateful for helping with this problem.
Regards

**Comment by xoofx** [comment]
You should have a precise debug log of the DXGI error in the Visual Studio output debugger, if you 
- run the device with Debug flag 
- "Enable native code debugging" in your .NET project.

**Comment by Reaw** [comment]
Ok, I've done that, but I've only received a message which is similar to the last one.
"An unhandled exception of type 'SharpDX.SharpDXException' occurred in SharpDX.dll

Additional information: HRESULT: [0x887A0001], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_INVALID_CALL/InvalidCall], Message: Unknown"

**Comment by xoofx** [comment]
Have you installed the [DirectX June 2010 SDK](https://www.microsoft.com/en-us/download/details.aspx?id=6812) on Windows 7 at least? You won't get any debug if it is not installed...

Also try to remove `FeatureLevel[] levels = new FeatureLevel[] { FeatureLevel.Level_11_0 };` and `DeviceCreationFlags.BgraSupport` to make sure.
(I suspect a notebook with dual GPU (Optimus?) which is not using the best one)

**Comment by Reaw** [comment]
@xoofx 
I'm trying to install this SDK, but I have some issues like S1023 error, but uninstalling the Microsoft Visual C++ Redistruable 2010 and newer doesnt work. I will have to figure out what to do :(

**Comment by Reaw** [comment]
Ok, I have installed this SDK on my PC, but I still cannot run those projects.
What to do?

**Comment by jegor377** [comment]
It does not work for me too. [screen1](http://i.imgur.com/0u17t1Q.png) [screen2](http://i.imgur.com/ySKhPLL.jpg)

I've got Windows 10 Pro and Invidia geforce gt 610.

**Comment by Gavin-Williams** [comment]
@jegor377 Can I suggest you make a new thread for your issue. They are probably not the same, and it might get confusing responding to both of you here.

**Comment by xoofx** [comment]
@Reaw if even the sample MiniTri is failing without modifying it, I really don't see what's wrong. This is a standard Direct3D11 code. If you just develop a simple C++ App calling the same function, you should have the same error. So unlikely a SharpDX issue.

**Comment by Reaw** [comment]
Well...
The samples from DirectX SDK (Direct3D11) in C++ are working properly.
In SlimDX I had also exception while creating Device, it was called Direct2DException, but installing SlimDX SDK solved the problem.

**Comment by xoofx** [comment]
@Reaw I don't have any clue

**Comment by Reaw** [comment]
It's sad.
I thought this is the only place where I could find a solution :(

**Comment by DavidoesW** [comment]
I also have this problem :/

**Comment by andrewst** [comment]
In windows 10 must be active "Graphics Tools" feature.
https://msdn.microsoft.com/en-us/library/windows/apps/mt210797.aspx

**Comment by Reaw** [comment]
@andrewst 
And what with Windows 7 64bit ?

**Comment by andrewst** [comment]
I think this page help you
http://stackoverflow.com/questions/25423371/d3d11createdevice-returns-garbage-value-and-fails?answertab=votes#tab-top

**Comment by Reaw** [comment]
@xoofx 
I'm so happy. I have found a solution.
Something is wrong with SharpDX on nuget.
I have downloaded the package from the website of SharpDX and everything worked from that package.
I think now this thread can be closed ;d

**Comment by xoofx** [comment]
@Reaw good if your problem is solved.

FYI, I have made an assembly diff between the NuGet version and the zip version and they are strictly equivalent (I just checked SharpDX, DXGI and Direct3D11 assemblies), so the problem was most likely somewhere else.

**Comment by Alan-FGR** [comment]
I'm having this problem in a single machine here... latest 4.2.0 from nuget, redownloaded multiple time to make sure it's not corrupted somehow, I develop DirectX stuff here (Win SDK) from C++ and it works fine, MiniTri fails at CreateWithSwapChain with `SharpDX.SharpDXException: 'HRESULT: [0x887A0001], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_INVALID_CALL/InvalidCall], Message: Unknown'`.
