### ISSUE TITLE
What do I have to reference to get a Vector3?

### ISSUE THREAD

**Issue by beppe9000** [sharpdx/SharpDX#759]
What is the absolute namespace for `Vector3` ? I am following a tutorial that uses that class but I can't find it anywhere. Is the `SharpDX.Mathematics.Interop.RawVector3` the same as a `Vector3`?

**Comment by Gavin-Williams** [comment]
SharpDX.Vector3 is what you want. The RawVector3 .. well .. it deals with problems with C# i guess.

**Comment by beppe9000** [comment]
What is the assembly that I have to reference? I installed the following Nuget packages but VS says that there is no `SharpDX.Vector3` when I try to declare a `Vector3`...

```
Id                                  Versions
--                                  --------
SharpDX                             {3.0.2}
SharpDX.D3DCompiler                 {3.0.2}
SharpDX.Desktop                     {3.0.2}
SharpDX.Direct3D11                  {3.0.2}
SharpDX.Direct3D12                  {3.0.2}
SharpDX.DXGI                        {3.0.2}
```

**Comment by beppe9000** [comment]
Fixed by installing the `SharpDX.Mathematics` Nuget package. I didn't expect this package to exist because the `SharpDX.Mathematics.Interop.RawVector3` class was accessible without installing it.

**Comment by Gavin-Williams** [comment]
Oh ok, so to clarify; the reference / package to include is SharpDX.Mathematics but the namespace is SharpDX.

And also just to mention the 'raw types' again, they are a lightweight struct used at a lower level to enable 1:1 mapping of the struct data throughout the C++ part of SharpDX while still allowing a 'higher level' Vector, which can be implemented by your own libraries or in an engine, with all the bells and whistles. So you don't end up with two vector3 dependencies.

As stated by xoofx last year ..
"In the 3.0.0, raw types are used by all SharpDX/DirectX API to perform the interop with C++. They don't carry any methods and are lightweight structs. That way a higher level API like Paradox or MonoGame can perform directly conversion to these raw types without having to reference  SharpDX.Mathematics . The  SharpDX.Mathematics  is just here to keep the samples working and is directly tied-up with SharpDX raw types to make conversion transparent to raw types."

**Comment by QuantumDeveloper** [comment]
@Gavin-Williams 
So, I can use Vectors from System.Numerics.Vectors assembly, but for that I need to make my own tiny wrapper, I suppose, To have implicit or explicit convertions to RawVector types. Also I am wondering is Vectors from System.Numerics could be passed to the shader without any additional mapping or something else?
