### ISSUE TITLE
Swap chain with Format other than R8G8B8

### ISSUE THREAD

**Issue by Gavin-Williams** [sharpdx/SharpDX#763]
Hi,

I can only make swapchains with 24 bit color (8 bits per channel, R8G8B8A8_UNorm), is that expected ? If i try 48 bit color (16 bits per channel, R16G16B16A16_UNorm), or 96 bit color (32 bits per channel, R32B32G32A32_Float) the swap chain creation fails. 

I've read that HDR displays can render 16 bits per channel, so I would at least expect R16G16B16A16_UNorm to work.

The wiki for color depth reads :

"The HDMI 1.3 specification defines bit depths of 30 bits (1.073 billion colors), 36 bits (68.71 billion colors), and 48 bits (281.5 trillion colors).[16] In that regard, the Nvidia Quadro graphics cards manufactured after 2006 support 30-bit deep color[23] as do some models of the Radeon HD 5900 series such as the HD 5970.[24][25] The ATI FireGL V7350 graphics card supports 40-bit and 48-bit color.[26]

The DisplayPort specification also supports color depths greater than 24 bpp.

At WinHEC 2008, Microsoft announced that color depths of 30 bits and 48 bits would be supported in Windows 7, along with the wide color gamut scRGB (which can be converted to xvYCC output).[27][28]"

Can anyone explain why it's not working ?

**Comment by xoofx** [comment]
Not really related to SharpDX directly, so you will have maybe more luck on [gamedev/DirectX](http://www.gamedev.net/forum/10-directx-and-xna/) forum

**Comment by Gavin-Williams** [comment]
Ok, thank you.
