### ISSUE TITLE
All Generated LocalInterop.cs files throwing NotImplementedException()

### ISSUE THREAD

**Issue by zcanann** [sharpdx/SharpDX#766]
SharpDX v3.0.2

When I use the nuget package, I can easily do things like:
DirectInput  directInput = new DirectInput();

However when compiling from source, almost all calls to any project under SharpDX (Direct3D9, RawInput, Direct3D12, etc) will fail because every single generated function in LocalInterop.cs simply throws a NotImplementedException.

Am I missing something in the build process?

**Comment by andrewst** [comment]
It's normal. 
In postbuild SharpCli.exe IL-code replaced.

**Comment by zcanann** [comment]
Got it, thanks
