### ISSUE TITLE
SharpDX.Mathematics/Matrix.cs - perspective view matrix calculation seems wrong 

### ISSUE THREAD

**Issue by jsidd** [sharpdx/SharpDX#783]
I have been porting the software render tutorials series from Microsoft to SDL2, 
(https://www.davrous.com/2013/06/13/tutorial-series-learning-how-to-write-a-3d-soft-engine-from-scratch-in-c-typescript-or-javascript/) and using SharpDX code, and I think this led me  to find a bug in: [SharpDX.Mathematics/Matrix.cs](url)

 (I tried the last two file historical versions and I observed the same behavior) 

This method: void PerspectiveFovRH(float fov, float aspect, float znear, float zfar, out Matrix result)

Basically I noticed that my model or mesh would always render upside down.

In my own code is what I ended up using: 

` 

Matrix4* ComputeFOVProjection( double fov, double aspect, double nearDist, double farDist, bool leftHanded)
{
    
    Matrix4* result = new Matrix4();
    result->m11 = 1.0;
    result->m22 = 1.0;
    result->m33 = 1.0;
    result->m44 = 1.0;

    if ( fov <= 0 || aspect == 0 )
    {
        assert( fov > 0 && aspect != 0 );
        return result;
    }

    double frustumDepth = farDist - nearDist;
    double oneOverDepth = 1 / frustumDepth;

    result->m22 = 1 / tan(0.5f * fov);
    result->m11 = (leftHanded ? 1 : -1 ) * result->m22 / aspect;
    result->m33 = farDist * oneOverDepth;
    result->m43 = (-farDist * nearDist) * oneOverDepth;
    result->m34 = 1;
    result->m44 = 0;
    return result;

}`

found here:
http://stackoverflow.com/questions/18404890/how-to-build-perspective-projection-matrix-no-api

**Comment by xoofx** [comment]
Your formula is equivalent to the PerspectiveFovLH only when leftHanded is true, otherwise it is invalid, the StackOverflow method is most likely invalid for RH.

Just check with [PerspectiveFovRH on msdn](https://msdn.microsoft.com/en-us/library/windows/desktop/bb281728(v=vs.85).aspx), it should be the same formula used in SharpDX

**Comment by jsidd** [comment]
@xoofx Ok, I see what you mean. Thank you for checking. The Soft Engine tutorial series seems to work better for LH so I am only going to use that formula for LH.  The C# version of the Soft Engine  tutorials code which uses SharpDX actually mixes LH and RH but that seems to be a mistake there. Thanks again.
