### ISSUE TITLE
WIC MetadataQueryWriter throwing an exception "Type [Byte] is not handled"

### ISSUE THREAD

**Issue by Tape-Worm** [sharpdx/SharpDX#787]
Using SharpDX 3.0.2 on Nuget

I'm attempting to write out a metadata item (/grctlext/Disposal for animated GIF files), which requires a VT_UI1 variant type (which I'm using a byte type for), and when I do this my code crashes with the exception mentioned above.

I've tracked the problem down to the Value property setter in SharpDX/Win32/Variant.cs. Basically, the setter does not have a check for byte types and as such, the exception is thrown.

**Comment by jkoritzinsky** [comment]
Fixed by #855
