### ISSUE TITLE
Screen capture has black bars for non native resolutions

### ISSUE THREAD

**Issue by MatthewFrench** [sharpdx/SharpDX#789]
Black bars appear on the left or top when the resolution is not native to the monitor when capturing the screen.

**Comment by xoofx** [comment]
Sorry, I'm closing this issue as It does not seem related to a bug in SharpDX.

**Comment by MatthewFrench** [comment]
Would you classify it as a bug in the technologies that SharpDX uses?

**Comment by xoofx** [comment]
Likely, or a wrong usage of it. The screen capture API in SharpDX is just a thin wrapper (generated automatically) calling directly the underlying API.
