### ISSUE TITLE
Access cbuffer in header from effect (Toolkit)

### ISSUE THREAD

**Issue by QuantumDeveloper** [sharpdx/SharpDX#792]
Hi.
I know, that toolkit is deprectaed, but I wish to know is it actually possible to reach some cbuffer defined in header file, which was included in fx file?
And if yes, then how I can do that? Because now effect file after compilation does not contains any variables from header file.

**Comment by xoofx** [comment]
Could you ask this to the [Toolkit repo](https://github.com/sharpdx/Toolkit/issues)?
