### ISSUE TITLE
HRESULT: [0x80004002], Module: [General], ApiCode: [E_NOINTERFACE/No such interface supported], Message: Interfaz no compatible

### ISSUE THREAD

**Issue by Aismel** [sharpdx/SharpDX#795]
Hi,

I try to capture a picture from my game and tell me that...!

Any idea what happend...

Thx for advance...

**Comment by xoofx** [comment]
Closing this issue as this is not a bug in SharpDX but more likely an incorrect usage of the API, unless proven otherwise.
