### ISSUE TITLE
Direct2D: No support for command lists?

### ISSUE THREAD

**Issue by Levia-** [sharpdx/SharpDX#800]
Direct2D1.DeviceContext should according to MSDN contain CreateCommandList
(https://msdn.microsoft.com/en-us/library/windows/desktop/hh404479(v=vs.85).aspx)

Is it possible to use command lists on D2D1 on DX11?

**Comment by andrewst** [comment]
You can use
`var commanList = new CommandList(deviceContext);`

**Comment by Levia-** [comment]
How do you execute it after, D2D1 DeviceContext does not have ExecuteCommandList?

**Comment by andrewst** [comment]
Please read msdn.
https://msdn.microsoft.com/en-us/library/windows/desktop/hh404392(v=vs.85).aspx
Example:
```csharp
var commanList = new CommandList(deviceContext);
deviceContext.DrawImage(commandList);
```
or
```csharp
var commanList = new CommandList(deviceContext);
deviceContext.Target = commandList
pD2D1DeviceContext->BeginDraw();
...
pD2D1DeviceContext->EndDraw();;
```

**Comment by Levia-** [comment]
Thanks, I must've missed the correct way to use it in D2D in the docs.
