### ISSUE TITLE
Displaying web content in a DirectX

### ISSUE THREAD

**Issue by ASantos007** [sharpdx/SharpDX#808]
I am new in DirectX and I'm a little bit lost.

What I would like to do is:
-	Show a web page using any browser (Chrome?) but within a DirectX app.

Is it possible to do that?

**Comment by xoofx** [comment]
Sorry, this is out of the scope of SharpDX. I don't think that Chrome provides even such a feature (as it is multiprocess, not suitable to integrated into another app like a browser control)
