### ISSUE TITLE
Update to latest SDK version (10.0.14393.0)

### ISSUE THREAD

**Issue by QuantumDeveloper** [sharpdx/SharpDX#811]
Is it possible to update mapping to SDK version 10.0.14393.0 which came with latest VS update and release a nuget package?

**Comment by xoofx** [comment]
Is there anything worthwhile new?

**Comment by QuantumDeveloper** [comment]
Yeah, I think so.
Here is link on MSDN, where describes new features of the latest Windows SDK after update WIn 10 to the version 1607:
https://msdn.microsoft.com/library/windows/desktop/mt748631(v=vs.85).aspx

So, maybe it is worth to update to the latest SDK version.

**Comment by xoofx** [comment]
Could you try a PR for that?

**Comment by QuantumDeveloper** [comment]
Unfortunately I am not familiar with all that mapping stuff and don`t know how it works. So, I am afraid I could not upgrade to new SDK version correctly. 
Maybe this could be done by someone who is more experienced in this question?

**Comment by amerkoleci** [comment]
I will try to update this and send PR back.

**Comment by amerkoleci** [comment]
Just submitted PR, see #815

**Comment by QuantumDeveloper** [comment]
Thanks a lot!!!
