### ISSUE TITLE
I can't find Viewport in the latest version of SharpDX

### ISSUE THREAD

**Issue by wky2014** [sharpdx/SharpDX#816]
I'm now using SharpDX 3.1.0, there seems to be missing the SharpDX.Viewport which originally had but there is a SharpDX.Mathematics.Interop.RawViewport. Are these the same? And please publish an official reference and keep them updated or it would be getting pretty confusing.

**Comment by QuantumDeveloper** [comment]
As I can see Vieport is still there:
https://github.com/sharpdx/SharpDX/blob/8dc1f64a9424c6b0dc8b9009f70e144ded03f1d7/Source/SharpDX.Mathematics/ViewportF.cs

**Comment by xoofx** [comment]
Use `SharpDX.Mathematics` assembly

**Comment by wky2014** [comment]
I see, I didn't install the mathematics package. Thank you guys.How many nuget packages should I install for the program? Is there a list?
