### ISSUE TITLE
There is а bug in Direct3D9.D3DX.OptimizeVertices

### ISSUE THREAD

**Issue by DIMOSUS** [sharpdx/SharpDX#817]
D3DX.cs in line number 312
`var faces = new int[faceCount];`
need
`var faces = new int[vertexCount];`

**Comment by xoofx** [comment]
PR?

**Comment by DIMOSUS** [comment]
I'm sorry, I did not catch you

**Comment by xoofx** [comment]
Can you make a fix via a Pull Request?

**Comment by DIMOSUS** [comment]
Yes, it can be closed?
