### ISSUE TITLE
DirectComposition: PCL

### ISSUE THREAD

**Issue by prasannavl** [sharpdx/SharpDX#819]
`DirectComposition` package should be allowed the same PCL profile as D3D11 and D2D1. It can be used form UWP. Currently, its only `net45`.

**Comment by xoofx** [comment]
afaik, `DirectComposition` is not allowed/accessible on UWP (check [this](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/dba0e184-662f-4459-b5e2-0876c3be9d7b/uwp-universal-apps-and-directcomposition-windows-composition-engine?forum=wpdevelop)) unless things changed in the meantime.

**Comment by prasannavl** [comment]
Ah. My bad. Sorry about that.
