### ISSUE TITLE
Can't compile under VS2015

### ISSUE THREAD

**Issue by boatschl** [sharpdx/SharpDX#823]
Hi,

I am having issues compiling under VS2015 @Windows 10. I already found two other (resolved) issues about this here (had to install the Win 8 Tools) and followed the steps mentioned there to no avail.

Checking the VS2015 features installed I have:
 - Visual C++ --> everything 
 - Universal WIndows App Dev Tools --> Windows 10 SDK (10.0.10586) + Windows 10 SDK (10.0.10240)
 - Windows 8.1 and Phone Tools --> everything
 - .NET stuff 4.0 onwards (no legacy 2.0 since this cannot be installed under WIndows 10).
I am using Win10 (obviously) and only have VS2010 installed in addition to the '15 version.

I can build the SharpDX tools without errors, but once I turn to build the SharpDX.csproj I am getting a window saying "A fatal error occured". Here are the first few lines from the console (Release as well as Debug):

4>  SharpGen(1,1): info:Loading config files...
4>  SharpGen(1,1): info:Assembly [D:\devel\SharpDX-master\Source\Tools\SharpGen\Bin\Debug\SharpGen.exe] changed. All files will be generated
4>  SharpGen(1,1): info:Starting code generation...
4>  SharpGen(1,1): info:Starting code generation...
4>  SharpGen(1,1): info:Config files changed.
4>  SharpGen(1,1): info:Parsing C++ headers starts, please wait...
4>  SharpGen(1,1): info: in gccxml Path used for gccxml [-I"D:\devel\SharpDX-master\Source\Tools\SharpGen\Bin\Debug"]
4>  SharpGen(1,1): info: in gccxml Path used for gccxml [-I"D:\devel\SharpDX-master\Source\SharpDX.Direct3D11\..\..\External\Effects11\Inc"]
4>  SharpGen(1,1): info: in gccxml Path used for gccxml [-I"D:\devel\SharpDX-master\Source\SharpDX.Direct3D11.Effects\..\..\External\Effects11\Inc"]
4>  SharpGen(1,1): info: in gccxml Path used for gccxml [-iwrapper"D:\devel\SharpDX-master\Source\..\External\gccxml\share\gccxml-0.9\vc12\overrides\shared"]
4>  SharpGen(1,1): info: in gccxml Path used for gccxml [-iwrapper"D:\devel\SharpDX-master\Source\..\External\gccxml\share\gccxml-0.9\vc12\overrides\um"]
4>  SharpGen(1,1): info: in gccxml Path used for gccxml [-iwrapper"D:\devel\SharpDX-master\Source\..\External\gccxml\share\gccxml-0.9\vc12\overrides"]
4>  SharpGen(1,1): info: in gccxml Path used for gccxml [-I"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\Include"]
4>  SharpGen(1,1): info: in gccxml Path used for gccxml [-I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared"]
4>  SharpGen(1,1): info: in gccxml Path used for gccxml [-I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um"]
4>   --gccxml-config "..\..\..\..\..\External\gccxml\bin\..\share\gccxml-0.9\vc12\gccxml_config" -E --gccxml-gcc-options gccxml_preprocess_sharpdx_options.txt -I"D:\devel\SharpDX-master\Source\Tools\SharpGen\Bin\Debug" -I"D:\devel\SharpDX-master\Source\SharpDX.Direct3D11\..\..\External\Effects11\Inc" -I"D:\devel\SharpDX-master\Source\SharpDX.Direct3D11.Effects\..\..\External\Effects11\Inc" -iwrapper"D:\devel\SharpDX-master\Source\..\External\gccxml\share\gccxml-0.9\vc12\overrides\shared" -iwrapper"D:\devel\SharpDX-master\Source\..\External\gccxml\share\gccxml-0.9\vc12\overrides\um" -iwrapper"D:\devel\SharpDX-master\Source\..\External\gccxml\share\gccxml-0.9\vc12\overrides" -I"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\Include" -I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um" sharpdx-root.h
4>SharpGen(1,1): warning : in gccxml In file included from sharpdx.h:2,
4>SharpGen(1,1): warning : in gccxml                  from sharpdx-root.h:29:
4>D:\devel\SharpDX-master\Source\SharpDX\sharpdx-core.h(2,24): error : in gccxml  objidlbase.h: No such file or directory
4>D:\devel\SharpDX-master\Source\SharpDX\sharpdx-core.h(3,20): error : in gccxml  wtypes.h: No such file or directory
4>D:\devel\SharpDX-master\Source\SharpDX\sharpdx-core.h(4,22): error : in gccxml  winerror.h: No such file or directory
4>SharpGen(1,1): warning : in gccxml In file included from sharpdx.h:3,
4>SharpGen(1,1): warning : in gccxml                  from sharpdx-root.h:29:
4>D:\devel\SharpDX-master\Source\SharpDX\sharpdx-core-direct3d.h(2,23): error : in gccxml  d3dcommon.h: No such file or directory
4>D:\devel\SharpDX-master\Source\SharpDX\sharpdx-core-direct3d.h(3,21): error : in gccxml  d3d10_1.h: No such file or directory
4>D:\devel\SharpDX-master\Source\SharpDX\sharpdx-core-direct3d.h(4,19): error : in gccxml  d3d10.h: No such file or directory

...and so forth for a couple hundred more include files.

Help would be greatly appreciated!

**Comment by xoofx** [comment]
as stated in the readme, you need 10.0.14393.0 (which should be part of VS 2015 Update 3)

**Comment by boatschl** [comment]
I updated my Windows 10 to 14393, still does not work:
http://imgur.com/a/H9zjB
Any more thoughts?

**Comment by xoofx** [comment]
You are getting exactly the same errors? Because above it was saying that the directory `C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um` was not containing files like `d3d10_1.h`
