### ISSUE TITLE
Swapchain presentation freezing issue

### ISSUE THREAD

**Issue by QuantumDeveloper** [sharpdx/SharpDX#824]
Hi. I found that when creating Swapchain with `swapEffect = discard`, then dispose it and create new swapchain with `swapEffect = flipsequental`, then dispose it and create again swapchain with `swapeffect = discard`, It will stop presenting anything on the screen and will be no error. 
Image just stop updating. But if I create new swapchain with `swapEffect = flipsequental`, presenting starts working again, but from that moment you cannot see anything if you create swapchain with `discard` effect during current lifecycle.
Seems this issue causing only for `discard -> flipsequental -> discard` sequence.
Could someone say is this by design?

I have tested this on 3.1.1 and also on 3.0.2. Issue is reproducible on both versions.

**Comment by xoofx** [comment]
I don't know, you should ask this on a DirectX forum (though not sure you will find many people doing this)
