### ISSUE TITLE
Direct2D1 WIC.BitmapDecoder dds

### ISSUE THREAD

**Issue by sjc1832** [sharpdx/SharpDX#827]
I get the following error when trying to load a dds file with BitmapDecode.

Additional information: HRESULT: [0x88982F50], Module: [SharpDX.WIC], ApiCode: [WINCODEC_ERR_COMPONENTNOTFOUND/Componentnotfound], Message: Unknown

I have tried both of these calls:

wicBitmapDecoder = new WIC.BitmapDecoder(wicImagingFactory, WIC.BitmapDecoderGuids.Dds);

wicBitmapDecoder = new WIC.BitmapDecoder(wicImagingFactory, filename, SharpDX.IO.NativeFileAccess.Read, WIC.DecodeOptions.CacheOnLoad);

where filename = some .dds file.

I have tried numerous .dds files and both windows 7 and 10.  Jpeg and tif work fine.

I'm using 3.1.1 version of the sharpdx libraries.

**Comment by xoofx** [comment]
It is not a bug in SharpDX but WIC limitation. See [msdn documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/dn424129%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396):

> However, the WIC DDS codec only supports decoding and encoding files containing the following formats:
> 
> * DXGI_FORMAT_BC1_UNORM
> * DXGI_FORMAT_BC2_UNORM
> * DXGI_FORMAT_BC3_UNORM

**Comment by sjc1832** [comment]
I read that too but the first call should not fail with BitmapDecoderGuids.Dds I'm not passing a file for that call. I tested both calls independently and they  both fail with same error.

Thanks for your help.

Sent from my iPhone

On Nov 21, 2016, at 10:09 PM, Alexandre Mutel <notifications@github.com<mailto:notifications@github.com>> wrote:


It is not a bug in SharpDX but WIC limitation. See msdn documentation<https://msdn.microsoft.com/en-us/library/windows/desktop/dn424129%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396>:

However, the WIC DDS codec only supports decoding and encoding files containing the following formats:

  *   DXGI_FORMAT_BC1_UNORM
  *   DXGI_FORMAT_BC2_UNORM
  *   DXGI_FORMAT_BC3_UNORM

**Comment by xoofx** [comment]
As the code is automatically generated, the only thing you can check is whether this is working in C++. If yes, then there is a problem in SharpDX mapping.
