### ISSUE TITLE
GdiInteropRenderTarget.GetDC() System.AccessViolationException

### ISSUE THREAD

**Issue by KingSora** [sharpdx/SharpDX#832]
Hello!

I'm getting a `System.AccessViolationException` if I try to call the GetDC() method from a `GdiInteropRenderTarget` object.

My code:

```
D3D10.Texture2D texture = new D3D10.Texture2D(d3d1Device, d3dTextureDescription);

DXGI.Surface textureSurface = texture.AsSurface();

D2D.RenderTarget renderTarget = new D2D.RenderTarget(d2dFactory, textureSurface, renderTargetProperties);

renderTarget = new D2D.BitmapRenderTarget(renderTarget, D2D.CompatibleRenderTargetOptions.GdiCompatible, renderTargetProperties.PixelFormat);

D2D.GdiInteropRenderTarget gdiTarget = new D2D.GdiInteropRenderTarget(renderTarget.NativePointer);

renderTarget.BeginDraw();
//...
gdiTarget.GetDC(D2D.DeviceContextInitializeMode.Copy); //System.AccessViolationException
```

Can anyone help me with this? I've the current version of SharpDX.

Best regards,
Sora

**Comment by xoofx** [comment]
You can't create a `D2D.GdiInteropRenderTarget gdiTarget = new D2D.GdiInteropRenderTarget(renderTarget.NativePointer);`, you are not supposed to you native COM pointer directly unless you know which object you are passing.

As specified on the [msdn documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/dd371321(v=vs.85).aspx), you need to `QueryInterface<GdiInteropRenderTarget>` on the renderTarget directly.

**Comment by KingSora** [comment]
Alright thanks! Its woring now :)
