### ISSUE TITLE
Cannot easily cast FontFileLoader to LocalFontFileLoader

### ISSUE THREAD

**Issue by corliss** [sharpdx/SharpDX#836]
The only way I'm able to successfully cast a `FontFileLoader` to a `LocalFontFileLoader` is by:

```
var ptr = ((SharpDX.CppObject)loader).NativePointer;
var localLoader = SharpDX.ComObject.QueryInterfaceOrNull<dw.LocalFontFileLoader>(ptr);

```
I didn't expect C#'s `as` to work, although that would have been nice.
Calling `ComObject.QueryInterface<dw.LocalFontFileLoader>(loader)` did not work either - it threw an exception.

Is this by design? It was sheer luck that I tried the working combination.

**Comment by xoofx** [comment]
The static method `ComObject.QueryInterface`  take an `Object` and not a `ComObject`, to under the wood, it will try to use the managed IUnknown associated to it, so it won't use the .NativePointer (which is the real COM ptr)

I guess the method you should use in your case is `loader.QueryInterface<LocalFontFileLoader>()`
