### ISSUE TITLE
How can I use SharpDX with the Framework v4.0?

### ISSUE THREAD

**Issue by jalil1408** [sharpdx/SharpDX#846]
How can I use SharpDX with the Framework v4.0?

**Comment by discosultan** [comment]
One way is to use a SharpDX version prior to 3.x.x.

For example, [SharpDX 2.6.3](https://www.nuget.org/packages/SharpDX/2.6.3). Note that it's missing APIs for Direct3D12.

**Comment by jalil1408** [comment]
Thank you @discosultan  I want to use the RawInput API to handle input from multiple keyboards (Tell which keyboard send the key) but seemingly it does not support this feature!

**Comment by xoofx** [comment]
Latest pre-release version of SharpDX (4.0.0+) have reintroduced support for 4.0
