### ISSUE TITLE
Consider providing pre-release NuGet packages

### ISSUE THREAD

**Issue by vanka78bg** [sharpdx/SharpDX#851]
The most common way to use SharpDX for many of us is as a NuGet package. Sometimes a bug gets fixed, but we have to wait a few months for a new NuGet package. As a temporary solution, one can build the library from the sources and switch to these custom DLLs, until the next NuGet package arrives. A better approach would be to provide pre-release NuGet packages on a regular basis, so that people who need the latest fixes and improvements can get them via NuGet.

**Comment by jkoritzinsky** [comment]
I'm very interested in this! One of my projects is currently blocked on the features I added to SharpDX with my pull requests a few weeks ago.

**Comment by xoofx** [comment]
I will try to bring this with appveyor

**Comment by xoofx** [comment]
This is fixed. Now whenever there is a merge happening on master, a pre-release of the next version is pushed to NuGet (post fixed by -betaXXX with XXX the build number)
