### ISSUE TITLE
DXGI_ERROR_SDK_COMPONENT_MISSING/SdkComponentMissing when in ARM target

### ISSUE THREAD

**Issue by titof49** [sharpdx/SharpDX#858]
Hi,

I'm writting an uwp application using sharpdx nuget to add it to my project, but Under x86 it work fine but when targertting arm plateform it doesn't work.
target debug , arm , device

reference "SharpDX.DXGI" is present in the nuget reference in the project and work fine when in x86 target mode.

may be it misss Something, may you help me ?

Br,
Christophe

Exception	{SharpDX.SharpDXException: HRESULT: [0x887A002D], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_SDK_COMPONENT_MISSING/SdkComponentMissing], Message: The application requested an operation that depends on an SDK component that is missing or mismatched.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateDevice(Adapter adapter, DriverType driverType, DeviceCreationFlags flags, FeatureLevel[] featureLevels)
   at SharpDX.Direct3D11.Device..ctor(DriverType driverType, DeviceCreationFlags flags)
   at SDKTemplate.MainPage.SwapChainPanel_Loaded(Object sender, RoutedEventArgs e)}	System.Exception {SharpDX.SharpDXException}
		Handled	false	bool
		Message	"SharpDX.SharpDXException: HRESULT: [0x887A002D], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_SDK_COMPONENT_MISSING/SdkComponentMissing], Message: The application requested an operation that depends on an SDK component that is missing or mismatched.\r\n\r\n   at SharpDX.Result.CheckError()\r\n   at SharpDX.Direct3D11.Device.CreateDevice(Adapter adapter, DriverType driverType, DeviceCreationFlags flags, FeatureLevel[] featureLevels)\r\n   at SharpDX.Direct3D11.Device..ctor(DriverType driverType, DeviceCreationFlags "	string

**Comment by xoofx** [comment]
you could have searched `DXGI_ERROR_SDK_COMPONENT_MISSING` on google, and you would have found that there was already #495 that could solve your problem

**Comment by titof49** [comment]
ok sorry you are right:

 i changed         
    
using (D3D11.Device defaultDevice = new D3D11.Device(D3D.DriverType.Hardware, D3D11.DeviceCreationFlags.**Debug**))

using (D3D11.Device defaultDevice = new D3D11.Device(D3D.DriverType.Hardware, D3D11.DeviceCreationFlags.**None**))

i think the issue isd on the case to debug that not supported, may be need to activate Something in my Windows phone.

keep in touch, i'll past what i m doing with the project in private message, you will see:
 it's IOT style ;->
