### ISSUE TITLE
cannot add sharpdx.directx9 (.net framework) to a uwp project (.netcore)

### ISSUE THREAD

**Issue by titof49** [sharpdx/SharpDX#860]
i'm writting a Bluetooth ble application based on the uwp project based on the sdk Microsoft and adding sharpdx support.

the main issue is that i need to create the same application for Windows and for a Lumia 640.
(always waitting for surface phone). 

The problem is that the chip Inside have an adreno in directx 9.0
Adreno 305 : DirectX 9.0c. 

the issue is that sharp dx written for .net Framework and my application use .netcore.
so my application work fine on Windows when using directx 10.

but the shaders doesn't start on my phone (only directx 9.0), i downloaded the latest source from the sharpdx github but after building sharpdx.directx9 i cannot add reference to my project.

I tried nuget to add but doesn't work too.

Is there a solution to solve this point ?
Regards,
Christophe

**Comment by xoofx** [comment]
Direct3D9 is not authorized/supported on UWP

**Comment by titof49** [comment]
thank you for this quick response.

Br,
Christophe

**Comment by titof49** [comment]
just to see other possibilities:

i justchanged pixel shader and vertex to 

 //
            using (var vertexShaderByteCode = ShaderBytecode.CompileFromFile("vertexShader.hlsl", "main", "**vs_4_0_level_9_1",** ShaderFlags.None))
            {
                vertexShader = new D3D11.VertexShader(this.device,vertexShaderByteCode);
                inputSignature = new ShaderSignature(vertexShaderByteCode);
            }

            //
            using (var pixelShaderByteCode = ShaderBytecode.CompileFromFile("pixelShader.hlsl", "main", "**ps_4_0_level_9_1**", ShaderFlags.None))
            {
                pixelShader = new D3D11.PixelShader(this.device , pixelShaderByteCode);
            }

should it ork ?

**Comment by titof49** [comment]
ok, i found the issue, sorry for the error 
vs_4_0_level_9_1
ps_4_0_level_9_1

and 
using (D3D11.Device defaultDevice = new D3D11.Device(D3D.DriverType.Hardware, D3D11.DeviceCreationFlags.None))

**Comment by titof49** [comment]
thanks to visual studio 2017 to help to find the issue ;->
