### ISSUE TITLE
SharpDX.Direct3D9 is missing in build 4.0.0-ci121

### ISSUE THREAD

**Issue by SergeyBaryshev** [sharpdx/SharpDX#873]
Sorry for my mistakes in my English, it is not my native language (hope you understand).

Hello everyone, especially SharpDX team!
Today I updated Nuget Packages to latest preview builds of SharpDX, and Direct3D9 is not exist in package folder. So my solution has hundreds errors with missing references to it. Moreover, accidentally there is file "SharpDX.DirectComposition.dll" I think (because it is separate library in Nuget download center). I tried several times to rollback to stable version 3.1.1 and update it again to 4.0.0-ci121. Every time same thing. So, is it on my side or is it a bug?

With regards to Developers!

**Comment by xoofx** [comment]
What is the target .NET framework of your application? (cc @jkoritzinsky)

Currently, the pre release is only including assemblies for .NET 4.5, .NETCoreApp 1.0+ and .NETStandard 1.3, but I think we could reintroduce back some of the previous target as well (.NET 4.0 and/or PCL 4.0+)

**Comment by jkoritzinsky** [comment]
I found the issue: I forgot to update the metadata for the DirectComposition project so it's overwriting the Direct3D9 package. I'll fix it later today.

**Comment by SergeyBaryshev** [comment]
First of all, thanks for fast reply.
**xoofx**
I mostly use latest builds and versions of software:
Visual Studio 2017 Community Edition 15.1 (26403.0) - updated today also,
.NET Framework 4.6.2,
SharpDX 3.1.2-beta109 (until today).

So, no need to do extra work to support previous targets (it is only my opinion).

**jkoritzinsky**
Thank you for inspect the problem. I hope there is not hard to fix this.

**Comment by jkoritzinsky** [comment]
PR is already out to fix this. Just need xoofx to merge it!
