### ISSUE TITLE
Performance issues - Prerelease 4.0.0-ci124

### ISSUE THREAD

**Issue by h1cks** [sharpdx/SharpDX#875]
Trying to isolate a performance issue in the new pre-release.  Rechecked that it wasn't config on my old machine by reverting to 3.1.2-beta109.

At least every half a seconnd I get a 200ms frame rate spike in the new pre-release. Stepping through code doesn't seem to show the origin of the issue.  Will continue to investigate, but definitely found the issue was gone when reverting to 3.1.2 version.

Running this in Visual Studio 2017 Community Edition.

**Comment by xoofx** [comment]
Which API are you using? Are you sure that you have proper Dispose() on each SharpDX objects? This 200ms spike looks like a GC problem...  I'm not aware of a change in the API that would introduce this...

**Comment by h1cks** [comment]
I've got more of an update, just installed Ci141 and now spammed with alot of warnings to the console.

Warning: Live ComObject [0x215C280D320], potential memory leak:

Went back and installed ci124 and same thing has been happening.  I didnt have my output view viewable so i wasnt seeing all these.  Is this a new warning level?    Anyway of lowering the noise on this?  Or debugging exactly how to find why the warning is occurring?

Please close, I now know the source of the performance issue, its verbose warnings coming from the package.

**Comment by h1cks** [comment]
Also, the debug warnings dont appear if you just step through the code slowly.

**Comment by xoofx** [comment]
As you can see, this warning is coming from [ComObject.Dispose](https://github.com/sharpdx/SharpDX/blob/8dc1f64a9424c6b0dc8b9009f70e144ded03f1d7/Source/SharpDX/ComObject.cs#L291)

It depends on the default Configuration:
- `EnableReleaseOnFinalizer`: false by default. If true, it will allow ComObject to be automatically released by the finalizer.
- `EnableTrackingReleaseOnFinalizer`: true by default. If true, it will display the above warning if `EnableReleaseOnFinalizer` was false

The idea behind these switches is that SharpDX expects by default that you explicitly Dispose() all ComObjects. If you are getting a warning (without modifying the code), it means that you have an object that was not correctly disposed manually. 

You use `ObjectTracker` to find the original stacktrace of the allocated ComObject (`ObjectTracker.ReportActiveObjects()`). If the stacktrace is incomplete, you might try to provide your own stacktrace via `ObjectTracker.StackTraceProvider` (and use something like `new StackTrace(new StackFrame(true)).ToString()`

**Comment by h1cks** [comment]
Interesting, in 3.1.1 I assume this was less verbose.  Thanks for info.

**Comment by h1cks** [comment]
Well this is getting weird, I was dumping the objects out to a file.  

Im getting a number of references to the immediate context and the device being allocated.  This get's weirder.  I commented out my game logic, leaving an empty logic loop and render loop.  It still keeps leaking references, but im not running any code in the loop.

frame - 1326

Count per Type:
BlendState1 : 4
Buffer : 681
DepthStencilState : 2
DepthStencilView : 1
Device : 754
Device3 : 0
DeviceContext : 0
DeviceContext1 : 4
DeviceContext2 : 0
DeviceContext3 : 0
DirectInput : 0
DomainShader : 0
GeometryShader : 1
HullShader : 0
InfoQueue : 0
InputLayout : 7
Joystick : 0
Keyboard : 0
Output : 1
PixelShader : 9
RasterizerState1 : 1
RenderTargetView1 : 1
SamplerState : 13
ShaderResourceView1 : 7
SwapChain3 : 0
Texture2D1 : 1
VertexShader : 7

Frame 1838

**Comment by xoofx** [comment]
Again, it is unlikely a problem in SharpDX but solely in your code. Their are lots of objects that can be created without noticing (properties access, QueryInterface...etc.). With the ObjectTracker as described in the other issue, you should be able to recover where all these references are created.

**Comment by h1cks** [comment]
Actually I tracked the problem down and its when I use reflection to enquire on the object be it either device or context.

       for (int i = 0; i < list.Count; i++)
        {
                    SharpDX.Diagnostics.ObjectReference item = list[i];
                    string a = item.StackTrace;
                    if (item.Object.IsAlive)
                    {
                        object reference = item.Object.Target;
                        file.WriteLine(reference.ToString());

                        foreach (var prop in reference.GetType().GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.NonPublic))
                        {
                            try
                            {
                                string aa = prop.Name + " " + prop.GetValue(reference, null);
                                file.WriteLine(aa);
                            }
                            catch
                            {
                                file.WriteLine("Exception");
                            }
                        }
                        file.WriteLine("------------------------------------------------------------------");
                    }
                }

**Comment by h1cks** [comment]
Will close issue as original item is answered.  Reflection issue needs more investigation.

**Comment by xoofx** [comment]
>  Reflection issue needs more investigation.

Not sure what you are looking for, but as I mentioned previously, using reflection on SharpDX ComObject will query properties that may create new ComObject, a reason why displaying them in via ObjectTracker would feed back the ObjectTracker.
