### ISSUE TITLE
issue with norton who find sharpdx as a virus ...

### ISSUE THREAD

**Issue by titof49** [sharpdx/SharpDX#880]
all description of the issiue done on the Norton site.

https://community.norton.com/en/forums/critical-issue-issue-visual-studio-sharpdx-and-norton#comment-7433811

dont hesiate to comment.

Br,

**Comment by Tiba3195** [comment]
uninstall Norton, that's your problem.

**Comment by xoofx** [comment]
As it is a Norton issue, we can't do much about it
