### ISSUE TITLE
VideoFormatGuids.FromFourCC throws because of invalid input

### ISSUE THREAD

**Issue by crowbar27** [sharpdx/SharpDX#886]
The implementation of `VideoFormatGuids.FromFourCC` uses `FourCC.ToString()` to construct the format GUID in the following way:

`return new Guid(string.Concat(fourCC.ToString(), "-0000-0010-8000-00aa00389b71"));`

However, `FourCC.ToString()` returns the four CC as string, ie "WMV3", which makes the call to `Guid` fail. A simple workaround would be using

`((uint) fourCC).ToString("X08") + "-0000-0010-8000-00aa00389b71"`

Alternatively, `FourCC.ToString()` could be modified to accept a format string allowing for producing hex output.

**Comment by xoofx** [comment]
Thanks for reporting this. A PR would be welcome.
