### ISSUE TITLE
Building SharpDX for Dummies?

### ISSUE THREAD

**Issue by kburgoyne** [sharpdx/SharpDX#888]
Hey guys. I've cloned the repo, installed Win10 Creators, installed the Win10 Creators SDK, installed VS2017 Community with ALL features selected (as is my habit).  Doing a "Rebuild entire solution" for SharpDX just cranks out a bunch of errors.  One of them (not even sure if this is the main one) is something about a Include var not being defined, or something.

Anyway... I have a major C# Universal (as in Win8.1) 3D game app running very nicely on the SharpDX 3.1.1 from Nuget.  Then when I went to track down and clean up memory leaks it became pretty apparent through some very simple tests that unmanaged heap was being leaked on vertex buffer allocs/deallocs.

I won't bother with the details since I'm seeing hints SharpDX isn't for WinPhone8.1 apps.  I'll just say a very simple tiny loop test (repeated creates and immediate Dispose()), in combination with heap snapshots, confirmed the issue while excluding any possibility of the problem being forgetting to Dispose().  SharpDX's own object tracker even thought everything was disposed, but the unmanaged heap snapshots disagreed.

Thus I'm looking at moving onto Win10 UWP.  This time I'm hoping to actually build SharpDX for UWP so I can debug into it if I run into issues.

Since my goal is really to get back to the game app and not make a career out of learning to build SharpDX, is there any guidance anywhere beyond the simple page which says to make sure you have the Creators SDK and various VS2017 components installed?  Seems like there might need to be some config settings I need to make, or perhaps just issuing a "Rebuild entire solution" isn't the right approach.

THANKS!

**Comment by xoofx** [comment]
Could you put the log of the compilation in a gist?

**Comment by kburgoyne** [comment]
Thanks.  I'm guessing this is what you need...

https://gist.github.com/kburgoyne/b43b3b5c253eb3a6e80c5dc748004a71

Bear with me a little here.  I'm learning as I go with this GitHub stuff.

In order to keep things as clean as possible, I performed a new clean clone to a new directory, had VS2017 open SharpDX.sln, right-clicked on the solution and chose "Rebuild Solution".

**Comment by xoofx** [comment]
Ok, so it seems that this the first important error:

```
6>SharpGen(1,1): error : System.IO.DirectoryNotFoundException: Directory [\include] not found in config file [sharpdx-root]
```
Which is most likely related to this [line 26 in Mapping.xml](https://github.com/sharpdx/SharpDX/blob/be1c541a9716c8657b6f7cd4b77fad4f27db264e/Source/Mapping.xml#L26)

```
 <include-dir>$(VC_TOOLS_PATH)\include</include-dir>
```

Which is setup for the CodeGenApp via the bat command argument  in [RunGenerator.bat line 18](https://github.com/sharpdx/SharpDX/blob/308744320a8e7b440d1bea4a30c392ecd65ba65f/Source/Tools/SharpGen/RunGenerator.bat#L18)

@jkoritzinsky didn't look carefully at this changes. Looks like there is a failure at detecting that VC++ is actually installed. Question: Why making all this detection in a `.bat` while previously we were able to do this detection in CodeGenApp directly and providing better error? (In our case, we should also produce an error if vctools is NULL)

**Comment by jkoritzinsky** [comment]
We're using VSWhere to find the installation since the location is no longer stored in the registry. We could also use the COM interface, but I decided to but it into RunGenerator.bat and use the command line since that felt like it fit a little better at the time. It looks like I didn't put in any code to error out when the correct installation isn't found. And it looks like on line 10 I had vswhere check for an installation with the Windows 10 SDK to make sure VS has that installed as well. However, that did not get updated when we updated to the Creators SDK (I apologize for missing that in the PR).

**Comment by kburgoyne** [comment]
Wow, you mean it wasn't me screwing up?  What a nice change of pace. :-)

So given I'm a relatively ignorant newbie to how things work around here... Should I clone again now, or am I waiting for some other "thing" to occur first?  (Branch merge, review process, whatever...)  At least I'm getting a first hand GitHub project education out of all this.

Thanks for the really amazing and efficient response to looking into this.  I'm impressed.  :-)

**Comment by kburgoyne** [comment]
BTW... I'm noticing I'm also getting a series of NuGet restore errors in the "Package Manager" output window when I open SharpDX in VS2017 after cloning it.  The following output is from three solution opens with intervening closes.  The precise details are NOT repeatable.  VS2017 will complain about a seemingly random set of projects for each different open when I repeat this experiment after cloning a fresh copy each time.  The "++++" lines below separate the output from the three solution opens.  Since VS2017 complains about a seemingly random set of projects each time, I'm actually wondering if this is a VS2017 problem with the randomness triggered by the parallel processing of opening the projects.

Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.Direct3D10 could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.Direct3D10 could not be loaded.
Restoring NuGet packages...
Time Elapsed: 00:00:17.1063430
========== Finished ==========

Restoring NuGet packages...
Time Elapsed: 00:00:11.6800926
========== Finished ==========

Restoring NuGet packages...
Time Elapsed: 00:00:21.3056043
========== Finished ==========

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.Direct3D10 could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.Direct3D10 could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.Direct3D12 could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.Direct3D12 could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.Direct3D12 could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.Direct3D12 could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.Direct3D12 could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.DirectManipulation could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.Direct3D11.Effects could not be loaded.
Restoring NuGet packages...
Time Elapsed: 00:00:11.3748054
========== Finished ==========

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.Direct3D10 could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.Desktop could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.Desktop could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.Direct3D12 could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.Direct3D12 could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.DirectManipulation could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.Animation could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.Animation could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SharpDX.Animation could not be loaded.
Restoring NuGet packages...
Time Elapsed: 00:00:13.7103692
========== Finished ==========

**Comment by jkoritzinsky** [comment]
As of right now, you can install the Windows 10 Anniversary SDK to get the build working. We'll remove that check so the build won't fail that way. I'm not sure what's happening with the NuGet situation though.

**Comment by kburgoyne** [comment]
One more time...  The build output is at:

https://gist.github.com/kburgoyne/32525e61d8b7e60492b8b016cc473d96

I've attached a JPG screen clip showing the SDK's installed as per Control Panel Programs and Features.  Microsoft doesn't really say "Anniversary" in the SDK archive.  I found an old MS blog posting announcing the Anniversary RTM SDK as being 14393.795.  I had 14393.33 installed which I guess was an RC.  I installed 14393.795, rebooted, cloned a fresh SharpDX copy, did a build entire solution, and created the gist (above) from the output.  Unfortunately still failing.

Can you confirm 14393.795 is the SDK you were thinking I needed to install?  Or are you looking for a different version not shown in the attached JPG? I didn't readily find anything in the MSFT Win10 SDK archive that I didn't have installed (other than the one I installed).

Is there anything I can investigate to see if "whatever" is on my system in the location the build is trying to find it?  Anything I can watch run separate from the build process to collect information on how its responding to my system?

Thanks!

![sdkinstalls](https://cloud.githubusercontent.com/assets/40460/25467621/431e47ac-2ac4-11e7-88ac-c6baea9813fb.JPG)

**Comment by kburgoyne** [comment]
Building current release successfully.
