### ISSUE TITLE
Spin off SharpGen/SharpCli tools to their own repo and have SharpDX depend on them

### ISSUE THREAD

**Issue by jkoritzinsky** [sharpdx/SharpDX#891]
The generator tools that SharpDX uses are extremely useful for any project that uses COM interop. However, to use these tools each person would have to pull down SharpDX and built it themselves just to get the SharpGen/SharpCLI binaries.

I propose that the SharpGen/SharpCLI tools (basically all of the projects in the SharpDX-Tools solution) be spun off into a separate repo along with the core Win32 classes they always have to generate (some portions of the core SharpDX assembly). This will allow other projects to consume these tools and allow us to update them independently since as of #890 there are no dependencies between the Tools and the rest of the project excluding the core classes.

I am willing to do the work to separate out the code into its own repo and then transfer ownership back to the SharpDX org on GitHub.

**Comment by xoofx** [comment]
I wanted to do this quite some time ago (https://github.com/xoofx/SharpCppGen), and I even started the work but never pushed it. I didn't have enough motivation to do this work... 

So if you are motivated for this, that would be amazing!

At that time, I developed [git-rocket-filter](https://github.com/xoofx/GitRocketFilter) specifically for extracting all the folders and relevant commits from SharpDX. 

I can open a repository under SharpDX org and give you write access to it if you want. Let me know.

**Comment by jkoritzinsky** [comment]
Sure! Btw git added a feature to extract subtrees a while back apparently.

I won't have time to work on it this week (exams). But ill have some time over the next few weeks/months to get it all cleaned up and nice.

**Comment by xoofx** [comment]
> Sure! Btw git added a feature to extract subtrees a while back apparently.

yep, It was already the case when I developed git-rocket-filter. But it is a lot less convenient when you need to have a white and black list together... and If I remember, this is not really a subtree that you need but more a full filter branch (you don't want a commit that removes all the code, you want to rework all the commits from the beginning and keep only the folders/file changes/commits related to SharpGen)

> I won't have time to work on it this week (exams). But ill have some time over the next few weeks/months to get it all cleaned up and nice.

no worries, no rush 😉

**Comment by jkoritzinsky** [comment]
I've got this in the https://github.com/jkoritzinsky/SharpTools repository as of now.
