### ISSUE TITLE
[DirectInput] ProductName not trimmed for devices (null characters at the end)

### ISSUE THREAD

**Issue by peter249** [sharpdx/SharpDX#892]
Seems similar to issue #784.

ProductName has nulls as part of string.

Attached a small test program to reproduce the problem configured by NuGet Manager
[SharpDXTest.zip](https://github.com/sharpdx/SharpDX/files/981644/SharpDXTest.zip)

Works if I build from sources in debug (VS2017pro, Win 10 Creators)

Fails if using NuGet package install.

**Comment by xoofx** [comment]
> Fails if using NuGet package install.

Which one? The pre release version (4.0.0.pre-xxxx) or the current stable version (3.1.x)

**Comment by peter249** [comment]
sorry, vers 3.1.1

**Comment by xoofx** [comment]
afair, I believed it was this in the meantime, try to use 4.0.0 pre nuget version.

**Comment by peter249** [comment]
Thanks, the prerelease version 4.00-ci145 seems to work just fine.
