### ISSUE TITLE
Support for ID3D12GraphicsCommandList::ExecuteIndirect

### ISSUE THREAD

**Issue by matmuze** [sharpdx/SharpDX#893]
Hi there,

I did not find any binding to the function ExecuteIndirect, is it in the roadmap ?

Best,
Mat.

**Comment by xoofx** [comment]
It should be there, as part of Shar[DX 4.0.0+ pre release Nuget packages

**Comment by mrvux** [comment]
As a side note, this was here for ages, and used it reasonably extensively, so I can also confirm it is working as expected.

the method is to be found in GraphicsCommandList.ExecuteIndirect

PS : Maybe we can close issue? as it is there in any case?

**Comment by amerkoleci** [comment]
I suppose we can close this, I also added another overload for ExecuteIndirect
