### ISSUE TITLE
Adding wrapper public methods for the 3.1.x release

### ISSUE THREAD

**Issue by jclin** [sharpdx/SharpDX#896]
Hello,
I need to add wrapper public methods to some DirectWrite interfaces, such as [IDWriteFontFallback::MapCharacters](https://msdn.microsoft.com/en-us/library/windows/desktop/dn280480(v=vs.85).aspx). 

Although that should be straightforward, would it be possible to push these changes to a 3.1.2 release? FWIW, I am developing against 3.1.1 at work, and we'd rather not have to make and maintain a separate fork.

Thanks,
Jerry

**Comment by xoofx** [comment]
Could you try to use latest 4.0.0? While features for 4.0.0 should not change a lot compare to 3.x, the build process is quite different (and I can't afford the time setup a build process for a previous version). I'm planning to release 4.0.0 this week.

**Comment by jclin** [comment]
Sure, we can do that. We'll try to put up a PR later this week.
