### ISSUE TITLE
4.0.0 Release

### ISSUE THREAD

**Issue by jclin** [sharpdx/SharpDX#901]
Hello,

IIRC, 4.0.0 was originally going to be released [last week](https://github.com/sharpdx/SharpDX/issues/896) - any idea as to a time table? FWIW, we're willing to help with any outstanding issues in order to get the release out sooner.

:beers:,
Jerry

**Comment by rockhymas** [comment]
Yep, I'm also happy to help out. SharpDX is seriously awesome, and has made our lives easier. Would love to give back and also see the release go out.

**Comment by xoofx** [comment]
Was hyper busy last week, and being hyper hyper busy this week (zero sparetime left), so I will try next week (should be back to a bit less busy week hopefully 😅 )

**Comment by jclin** [comment]
No worries, and let us know if there's anything we can do to help!

**Comment by xoofx** [comment]
4.0.0 is published

**Comment by rockhymas** [comment]
Awesome, thanks!

**Comment by jclin** [comment]
:beers:
