### ISSUE TITLE
Create PSO Failed.

### ISSUE THREAD

**Issue by LinkClinton** [sharpdx/SharpDX#916]
It is ok for this code:
`float4 PSmain(PsInput input) : SV_TARGET
{
    return input.color;
`

but bad for this:

`float4 PSmain(PsInput input) : SV_TARGET
{
    return cube_texture.Sample(Sampler, input.tex);
}`

HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments in 
CreateGraphicsPipelineState

**Comment by LinkClinton** [comment]
I have tried [this](https://github.com/sharpdx/SharpDX-Samples/blob/ed7e80cdcac145cf1864c6b9358a558e5fe8deb6/Desktop/Direct3D12/HelloTexture/shaders.hlsl#L22) code.

But I failed.

**Comment by xoofx** [comment]
Have you tried to create D3D12 device in debug and check the output VS debug window? (with unsafe debugging mode enabled)

You issue report is unusable otherwise

**Comment by LinkClinton** [comment]
Oh! 
I get why I create it failed. 

And when I compile a shader , is `CompilationResult.HasErrors` ok? 
I get messages that show error, but `HasErrors` is false.

Yeah,It is not a issue.
Thx.
