### ISSUE TITLE
NuGet Package Dependencies for 4.0.1

### ISSUE THREAD

**Issue by kburgoyne** [sharpdx/SharpDX#919]
Just an FYI.  Pretty minor.

Just switched to using the 4.0.1 NuGet packages. I was previously referencing clone builds made on my own system.  In the process it appears the package dependencies are not in place for the various SharpDX packages on NuGet.  Under SharpDX 3.X I was in the habit of grabbing SharpDX.Direct3D11 and letting the dependencies do most of the work grabbing most of the other modules at the same time.  That trick didn't work with 4.0.1.

Not exactly high priority for anyone who has developed experience with what they need.  For newbies it'll be another addition to the learning curve.

Of course I think this is the first NuGet grabs I've made using VS2017 (as opposed to VS2015), so I suppose I'm assuming it isn't VS2017 that might be at fault.

On the plus side, the switch from referencing a clone to referencing the NuGet packages was flawless when it came to building and running.

**Comment by xoofx** [comment]
Just checked `SharpDX.Direct3D11` and it is working fine with plain nuget and from VS2017, getting the following log:

```
Attempting to gather dependency information for package 'SharpDX.Direct3D11.4.0.1' with respect to project 'TestSharpDXNuGet', targeting '.NETFramework,Version=v4.5'
Gathering dependency information took 3.03 sec
Attempting to resolve dependencies for package 'SharpDX.Direct3D11.4.0.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'SharpDX.Direct3D11.4.0.1'
Resolved actions to install package 'SharpDX.Direct3D11.4.0.1'
Retrieving package 'SharpDX 4.0.1' from 'NuGet Feed 3.0'.
Retrieving package 'SharpDX.Direct3D11 4.0.1' from 'NuGet Feed 3.0'.
Retrieving package 'SharpDX.DXGI 4.0.1' from 'NuGet Feed 3.0'.
Adding package 'SharpDX.4.0.1' to folder 'C:\Code\Temp\TestSharpDXNuGet\packages'
Added package 'SharpDX.4.0.1' to folder 'C:\Code\Temp\TestSharpDXNuGet\packages'
Added package 'SharpDX.4.0.1' to 'packages.config'
Successfully installed 'SharpDX 4.0.1' to TestSharpDXNuGet
Adding package 'SharpDX.DXGI.4.0.1' to folder 'C:\Code\Temp\TestSharpDXNuGet\packages'
Added package 'SharpDX.DXGI.4.0.1' to folder 'C:\Code\Temp\TestSharpDXNuGet\packages'
Added package 'SharpDX.DXGI.4.0.1' to 'packages.config'
Successfully installed 'SharpDX.DXGI 4.0.1' to TestSharpDXNuGet
Adding package 'SharpDX.Direct3D11.4.0.1' to folder 'C:\Code\Temp\TestSharpDXNuGet\packages'
Added package 'SharpDX.Direct3D11.4.0.1' to folder 'C:\Code\Temp\TestSharpDXNuGet\packages'
Added package 'SharpDX.Direct3D11.4.0.1' to 'packages.config'
Successfully installed 'SharpDX.Direct3D11 4.0.1' to TestSharpDXNuGet
Executing nuget actions took 1.6 sec
Time Elapsed: 00:00:04.8077665
========== Finished ==========
```

So not sure what is happening on your side...

**Comment by kburgoyne** [comment]
Interesting.  I just tried again using a blank UWP app. I tell "Manage NuGet packages for solution..." to install SharpDX.Direct3D11.  I get a dialog saying it's going to install SharpDX, SharpDX.Direct3D11, and SharpDX.DXGI.  The Output window then reports the following then the project's references only shows SharpDX11.Direct3D11.  I'm assuming references should show all three like it did under VS2015. Intellisense also doesn't seem to be able to find things in the namespaces.

Well... since you have success, this is probably best left as an experience to be kept in mind incase anybody else reports it.  There's a perfectly straight-forward workaround (do them all separately).

```
Restoring packages for S:\ProjNet\CereQuest\Apps\Win10Uwp\App2\App2\App2.csproj...
Committing restore...
Writing lock file to disk. Path: S:\ProjNet\CereQuest\Apps\Win10Uwp\App2\App2\obj\project.assets.json
Restore completed in 931.35 ms for S:\ProjNet\CereQuest\Apps\Win10Uwp\App2\App2\App2.csproj.
Successfully installed 'SharpDX 4.0.1' to App2
Successfully installed 'SharpDX.Direct3D11 4.0.1' to App2
Successfully installed 'SharpDX.DXGI 4.0.1' to App2
Executing nuget actions took 1.37 sec
Time Elapsed: 00:00:02.4258351
========== Finished ==========

```
