### ISSUE TITLE
How to GPU profiling with BeginEvent in DX11 ?

### ISSUE THREAD

**Issue by matmuze** [sharpdx/SharpDX#922]
Hello,

I would like to do very lightweight GPU profiling for DX11 in **real-time**, and therefore I would like to know an easy way to get the time it takes to perform a given GPU command.

Thanks in advance.
Mat.

**Comment by xoofx** [comment]
This is not a good place to ask question about Direct3D API.  Specifically to your question, google gives you this http://reedbeta.com/blog/gpu-profiling-101/ and otherwise you should ask this question to www.gamedev.net/forum/10-directx-and-xna/

**Comment by matmuze** [comment]
Yeah you are right I thought that because of C# there would be a special sauce to do the DX11 queries... But even without examples I eventually managed to do the queries following the C++ doc.
