### ISSUE TITLE
System.EntryPointNotFoundException "Can't find the entry point" MFCreateDXGIDeviceManager" in DLL "Mfplat.dll".'

### ISSUE THREAD

**Issue by ToxaDev** [sharpdx/SharpDX#930]
Version 4.0.1

Try to launch Simple and got exception in:
//Reset device
manager = new DXGIDeviceManager();

**Comment by ToxaDev** [comment]
Windows 7 x64 Ultimate

**Comment by amerkoleci** [comment]
MFCreateDXGIDeviceManager is supported starting from Windows 8, take look here:
https://msdn.microsoft.com/en-us/library/windows/desktop/hh162750(v=vs.85).aspx

**Comment by ToxaDev** [comment]
Thanks
