### ISSUE TITLE
Share experience using SharpDX with .NETStandard 2.0 under UWP 6.0

### ISSUE THREAD

**Issue by JimSEOW** [sharpdx/SharpDX#936]
Here we collect any issue related to testing the latest SharpDX build with UWP6.0

In my experience, the [W10 and W10M build ](https://github.com/sharpdx/SharpDX/issues/927#issuecomment-324937295)can affect the outcome

**Comment by xoofx** [comment]
Let's keep issue #927 for tracking UWP problems. Please refrain from opening this problem on multiple issues.
