### ISSUE TITLE
Latest sharpdx fails windows store certification! (4.0.1)

### ISSUE THREAD

**Issue by Danthekilla** [sharpdx/SharpDX#939]
We have updated our engine to use SharpDX 4.0.1 and now our game fails the windows store verification because of illegal dlls in SharpDX.

**Supported API test**

**FAILED**
_Error Found: The supported APIs test detected the following errors:_

API MFCreateAudioRendererActivate in mf.dll is not supported for this application type. SharpDX.MediaFoundation.dll calls this API.
API MFCreatePresentationClock in mf.dll is not supported for this application type. SharpDX.MediaFoundation.dll calls this API.
API MFCreateMuxStreamAttributes in mfplat.dll is not supported for this application type. SharpDX.MediaFoundation.dll calls this API.
API MFCreateMuxStreamMediaType in mfplat.dll is not supported for this application type. SharpDX.MediaFoundation.dll calls this API.
API MFCreateMuxStreamSample in mfplat.dll is not supported for this application type. SharpDX.MediaFoundation.dll calls this API.
API MFCreateSensorGroup in mfplat.dll is not supported for this application type. SharpDX.MediaFoundation.dll calls this API.
API MFCreateSensorStream in mfplat.dll is not supported for this application type. SharpDX.MediaFoundation.dll calls this API.

Impact if not fixed: Using an API that is not part of the Windows SDK for Windows Store apps violates the Windows Store certification requirements. 

What can be done about this?

**Comment by xoofx** [comment]
They need to be discarded in SharpDX codegen:

https://github.com/sharpdx/SharpDX/blob/9db524770d6250e7c81d400102b77cbfc0c5cb58/Source/SharpDX.MediaFoundation/Mapping-core.xml#L1019-L1028

PR welcome.

**Comment by Danthekilla** [comment]
#940 

I have made the required changes and everything seems to build correctly, it would be great if these could be tested and accepted and pushed to nuget.

**Comment by xoofx** [comment]
> I have made the required changes and everything seems to build correctly, it would be great if these could be tested and accepted and pushed to nuget.

This should be part of the 4.1.0 pre-release nuget package (should be pushed in a few minutes)

**Comment by devedse** [comment]
I just tried to submit a package using MonoGame and SharpDX 4.2.0, however I'm still seeing some errors in the Package Certification:

![image](https://user-images.githubusercontent.com/2350015/49802395-0d2a8680-fd4d-11e8-96a3-8f64838f60da.png)

Shall I open a new issue?

https://github.com/MonoGame/MonoGame/issues/5003#issuecomment-446193549

**Comment by devedse** [comment]
Tagging @xoofx

**Comment by xoofx** [comment]
For GetModuleHandle/LoadLibrary, It looks like a regression coming from 556aee5cd01b7dfa4ded256ef7510f57bcb9df0e by @Ziriax 

The code should be only valid for DESKTOP_APP.

For the MF function, similar fix to this issue should be done.

PR Welcome.

**Comment by devedse** [comment]
@xoofx , could you check my pull request?
