### ISSUE TITLE
System.Reflection.ObfuscationAttribute conflict

### ISSUE THREAD

**Issue by aleksrdm** [sharpdx/SharpDX#947]
New Windows SDK 16299 (Fall Creators Update) with .NET Standard 2.0 brought back System.Reflection.ObfuscationAttribute, and it is now in conflict with one declared in SharpDX package.

**Comment by xoofx** [comment]
Like the class in SharpDX could be removed entirely. It was used at some point to be compatible with some obfuscation tools. So PR welcome.
