### ISSUE TITLE
Direct3D12 Fence Value should be ulong instead of long

### ISSUE THREAD

**Issue by amerkoleci** [sharpdx/SharpDX#948]
As title says, Fence, Signal and CommandQueue now uses long, should be ulong as native UINT64 type, any thought?

I can submit PR

**Comment by xoofx** [comment]
If we could stay with long, I would prefer. Otherwise it will have to go through a longer route of updating SharpGen (to support unsigned) and activate only this option for Direct3D12...

**Comment by amerkoleci** [comment]
I see but in that case long wont fit as u long

**Comment by xoofx** [comment]
what is it used for? we have plenty of uint that have been used as int in SharpDX for the past years and while not ideal, it haven't heard any complain about this...

**Comment by amerkoleci** [comment]
I understand what you mean and for me is ok, just wanted to point out the logic :)
