### ISSUE TITLE
How do you know which trigger is pressed ?

### ISSUE THREAD

**Issue by Zayceur** [sharpdx/SharpDX#960]
Hello,

I have an issue. I want to get the state (and the analog value) of the right and left trigger. Both of these values are stored in the Z-Axis. The problem is when I press no trigger, the Z-Axis value is the same as if I press the two trigger at the same time.

`Joystick.GetCurrentState().Z` give me (exactly) the same value !

I use DirectInput.

Do someone have a solution to this issue ?

Thanks a lot.

Zayceur

**Comment by Gavin-Williams** [comment]
If this is for a gamepad, why aren't you using Windows.Gaming.Input.Gamepad ? I would suggest that's the best way to gather gamepad input, assuming your not on legacy windows.

**Comment by Zayceur** [comment]
Thanks a lot I moved to XInput !
