### ISSUE TITLE
ClearRenderTargetView color problems

### ISSUE THREAD

**Issue by pekira001** [sharpdx/SharpDX#966]
`_Device.ImmediateContext.ClearRenderTargetView(TargetView, new RawColor4(0, 165, 35, 1));`
On the code above if R G an B are different of 0 only white will be rendered but if 1or 2 of them is 0 then it will render properly.
I am using all the latest versions.
Can anyone help me?

**Comment by Gavin-Williams** [comment]
RawColor4 takes floats in the range {0,1}, so (1,0,0,1) = Red. You're example of (0,165,35,1) is actually equal to (0,1,1,1). To represent mid-red you would use (0.5f, 0, 0, 1)
