### ISSUE TITLE
Cannot add SharpDX source projects to own solution

### ISSUE THREAD

**Issue by Ziriax** [sharpdx/SharpDX#968]
It seems that to build SharpDX from sources, it uses MSBuild stuff from `sharpdx.targets`.

This file refers to `$(SolutionDir)`, but this links the SharpDX projects to the SharpDX solution.

Changing this to `$(ProjectDir)..\..` instead allows the SharpDX projects to be added to any solution.

I have a pull request ready, but before submitting this, I might be missing the reason why `$(SolutionDir)`  is used in `sharpdx.targets`?

**Comment by xoofx** [comment]
> I have a pull request ready, but before submitting this, I might be missing the reason why $(SolutionDir) is used in sharpdx.targets?

Don't remember and using `$(ProjectDir)..\..` sounds fine

**Comment by Ziriax** [comment]
#971
