### ISSUE TITLE
Direct2D1 RenderTarget.FillGeometry is not working

### ISSUE THREAD

**Issue by Dunkhan** [sharpdx/SharpDX#985]
I added a path geometry to the MiniRect example project in the samples library. I am using the SharpDX NuGet packages.

The DrawGeometry call works correctly, the geometry is drawn, using the brush specified.
The FillGeometry call does nothing at all, using the same geometry and brush.

This is causing problems for the Oxyplot SharpDX project:
https://github.com/oxyplot/oxyplot-sharpdx/issues/6

Here is the sample code I used
https://pastebin.com/HTn1P5Gd

**Comment by mrvux** [comment]
Hello

On your code, line 85, you need to set FigureBegin to Filled instead of Hollow:  
 sink.BeginFigure(points[0], FigureBegin.Filled);

From MSDN source:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd368106(v=vs.85).aspx

**Comment by Dunkhan** [comment]
Thanks. It may seem obvious but I was focused on a whole different codebase and am not familiar with SharpDX at all.
I will close this because it is an invalid report.
