### ISSUE TITLE
Update in Build ci217 - breaks XInput

### ISSUE THREAD

**Issue by h1cks** [sharpdx/SharpDX#987]
Believe related to change -> https://github.com/sharpdx/SharpDX/commit/83537beec66649a417e64d9f8b6560f256e44ffc?_pjax=%23js-repo-pjax-container

The change from a 2 byte field to a 4 byte field has misaligned all the states for the buttons in the SharpDX.XInput.State.   Believe the GamepadButtonFlags may be the issue (size being 2 bytes).

Can this be confirmed/denied.  But I have moved back to version ci-184 and issue has disappeared.

**Comment by xoofx** [comment]
yeah, actually this change is bad (my fault when reviewing). This should be reverted. @Gavin-Williams could you revert this change?
