### ISSUE TITLE
Can't Draw Text with Direct2D1 & DirectWrite :(

### ISSUE THREAD

**Issue by SharinganShuriken** [sharpdx/SharpDX#999]
Hello Guys,

i want to draw a text in my form, but everytime i get a Access Violation Exception if i want to create the rendertarget :(

Maybe you can help me and explain me what i do wrong?

`       private DeviceContextRenderTarget device;
        private TextFormat format;
        private SolidColorBrush brush;

        private void button1_Click(object sender, EventArgs e)
        {
            this.device = new DeviceContextRenderTarget(new SharpDX.Direct2D1.Factory(SharpDX.Direct2D1.FactoryType.SingleThreaded),
                new RenderTargetProperties(new PixelFormat(SharpDX.DXGI.Format.B8G8R8A8_UNorm, AlphaMode.Ignore)));
            this.format = new TextFormat(new SharpDX.DirectWrite.Factory(), "Arial", 1.0f);
            SharpDX.DXGI.Surface surface = new SharpDX.DXGI.Surface(this.Handle);
            RenderTarget renderTarget = new RenderTarget(this.device.Factory, surface, new RenderTargetProperties());
            this.brush = new SolidColorBrush(renderTarget, SharpDX.Color4.Black);

            this.device.BeginDraw();
            this.device.DrawText("Hello World", this.format, new SharpDX.RectangleF(0, 0, 100, 100), this.brush);
            this.device.EndDraw();
        }`

**Comment by xoofx** [comment]
> SharpDX.DXGI.Surface surface = new SharpDX.DXGI.Surface(this.Handle);

You can't do this. The handle of the window has nothing to do with the COM pointer of a DXGI surface. Please follow the [Direct2D documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/dd370990(v=vs.85).aspx) to properly use Direct2D with a HWND.
